# Introduction
This notebook creates a first cut of a sample metadata file to be used in public release, i.e. in Panoptes

# Plan
* Sanity check ox_codes/src_codes from Cristina
* Incorporate data from Cristina
* Incorporate PDNA data from Rob
* Remove any reliance on batch_arrived year
* Check all locations vs previous Panoptes
* Make manual changes as per notes
* Create tables of study vs location and study vs year
* Send Rob all different dates for 1044

In [1]:
%run _standard_imports.ipynb

/Users/rpearson/miniconda3/envs/biipy/lib/python3.5/site-packages/rpy2/robjects/robject.py:6: UserWarning: use 'source("https://bioconductor.org/biocLite.R")' or 'source("http://bioconductor.org/biocLite.R")' to update 'BiocInstaller' after library("utils")

  rpy2.rinterface.initr()

python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12)
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]
numpy 1.11.2
scipy 0.18.1
pandas 0.19.0
numexpr 2.6.1
pysam 0.9.1.4
petl 1.1.0
petlx 1.0.3
vcf 0.6.8
vcfnp 2.2.0
h5py 2.6.0
tables 3.3.0

In [2]:
output_dir = "/nfs/team112_internal/rp7/data/methods-dev/builds/Pf6.0/20161214_samples_which_release"
!mkdir -p {output_dir}

report_sample_status_fn = "/nfs/team112_internal/rp7/data/methods-dev/builds/Pf6.0/20161214_parse_sample_status_report/2016_12_07_report_sample_status.txt"
# solaris_fn = "%s/PF_metadata_base.csv" % output_dir

# olivo_fn sent by Olivo 10/11/2016 14:44 (filed in Genetic Report Card)
olivo_fn = "/nfs/team112_internal/rp7/data/methods-dev/builds/Pf6.0/20161118_compare_7979_vs_Pf6_GRC/samplesMeta5x-V1.0.xlsx"
# elife_fn sent by Rob 19/12/2016 13:15 (filed in Pf6.0 and Pv3.0)
elife_fn = "%s/SamplesMetadata.xlsx" % output_dir
sample_4_0_fn = "/nfs/team112_internal/production/release_build/4_0_study_samples.tab"
sample_5_0_fn = "/nfs/team112_internal/production/release_build/5_0_study_samples.tab"
sample_5_1_fn = "/nfs/team112_internal/production/release_build/5_1_study_samples_all.tab"
sample_6_0_fn = "/nfs/team112_internal/production/release_build/Pf/6_0_release_packages/Pf_60_sample_metadata.txt"
oxford_table_fn = "%s/oxford.txt" % output_dir
sampling_date_fn = "%s/sampling_date.txt" % output_dir
solaris_dates_fn = "%s/solaris_dates.txt" % output_dir

panoptes_metadata_fn = "%s/pf_6_0_panoptes_samples_20170123.txt.gz" % output_dir
panoptes_final_metadata_fn = "%s/pf_6_0_panoptes_samples_final_20170123.txt.gz" % output_dir


sample_information_sheets = collections.OrderedDict()
sample_information_sheets['1044_Oct2012_NIH'] = ["%s/List of DNACF11_TRAC2012 and NIH2012_Oct2012_Sanger.xlsx" % output_dir, 'NIH STUDY for Sanger']
sample_information_sheets['1044_Oct2012_TRAC'] = ["%s/List of DNACF11_TRAC2012 and NIH2012_Oct2012_Sanger.xlsx" % output_dir, 'TRAC STUDY for Sanger']
sample_information_sheets['1044_Dec2012'] = ["%s/DNA from CF11 blood sample for Sanger_Dec2012.xlsx" % output_dir, 'NIH STUDY-PF']
sample_information_sheets['1044_Jan2014'] = ["%s/List of DNA-CF11_Protocol12-I-N163_2013 to Sanger_27January2014 Rick F.xlsx" % output_dir, 'PF-DNA from adapted culture (2)']
sample_information_sheets['1101_Apr2013'] = ["%s/175x blood pellets DRC marie april 2013.xlsx" % output_dir, 'Partner Study Sample Info']
sample_information_sheets['1052_Sep2015'] = ["%s/(Sample management) 1052-PF-TRAC-WHITE.xlsx" % output_dir, 'Samples']
# sample_information_sheets['1136_Jun2015'] = ["%s/Alfred and Umberto samples study 1136.xlsx" % output_dir, 'Plasmodium Samples']
sample_information_sheets['1138_Mar2015'] = ["%s/sample info sheet_v1 2_OM-1 FALCIPARUM CF(2)(1).xlsx" % output_dir, 'Samples']
# sample_information_sheets['1137_Jul2015'] = ["%s/Umberto samples study 1137.xlsx" % output_dir, 'Plasmodium Samples']
sample_information_sheets['1155_May2015'] = ["%s/1048-PV-SVSEA_PRICE_28112014.xlsx" % output_dir, 'Plasmodium Samples']
sample_information_sheets['1134_May2015'] = ["%s/Conway samples study 1134 (3510).xlsx" % output_dir, 'Mali']
# sample_information_sheets['1098_May2015'] = ["%s/Golassa study 1098 (3531).xlsx" % output_dir, 'Golassa SIS']
sample_information_sheets['1062_Sep2013'] = ["%s/Alyssa pf sept 2013 PNG.xlsx" % output_dir, 'QC']
sample_information_sheets['1021_Apr2010'] = ["%s/PNG malaria Isolate dataset (Pascal-20 04 10).xlsx" % output_dir, 'malaria isolates']
sample_information_sheets['1044_Aug2015'] = ["%s/1044-PF-KH-FAIRHURST.xlsx" % output_dir, 'Plasmodium Samples']
sample_information_sheets['1044_Jul2015'] = ["%s/Chanaki samples 1044.xlsx" % output_dir, 'Plasmodium Samples']
sample_information_sheets['1141_Oct2015'] = ["%s/Antoine Claessens samples study 1141.xlsx" % output_dir, 'Plasmodium Samples']
sample_information_sheets['1125_Nov2013'] = ["%s/SMRU_for_Sanger_11Nov2013 nosten x803 extractions.xlsx" % output_dir, 'Partner Study Sample Info']
sample_information_sheets['1098_Oct2016'] = ["%s/Lemu G. interim sample info sheet_v1 2_OM-1.xlsx" % output_dir, 'Samples']
sample_information_sheets['1127_Feb2014'] = ["%s/Souleymane Dama Mali Feb 2014 x191.xlsx" % output_dir, 'Partner Study Sample Info']
sample_information_sheets['1134_Feb2015'] = ["%s/Conway study.xlsx" % output_dir, 'information sheet']
sample_information_sheets['1135_May2015'] = ["%s/senegal__Sanger_sample_submission_May2015.xlsx" % output_dir, 'Plasmodium Samples']
sample_information_sheets['1147_Jul2015'] = ["%s/Copy of 1147-PF-MR-CONWAY STDY 3666 (Mauritania) (2).xlsx" % output_dir, 'Plasmodium Samples']
sample_information_sheets['1102_Nov2013'] = ["%s/Batch 1 MDG_Plasmodium Sample Information Form_Nov13.xlsx" % output_dir, 'Partner Study Sample Info']
sample_information_sheets['1102_Jan2014'] = ["%s/madagascar x48 MDG_Plasmodium Sample Information_January2014.xlsx" % output_dir, 'Partner Study Sample Info']
sample_information_sheets['1102_Apr2014'] = ["%s/Madagascar x82 2 batches.xlsx" % output_dir, 'Partner Study Sample Info']
sample_information_sheets['1102_Apr2014'] = ["%s/Madagascar x82 2 batches.xlsx" % output_dir, 'Partner Study Sample Info']
sample_information_sheets['1155_Jun2013'] = ["%s/Sarah Indonesia_Pv_Pf_050613 1.0.xlsx" % output_dir, 'extended information']
# 6.0 release_Panoptes_December 2017 RDP.xlsx was created from version sent by Rob 13/01/2017 11:27
# after changing a few values in date column (non-existent 31/6 to 30/6)
sample_information_sheets['1093_Rob'] = ["%s/6.0 release_Panoptes_December 2017 RDP.xlsx" % output_dir, '1093-PF-CM-APINJOH']
sample_information_sheets['1094_Rob'] = ["%s/6.0 release_Panoptes_December 2017 RDP.xlsx" % output_dir, '1094-PF-GH-AMENGA-ETEGO']
sample_information_sheets['1095_Rob'] = ["%s/6.0 release_Panoptes_December 2017 RDP.xlsx" % output_dir, '1095-PF-GH-ISHENGOMA']
sample_information_sheets['1096_Rob'] = ["%s/6.0 release_Panoptes_December 2017 RDP.xlsx" % output_dir, '1096-PF-GH-GHANSAH']
sample_information_sheets['1097_Rob'] = ["%s/6.0 release_Panoptes_December 2017 RDP.xlsx" % output_dir, '1097-PF-PDN-MAIGA']
sample_information_sheets['1098_Rob'] = ["%s/6.0 release_Panoptes_December 2017 RDP.xlsx" % output_dir, '1098-PF-ET-GOLASSA']
sample_information_sheets['1100_Rob'] = ["%s/6.0 release_Panoptes_December 2017 RDP.xlsx" % output_dir, '1100-PF-CI-YAVO']
sample_information_sheets['1102_Rob'] = ["%s/6.0 release_Panoptes_December 2017 RDP.xlsx" % output_dir, '1102-PF-MG-RANDRIANARIVELOJOSIA']
sample_information_sheets['1103_Rob'] = ["%s/6.0 release_Panoptes_December 2017 RDP.xlsx" % output_dir, '1103-PF-GM-AMAMBUA-NGWA']
sample_information_sheets['1107_Rob'] = ["%s/6.0 release_Panoptes_December 2017 RDP.xlsx" % output_dir, '1107-PF-KEN-KAMAU']
sample_information_sheets['1136_Rob'] = ["%s/6.0 release_Panoptes_December 2017 RDP.xlsx" % output_dir, '1136-PF-GM-NGWA']
sample_information_sheets['1137_Rob'] = ["%s/6.0 release_Panoptes_December 2017 RDP.xlsx" % output_dir, '1137-PF-GM-DALESSANDRO']

lucas_0_fn = "%s/PFDdatapg.xls" % output_dir # Email from Cristina 12/01/2017
lucas_1_fn = "%s/PFDdataset1.xls" % output_dir # Email from Cristina 12/01/2017
lucas_2_fn = "%s/PFDdataset2.xls" % output_dir # Email from Cristina 12/01/2017
lucas_3_fn = "%s/PFDdataset3.xls" % output_dir # Email from Cristina 12/01/2017
lucas_4_fn = "%s/PFDdataset4.xls" % output_dir # Email from Cristina 12/01/2017
lucas_5_fn = "%s/PFDdataset5.xls" % output_dir # Email from Cristina 12/01/2017
lucas_oxcode_fn = "%s/Soucecode_OxfordCode.xlsx" % output_dir # Email from Cristina 12/01/2017

lucas_studies = [
    '1017-PF-GH-AMENGA-ETEGO', '1094-PF-GH-AMENGA-ETEGO', '1151-PF-GH-AMENGA-ETEGO', '1152-PF-DBS-GH-AMENGA-ETEGO'
]

pdna_fn = '%s/PDNA.xlsx'

# study_summary_fn = "%s/Pf_6_0_study_summary.xlsx" % output_dir

In [3]:
# The following were not matched in any SIS, but all matched Chanaki samples 1044.xlsx if _CF11 removed,
# and all Chanaki samples 1044.xlsx are from Pursat
pursat_samples = ['163-KH1-166-1RME_CF11',
 '163-KH1-207-1_CF11',
 '163-KH1-208-1_CF11',
 '163-KH1-209-1_CF11',
 '163-KH1-210-1_CF11',
 '163-KH1-212-1_CF11',
 '163-KH1-213-1_CF11',
 '163-KH1-214-1_CF11',
 '163-KH1-215-1_CF11',
 '163-KH1-216-1_CF11',
 '163-KH1-217-1_CF11',
 '163-KH1-218-1_CF11']

In [4]:
# Email from Cristina 19/01/2017 15:26
swga_samples = [
    'PF1120-Cx8',
    'PF1121-Cx9',
    'PF1194-Cx8',
    'PF1130-Cx8',
    'PF1135-Cx8',
    'PF1143-Cx8',
    'PF1128-Cx6',
    'PF1121-Cx6',
    'PF1195-Cx6',
    'PF1128-Cx4',
    'PF1130-Cx6',
    'PF1157-Cx6',
    'PF1171-Cx6',
    'PF1141-Cx7',
    'PF1143-Cx7',
    'PF1161-Cx7',
]

In [5]:
study_sites = collections.OrderedDict()
for study in lucas_studies:
    study_sites[study] = 'Navrongo'
study_sites['1093-PF-CM-APINJOH'] = 'Buea'
# study_sites['1107-PF-KEN-KAMAU'] = 'Kombewa'
study_sites['1145-PF-PE-GAMBOA'] = 'Loreto'
study_sites['1011-PF-KH-SU'] = 'Pursat'
# study_sites['1095-PF-TZ-ISHENGOMA'] = 'Muheza' # Study description mentions 3 sites (Muheza, Muleba and Nachingwea)
# study_sites['1102-PF-MG-RANDRIANARIVELOJOSIA'] = 'Maevatanana'
study_sites['1125-PF-TH-NOSTEN'] = 'Mae Sot'
study_sites['1010-PF-TH-ANDERSON'] = 'Mae Sot'

# study_sites[''] = ''

study_sites

OrderedDict([('1017-PF-GH-AMENGA-ETEGO', 'Navrongo'),
             ('1094-PF-GH-AMENGA-ETEGO', 'Navrongo'),
             ('1151-PF-GH-AMENGA-ETEGO', 'Navrongo'),
             ('1152-PF-DBS-GH-AMENGA-ETEGO', 'Navrongo'),
             ('1093-PF-CM-APINJOH', 'Buea'),
             ('1145-PF-PE-GAMBOA', 'Loreto'),
             ('1011-PF-KH-SU', 'Pursat'),
             ('1125-PF-TH-NOSTEN', 'Mae Sot'),
             ('1010-PF-TH-ANDERSON', 'Mae Sot')])

In [6]:
source_code_sites = collections.OrderedDict()
source_code_sites['EIMK359'] = 'Kintampo'
source_code_sites['PfXUA001'] = 'Madang'
source_code_sites['sample_219'] = 'Kombewa' # See (PDN PROJECT)Sanger_MalariaGEN Partner Study Sample Information Form_Mar31  kenya kamau.xls (main data)
source_code_sites['J025616'] = 'Lab' # Antoine Claessens samples study 1141.xlsx

In [7]:
study_years = collections.OrderedDict()
study_years['1001-PF-ML-DJIMDE'] = '2007'
study_years['1004-PF-BF-OUEDRAOGO'] = '2008'
study_years['1006-PF-GM-CONWAY'] = '2008'
study_years['1007-PF-TZ-DUFFY'] = '2010'
study_years['1011-PF-KH-SU'] = '2007'
study_years['1014-PF-SSA-SUTHERLAND'] = '2009'
study_years['1015-PF-KE-NZILA'] = '2007'
study_years['1022-PF-MW-OCHOLLA'] = '2011'
study_years['1023-PF-CO-ECHEVERRI-GARCIA'] = '2011'
study_years['1024-PF-UG-BOUSEMA'] = '2010'
study_years['1026-PF-GN-CONWAY'] = '2011'
study_years['1027-PF-KE-BULL'] = '2007'
study_years['1093-PF-CM-APINJOH'] = '2013'
study_years['1107-PF-KEN-KAMAU'] = '2014'
# study_years['1135-PF-SN-CONWAY'] = '2013' # later decided to derive year from source code (end 13 or 14)
study_years['1136-PF-GM-NGWA'] = '2014'
# study_years['1141-PF-GM-CLAESSENS'] = '2014' # not necessary as all in SIS
study_years['1145-PF-PE-GAMBOA'] = '2009'
study_years['1151-PF-GH-AMENGA-ETEGO'] = '2015'
study_years['1152-PF-DBS-GH-AMENGA-ETEGO'] = '2015'

In [8]:
ox_code_year = collections.OrderedDict()
ox_code_year['PH0493-CW'] = '2010'
ox_code_year['PH0495-CW'] = '2009'
ox_code_year['PH0496-CW'] = '2009'
ox_code_year['PH0497-CW'] = '2009'
ox_code_year['PH0498-CW'] = '2009'
ox_code_year['PH0499-CW'] = '2010'
ox_code_year['PM0390-C'] = '2013' # 010011PE4J0 (mistyped in SIS)
ox_code_year['PJ0133-C'] = '2011' # inferred from similar source codes
ox_code_year['PD0047-C'] = '2004' # inferred from similar source codes
ox_code_year['PA0577-C'] = '2013' # inferred from similar source codes

In [9]:
location_sites = collections.OrderedDict()
# location_sites['Bago'] = 'Bago Division'
location_sites['Si Sa Ket'] = 'Sisakhet'
location_sites['Wang Pha'] = 'Mae Sot'
location_sites['Binh Phuoc'] = 'Binh Phuoc'
# location_sites['Faladje'] = 'Kolle and Faladje, Bamako'
# location_sites['Kolle'] = 'Kolle and Faladje, Bamako'
# location_sites['Brikama'] = 'Western Division'
location_sites['Mawker Thai'] = 'Mae Sot'
location_sites['Iquitos'] = 'Iquitos, Loreto Province'
location_sites['East Sepik'] = 'East Sepik'
# location_sites['Chikwawa'] = 'Chikwawa district'
# location_sites['Guapi'] = 'Guapi, Cauca'
# location_sites['Quibdo'] = 'Quibdó, Chocó'
# location_sites['Tumaco'] = 'Tumaco, Narino'
# location_sites['Milne Bay'] = 'Alotau'
location_sites['Kassena'] = 'Navrongo'
location_sites['Papua'] = 'Timika'

# Read in master table (6.0 release)

In [10]:
tbl_sample_6_0 = (etl
    .fromtsv(sample_6_0_fn)
)
print(len(tbl_sample_6_0.data()))
samples_6_0 = tbl_sample_6_0.values('sample').array()
print(len(samples_6_0))
tbl_sample_6_0.tail()

7182
7182

+------------+---------------------+-------------+----------------+-------------+-------------------+----------------------+-----------------------+-----------------------------+-------------------------------+----------------+----------------------+----------------------+----------------------+-------------------------+-------------------------+---------------+------------------+----------------+-----------------+------------+--------------+-------------------------+-----------------------+-----------------+--------------------------------+------------------------+-----------------+---------------------------------+-----------------------------------+---------------------------+--------------------+--------------+-------------------+-------------+------------------+------------+-----------------+-------------+---------+--------------+-------------+------------------+------------------+-------------------+-----------------------+----------------------+--------------------------+----------------------+--------------------------+-------------+-----------------+---------+---------------+-------------------+-----------+-------------+-----------------+---------+-------------+-----------------+---------+----------------+--------------------+------------+-------------------+--------------------+----------------+--------------------+--------------------+---------------------+-----------------+---------------------+---------------+-------------------------+----------------------+-----------------------+----------------------+-------------------+----------------+-------------+-------------------+----------------+-------------------+----------------+--------------------------+-----------------------+-------------------+---------------------+-----------------+-----------------+-----------------+-----------------+------------+--------------------+--------------------+--------------------+-----------+---------------+-------------------+-----------+---------------+-------------------+----------------------+-----------------------+------------------------+------------------------+-------------------------+--------------------------+--------------------------+------------------------+------------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+----------------------+-----------------------+-----------------------+------------------+-------------------------+----------------------+-----------------------+------------------------+-----------------------+-----------------------+-----------------------+-----------------------+-------------------------+----------------------+----------------------+-----------------------+------------------------+-----------------------+-------------------------+-----------------+-----------------+-----------------+-----------------+-----------------+-----------------+-----------------+-----------------+-------------------+-----------------+
| sample     | study               | source_code | run_accessions | center_name | pc_bases_callable | pc_bases_no_coverage | pc_bases_low_coverage | pc_bases_excessive_coverage | pc_bases_poor_mapping_quality | pc_bases_ref_n | bases_of_1X_coverage | bases_of_2X_coverage | bases_of_5X_coverage | pc_genome_covered_at_1x | pc_genome_covered_at_5x | mean_coverage | mean_insert_size | sd_insert_size | avg_read_length | reads      | reads_mapped | reads_mapped_and_paired | reads_properly_paired | reads_qc_failed | pairs_on_different_chromosomes | non_primary_alignments | pc_reads_mapped | pc_mapped_reads_properly_paired | pc_pairs_on_different_chromosomes | pc_non_primary_alignments | pc_reads_qc_failed | num_variants | num_pass_variants | num_missing | num_pass_missing | num_called | num_pass_called | num_hom_ref | num_het | num_pass_het | num_hom_alt | num_pass_hom_alt | num_pass_non_ref | num_biallelic_het | num_biallelic_hom_alt | num_spanning_del_het | num_spanning_del_hom_alt | num_multiallelic_het | num_multiallelic_hom_alt | num_snp_het | num_snp_hom_alt | num_snp | num_indel_het | num_indel_hom_alt | num_indel | num_ins_het | num_ins_hom_alt | num_ins | num_del_het | num_del_hom_alt | num_del | num_coding_het | num_coding_hom_alt | num_coding | num_hq_snp_called | num_hq_snp_hom_ref | num_hq_snp_het | num_hq_snp_hom_alt | num_vhq_snp_called | num_vhq_snp_hom_ref | num_vhq_snp_het | num_vhq_snp_hom_alt | num_singleton | num_biallelic_singleton | num_hq_snp_singleton | num_vhq_snp_singleton | num_bi_nonsynonymous | num_bi_synonymous | num_frameshift | num_inframe | num_bi_frameshift | num_bi_inframe | num_hq_frameshift | num_hq_inframe | num_bi_frameshift_snpeff | num_bi_inframe_snpeff | num_bi_transition | num_bi_transversion | num_bi_AT_to_AT | num_bi_CG_to_CG | num_bi_AT_to_CG | num_bi_CG_to_AT | num_phased | num_phased_non_ref | num_phased_hom_ref | num_phased_missing | num_GQ_30 | num_het_GQ_30 | num_hom_alt_GQ_30 | num_GQ_99 | num_het_GQ_99 | num_hom_alt_GQ_99 | pc_pass              | pc_missing            | pc_pass_missing        | pc_het                 | pc_pass_het             | pc_hq_snp_het            | pc_vhq_snp_het           | pc_hom_alt             | pc_pass_hom_alt        | pc_snp                | pc_biallelic          | pc_spanning_del       | pc_mutliallelic       | pc_ins                | pc_coding             | pc_bi_nonsynonymous  | pc_frameshift         | pc_bi_frameshift      | pc_hq_frameshift | pc_bi_frameshift_snpeff | pc_bi_transition     | pc_bi_AT_to_AT        | pc_bi_CG_to_CG         | pc_bi_AT_to_CG        | pc_bi_CG_to_AT        | pc_phased             | pc_phased_hom_ref     | pc_phased_missing       | pc_GQ_30             | pc_het_GQ_30         | pc_hom_alt_GQ_30      | pc_GQ_99               | pc_het_GQ_99          | pc_hom_alt_GQ_99        | mean_GQ         | mean_GQ_hom_ref | mean_GQ_het     | mean_GQ_hom_alt | mean_DP         | mean_DP_hom_ref | mean_DP_het     | mean_DP_hom_alt | mean_indel_len    | total_indel_len |
+============+=====================+=============+================+=============+===================+======================+=======================+=============================+===============================+================+======================+======================+======================+=========================+=========================+===============+==================+================+=================+============+==============+=========================+=======================+=================+================================+========================+=================+=================================+===================================+===========================+====================+==============+===================+=============+==================+============+=================+=============+=========+==============+=============+==================+==================+===================+=======================+======================+==========================+======================+==========================+=============+=================+=========+===============+===================+===========+=============+=================+=========+=============+=================+=========+================+====================+============+===================+====================+================+====================+====================+=====================+=================+=====================+===============+=========================+======================+=======================+======================+===================+================+=============+===================+================+===================+================+==========================+=======================+===================+=====================+=================+=================+=================+=================+============+====================+====================+====================+===========+===============+===================+===========+===============+===================+======================+=======================+========================+========================+=========================+==========================+==========================+========================+========================+=======================+=======================+=======================+=======================+=======================+=======================+======================+=======================+=======================+==================+=========================+======================+=======================+========================+=======================+=======================+=======================+=======================+=========================+======================+======================+=======================+========================+=======================+=========================+=================+=================+=================+=================+=================+=================+=================+=================+===================+=================+
| 'QV0107-C' | '1135-PF-SN-CONWAY' | 'PK23.14'   | 'ERR1081188'   | 'SC'        | '0.6972'          | '0.0685'             | '0.1996'              | '0.0'                       | '0.0348'                      | '0.0'          | '22039947'           | '21002572'           | '18077800'           | '0.9446'                | '0.7748'                | '14.0'        | '208.8'          | '67.1'         | '99'            | '18568603' | '3112533'    | '3085979'               | '2929928'             | '0'             | '70464'                        | '37851'                | '0.1676'        | '0.9413'                        | '0.0459'                          | '0.0122'                  | '0.0'              | '6051696'    | '3114760'         | '1190490'   | '449570'         | '4861206'  | '2665190'       | '4753502'   | '34271' | '9742'       | '73433'     | '47866'          | '57608'          | '1080'            | '6079'                | '3107'               | '20192'                  | '5555'               | '21595'                  | '2968'      | '16318'         | '19286' | '6774'        | '6774'            | '13548'   | '1350'      | '3548'          | '4898'  | '4041'      | '21601'         | '25642' | '5468'         | '18775'            | '24243'    | '1042991'         | '1038580'          | '629'          | '3782'             | '83113'            | '79918'             | '332'           | '2863'              | '286'         | '171'                   | '134'                | '9'                   | '2931'               | '1451'            | '4777'         | '6167'      | '38'              | '64'           | '0'               | '6'            | '36'                     | '64'                  | '3736'            | '3039'              | '1387'          | '379'           | '2578'          | '2431'          | '11778'    | '10249'            | '1452'             | '77'               | '1455311' | '5476'        | '14583'           | '7109'    | '1734'        | '25'              | '0.5482569551670923' | '0.19672005996335573' | '0.14433535810142675'  | '0.007049896671731254' | '0.0036552741080373256' | '0.0006030732767588598'  | '0.003994561620925727'   | '0.01510592227525433'  | '0.017959695181206593' | '0.33477989168171085' | '0.12427093459241773' | '0.4044403555061797'  | '0.4712887099014026'  | '0.16037982973149967' | '0.42082696847660045' | '0.6688726608854404' | '0.4364948830409357'  | '0.37254901960784315' | '0.0'            | '0.36'                  | '0.5514391143911439' | '0.20472324723247232' | '0.05594095940959409'  | '0.3805166051660517'  | '0.3588191881918819'  | '0.1779093181502569'  | '0.12328069281711666' | '0.006537612497877399'  | '0.546043996863263'  | '0.562102237733525'  | '0.30466301759077424' | '0.002667352046195581' | '0.17799219872716074' | '0.0005222913968161117' | '27.9065141456' | '32.7308663735' | '44.4094641757' | '23.8381941253' | '10.7421547728' | '12.5499060049' | '11.189386163'  | '8.2676847867'  | '-0.108173984512' | '-336936'       |
+------------+---------------------+-------------+----------------+-------------+-------------------+----------------------+-----------------------+-----------------------------+-------------------------------+----------------+----------------------+----------------------+----------------------+-------------------------+-------------------------+---------------+------------------+----------------+-----------------+------------+--------------+-------------------------+-----------------------+-----------------+--------------------------------+------------------------+-----------------+---------------------------------+-----------------------------------+---------------------------+--------------------+--------------+-------------------+-------------+------------------+------------+-----------------+-------------+---------+--------------+-------------+------------------+------------------+-------------------+-----------------------+----------------------+--------------------------+----------------------+--------------------------+-------------+-----------------+---------+---------------+-------------------+-----------+-------------+-----------------+---------+-------------+-----------------+---------+----------------+--------------------+------------+-------------------+--------------------+----------------+--------------------+--------------------+---------------------+-----------------+---------------------+---------------+-------------------------+----------------------+-----------------------+----------------------+-------------------+----------------+-------------+-------------------+----------------+-------------------+----------------+--------------------------+-----------------------+-------------------+---------------------+-----------------+-----------------+-----------------+-----------------+------------+--------------------+--------------------+--------------------+-----------+---------------+-------------------+-----------+---------------+-------------------+----------------------+-----------------------+------------------------+------------------------+-------------------------+--------------------------+--------------------------+------------------------+------------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+----------------------+-----------------------+-----------------------+------------------+-------------------------+----------------------+-----------------------+------------------------+-----------------------+-----------------------+-----------------------+-----------------------+-------------------------+----------------------+----------------------+-----------------------+------------------------+-----------------------+-------------------------+-----------------+-----------------+-----------------+-----------------+-----------------+-----------------+-----------------+-----------------+-------------------+-----------------+
| 'QV0108-C' | '1135-PF-SN-CONWAY' | 'PK24.14'   | 'ERR1081189'   | 'SC'        | '0.9007'          | '0.0134'             | '0.0143'              | '0.0'                       | '0.0717'                      | '0.0'          | '23169213'           | '23114072'           | '22965277'           | '0.993'                 | '0.9842'                | '145.17'      | '220.4'          | '70.9'         | '99'            | '35103138' | '34286075'   | '34124051'              | '32256043'            | '0'             | '858190'                       | '480722'               | '0.9767'        | '0.9408'                        | '0.0505'                          | '0.014'                   | '0.0'              | '6051696'    | '3114760'         | '455655'    | '74649'          | '5596041'  | '3040111'       | '5367751'   | '83080' | '20107'      | '145210'    | '106050'         | '126157'         | '163'             | '7776'                | '5066'               | '51587'                  | '14878'              | '46687'                  | '2373'      | '32091'         | '34464' | '17734'       | '17734'           | '35468'   | '4169'      | '8254'          | '12423' | '11399'     | '51791'         | '63190' | '2637'         | '26479'            | '29116'    | '1040573'         | '1036209'          | '68'           | '4296'             | '83085'            | '79874'             | '5'             | '3206'              | '303'         | '177'                   | '97'                 | '13'                  | '2859'               | '1477'            | '6425'         | '7675'      | '32'              | '57'           | '0'               | '4'            | '29'                     | '55'                  | '4030'            | '3354'              | '1583'          | '425'           | '2698'          | '2678'          | '20826'    | '18128'            | '2605'             | '93'               | '2768213' | '12003'       | '91488'           | '2428007' | '4445'        | '60844'           | '0.5432610304320501' | '0.0752937688872673'  | '0.02396621248507108'  | '0.014846210025980867' | '0.006613903242348717'  | '6.534861081346528e-05'  | '6.017933441656135e-05'  | '0.025948701948395304' | '0.03488359471085102'  | '0.2731834143170811'  | '0.06292952432286754' | '0.4490674318507891'  | '0.48800304382634335' | '0.16429714467088993' | '0.23079179118083024' | '0.6593634686346863' | '0.45567375886524825' | '0.3595505617977528'  | '0.0'            | '0.34523809523809523'   | '0.545774647887324'  | '0.21438244853737812' | '0.057556879739978334' | '0.36538461538461536' | '0.3626760563380282'  | '0.1436939686263941'  | '0.1250840295784116'  | '0.0044655718813022185' | '0.9105631340434609' | '0.5969562838812353' | '0.8626874115983026'  | '0.7986573516559099'   | '0.22106728999850797' | '0.5737293729372938'    | '84.7123845818' | '87.4236621443' | '48.2705525439' | '76.7528618576' | '80.6104438223' | '83.0739582711' | '45.4706818521' | '65.8604809052' | '-0.267562187777' | '-833392'       |

# Read in Lucas spreadsheets

## First sanity check source_code to ox_code mapping

In [11]:
tbl_lucas_oxcode = etl.fromxlsx(lucas_oxcode_fn).rename({'Study_id': 'LucasSrcCode', 'Oxford code': 'Sample'})
print(len(tbl_lucas_oxcode.data()))
tbl_lucas_oxcode.tail()

666

+--------------+------------+
| LucasSrcCode | Sample     |
+==============+============+
| 'PDN512'     | 'PF0999-C' |
+--------------+------------+
| 'PDN515'     | 'PF1001-C' |
+--------------+------------+
| 'PDN522'     | 'PF1004-C' |
+--------------+------------+
| 'PDN524'     | 'PF1005-C' |
+--------------+------------+
| 'PDN526'     | 'PF1006-C' |
+--------------+------------+

In [12]:
print(len(tbl_lucas_oxcode.distinct('LucasSrcCode').data()))
print(len(tbl_lucas_oxcode.distinct('Sample').data()))
print(len(tbl_lucas_oxcode.distinct('LucasSrcCode').distinct('Sample').data()))

606
606
606

In [13]:
tbl_lucas_join = (
    tbl_lucas_oxcode
    .distinct('LucasSrcCode')
    .join(tbl_sample_6_0, lkey='Sample', rkey='sample')
    .cut(['Sample', 'LucasSrcCode', 'source_code'])
)
print(len(tbl_lucas_join.data()))

587

In [14]:
tbl_lucas_join.select(lambda rec: rec['LucasSrcCode'] != rec['source_code']).displayall()

Sample,LucasSrcCode,source_code
PF0095-C,PFD040,PFD40
PF0097-C,PFD042,PFD42
PF0098-C,PFD043,PFD43
PF0100-C,PFD045,PFD45
PF0101-C,PFD046,PFD46
PF0102-C,PFD047,PFD47
PF0103-C,PFD048,PFD48
PF0104-C,PFD049,PFD49
PF0489-C,PFD1398,PDF1398

## Then create table of Lucas samples

In [15]:
tbl_lucas = (
    etl.fromxls(lucas_0_fn).rename({'studyid': 'OxfordSrcCode', 'date': 'Lucas_Date'}).cut(['OxfordSrcCode', 'Lucas_Date'])
    .cat(etl.fromxls(lucas_1_fn).rename({'SourceCode': 'OxfordSrcCode', 'date': 'Lucas_Date'})).cut(['OxfordSrcCode', 'Lucas_Date'])
    .cat(etl.fromxls(lucas_2_fn).rename({'studyid': 'OxfordSrcCode', 'date': 'Lucas_Date'})).cut(['OxfordSrcCode', 'Lucas_Date'])
    .cat(etl.fromxls(lucas_3_fn).rename({'studyid': 'OxfordSrcCode', 'date': 'Lucas_Date'})).cut(['OxfordSrcCode', 'Lucas_Date'])
    .cat(etl.fromxls(lucas_4_fn).rename({'studyid': 'OxfordSrcCode', 'date': 'Lucas_Date'})).cut(['OxfordSrcCode', 'Lucas_Date'])
    .cat(etl.fromxls(lucas_5_fn).rename({'SourceCode': 'OxfordSrcCode', 'date': 'Lucas_Date'})).cut(['OxfordSrcCode', 'Lucas_Date'])
    .addfield('Lucas_Year', lambda rec: str(rec['Lucas_Date'])[0:4])
    .convert('OxfordSrcCode', lambda x: x.replace('PFD04', 'PFD4')) # different format in Oxford DB versus Cristina spreadsheet
    .convert('OxfordSrcCode', lambda x: x.replace('PFD1398', 'PDF1398')) # looks like Oxford DB has this one wrong
)
print(len(tbl_lucas.data()))
tbl_lucas.tail()

779

+---------------+---------------------------------------+------------+
| OxfordSrcCode | Lucas_Date                            | Lucas_Year |
+===============+=======================================+============+
| 'PFD1432'     | datetime.datetime(2010, 11, 20, 0, 0) | '2010'     |
+---------------+---------------------------------------+------------+
| 'PFD1435'     | datetime.datetime(2009, 11, 10, 0, 0) | '2009'     |
+---------------+---------------------------------------+------------+
| 'PFD1439'     | datetime.datetime(2009, 8, 12, 0, 0)  | '2009'     |
+---------------+---------------------------------------+------------+
| 'PFD1441'     | datetime.datetime(2009, 5, 7, 0, 0)   | '2009'     |
+---------------+---------------------------------------+------------+
| 'PFD1452'     | datetime.datetime(2010, 4, 17, 0, 0)  | '2010'     |
+---------------+---------------------------------------+------------+

In [16]:
tbl_lucas.select(lambda rec: 'PFD04' in rec['OxfordSrcCode']).displayall()

In [17]:
tbl_lucas.select(lambda rec: 'PFD4' in rec['OxfordSrcCode']).displayall()

OxfordSrcCode,Lucas_Date,Lucas_Year
PFD40,2009-10-05 00:00:00,2009
PFD41,2009-10-07 00:00:00,2009
PFD42,2009-10-07 00:00:00,2009
PFD43,2009-10-12 00:00:00,2009
PFD44,2009-10-13 00:00:00,2009
PFD45,2009-10-16 00:00:00,2009
PFD46,2009-10-20 00:00:00,2009
PFD47,2009-10-21 00:00:00,2009
PFD48,2009-10-23 00:00:00,2009
PFD49,2009-10-26 00:00:00,2009
PFD427,2010-08-25 00:00:00,2010
PFD404,2010-07-08 00:00:00,2010
PFD404,2010-07-08 00:00:00,2010
PFD446,2011-09-06 00:00:00,2011
PFD427,2011-01-06 00:00:00,2011
PFD450,2011-04-07 00:00:00,2011

In [18]:
tbl_lucas.selecteq('OxfordSrcCode', 'PFD040')

+---------------+------------+------------+
| OxfordSrcCode | Lucas_Date | Lucas_Year |
+===============+============+============+

In [19]:
tbl_lucas.selecteq('OxfordSrcCode', 'PFD40')

+---------------+--------------------------------------+------------+
| OxfordSrcCode | Lucas_Date                           | Lucas_Year |
+===============+======================================+============+
| 'PFD40'       | datetime.datetime(2009, 10, 5, 0, 0) | '2009'     |
+---------------+--------------------------------------+------------+

# Read in sample information spreadsheets
Queries were used to identify studies with many missing dates (see 20161215_samples_panoptes_metadata.ipynb). I then manually searched for source code in sample information spreadsheets

In [20]:
tbl_sis = collections.OrderedDict()

In [21]:
sis = '1093_Rob'
tbl_sis['1093_Rob'] = (
    etl
    .fromxlsx(sample_information_sheets['1093_Rob'][0], sample_information_sheets['1093_Rob'][1], row_offset=12)
    .rename('Sample ID*', 'OxfordSrcCode')
    .rename('Date/Month/Year of Collection*', 'sis_Date_%s' % sis)
    .rename('Province/Region/Town of Origin*', 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1093_Rob', lambda rec: str(rec['sis_Date_%s' % '1093_Rob'])[0:4])
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1093_Rob', 'sis_Year_%s' % '1093_Rob', 'sis_Location_%s' % sis])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

243
243

sis_Year_1093_Rob,count,frequency
2013,242,0.9958847736625515
None,1,0.00411522633744856

In [22]:
sis = '1094_Rob'
tbl_sis['1094_Rob'] = (
    etl
    .fromxlsx(sample_information_sheets['1094_Rob'][0], sample_information_sheets['1094_Rob'][1], row_offset=12)
    .rename('Sample ID*', 'OxfordSrcCode')
    .rename('Date/Month/Year of Collection*', 'sis_Date_%s' % sis)
    .rename('Province/Region/Town of Origin*', 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1094_Rob', lambda rec: (
            str(rec['sis_Date_%s' % '1094_Rob'])[0:4] if str(rec['sis_Date_%s' % '1094_Rob'])[0:3] == '201'
            else str(rec['sis_Date_%s' % '1094_Rob'])[-4:] if str(rec['sis_Date_%s' % '1094_Rob'])[-4:-1] == '201'
            else 'N/A'))
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1094_Rob', 'sis_Year_%s' % '1094_Rob', 'sis_Location_%s' % sis])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

184
184

sis_Year_1094_Rob,count,frequency
2013,184,1.0

In [23]:
sis = '1095_Rob'
tbl_sis['1095_Rob'] = (
    etl
    .fromxlsx(sample_information_sheets['1095_Rob'][0], sample_information_sheets['1095_Rob'][1], row_offset=13)
    .rename('Sample ID*', 'OxfordSrcCode')
    .rename('Date/Month/Year of Collection*', 'sis_Date_%s' % sis)
    .rename('Province/Region/Town of Origin*', 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1095_Rob', lambda rec: str(rec['sis_Date_%s' % '1095_Rob'])[0:4])
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1095_Rob', 'sis_Year_%s' % '1095_Rob', 'sis_Location_%s' % sis])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

447
447

sis_Year_1095_Rob,count,frequency
2013,415,0.9284116331096197
2011,32,0.07158836689038031

In [24]:
sis = '1096_Rob'
tbl_sis['1096_Rob'] = (
    etl
    .fromxlsx(sample_information_sheets['1096_Rob'][0], sample_information_sheets['1096_Rob'][1], row_offset=14)
    .rename('Sample ID*', 'OxfordSrcCode')
    .rename('Date of Collection (mm/yy)*', 'sis_Date_%s' % sis)
    .rename('Province/Region/Town of Origin*', 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1096_Rob', lambda rec: str(rec['sis_Date_%s' % '1096_Rob'])[0:4])
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1096_Rob', 'sis_Year_%s' % '1096_Rob', 'sis_Location_%s' % sis])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

100
100

sis_Year_1096_Rob,count,frequency
2014,98,0.98
2013,2,0.02

In [25]:
sis = '1097_Rob'
tbl_sis['1097_Rob'] = (
    etl
    .fromxlsx(sample_information_sheets['1097_Rob'][0], sample_information_sheets['1097_Rob'][1], row_offset=17)
    .rename('Sample ID*', 'OxfordSrcCode')
    .rename('Date of Collection (mm/yy)*', 'sis_Date_%s' % sis)
    .rename('Province/Region/Town of Origin*', 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1097_Rob', lambda rec: str(rec['sis_Date_%s' % '1097_Rob'])[0:4])
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1097_Rob', 'sis_Year_%s' % '1097_Rob', 'sis_Location_%s' % sis])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

144
144

sis_Year_1097_Rob,count,frequency
2013,141,0.9791666666666666
2014,3,0.020833333333333332

In [26]:
sis = '1098_Rob'
tbl_sis['1098_Rob'] = (
    etl
    .fromxlsx(sample_information_sheets['1098_Rob'][0], sample_information_sheets['1098_Rob'][1], row_offset=14)
    .rename('Sample ID*', 'OxfordSrcCode')
    .rename('Date of Collection (mm/yy)*', 'sis_Date_%s' % sis)
    .rename('Province/Region/Town of Origin*', 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1098_Rob', lambda rec: (
            str(rec['sis_Date_%s' % '1098_Rob'])[0:4] if str(rec['sis_Date_%s' % '1098_Rob'])[0:3] == '201'
            else '20' + str(rec['sis_Date_%s' % '1098_Rob'])[-2:]))
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1098_Rob', 'sis_Year_%s' % '1098_Rob', 'sis_Location_%s' % sis])
    .distinct('OxfordSrcCode')
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

203
203

sis_Year_1098_Rob,count,frequency
2013,203,1.0

In [27]:
tbl_sis[sis].duplicates('OxfordSrcCode')

+---------------+-------------------+-------------------+-----------------------+
| OxfordSrcCode | sis_Date_1098_Rob | sis_Year_1098_Rob | sis_Location_1098_Rob |
+===============+===================+===================+=======================+

In [28]:
sis = '1100_Rob'
tbl_sis['1100_Rob'] = (
    etl
    .fromxlsx(sample_information_sheets['1100_Rob'][0], sample_information_sheets['1100_Rob'][1], row_offset=13)
    .rename('Sample ID*', 'OxfordSrcCode')
    .rename('Date/Month/Year of Collection*', 'sis_Date_%s' % sis)
    .rename('Province/Region/Town of Origin*', 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1100_Rob', lambda rec: str(rec['sis_Date_%s' % '1100_Rob'])[0:4])
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1100_Rob', 'sis_Year_%s' % '1100_Rob', 'sis_Location_%s' % sis])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

121
121

sis_Year_1100_Rob,count,frequency
2013,97,0.8016528925619835
2014,24,0.19834710743801653

In [29]:
sis = '1102_Rob'
tbl_sis['1102_Rob'] = (
    etl
    .fromxlsx(sample_information_sheets['1102_Rob'][0], sample_information_sheets['1102_Rob'][1], row_offset=14)
    .rename('Sample ID*', 'OxfordSrcCode')
    .rename('Date of Collection (mm/yy)*', 'sis_Date_%s' % sis)
    .rename('Province/Region/Town of Origin*', 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1102_Rob', lambda rec: str(rec['sis_Date_%s' % '1102_Rob'])[0:4])
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1102_Rob', 'sis_Year_%s' % '1102_Rob', 'sis_Location_%s' % sis])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

136
136

sis_Year_1102_Rob,count,frequency
2012,112,0.8235294117647058
2013,24,0.17647058823529413

In [30]:
sis = '1103_Rob'
tbl_sis['1103_Rob'] = (
    etl
    .fromxlsx(sample_information_sheets['1103_Rob'][0], sample_information_sheets['1103_Rob'][1], row_offset=13)
    .rename('7. Study Sample Id', 'OxfordSrcCode')
    .rename('9. Collection date', 'sis_Date_%s' % sis)
    .rename(3, 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1103_Rob', lambda rec: (
            str(rec['sis_Date_%s' % '1103_Rob'])[0:4] if str(rec['sis_Date_%s' % '1103_Rob'])[0:3] == '201'
            else '20' + str(rec['sis_Date_%s' % '1103_Rob'])[-2:]))
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .distinct('OxfordSrcCode')
#     .cut(['OxfordSrcCode', 'sis_Date_%s' % '1103_Rob', 'sis_Year_%s' % '1103_Rob', 'sis_Location_%s' % sis])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

165
165

sis_Year_1103_Rob,count,frequency
2014,128,0.7757575757575758
2015,37,0.22424242424242424

In [31]:
tbl_sis[sis].duplicates('OxfordSrcCode').displayall()

In [32]:
sis = '1107_Rob'
tbl_sis['1107_Rob'] = (
    etl
    .fromxlsx(sample_information_sheets['1107_Rob'][0], sample_information_sheets['1107_Rob'][1], row_offset=15)
    .rename('Sample ID*', 'OxfordSrcCode')
    .rename('Date of Collection (dd/mm/yy)*', 'sis_Date_%s' % sis)
    .rename(' Site (local clinic etc) Collection*', 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1107_Rob', lambda rec: str(rec['sis_Date_%s' % '1107_Rob'])[-4:])
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1107_Rob', 'sis_Year_%s' % '1107_Rob', 'sis_Location_%s' % sis])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

240
240

sis_Year_1107_Rob,count,frequency
2013,97,0.4041666666666667
None,78,0.325
2012,65,0.2708333333333333

In [33]:
# Note have removed spaces in source codes
sis = '1136_Rob'
tbl_sis['1136_Rob'] = (
    etl
    .fromxlsx(sample_information_sheets['1136_Rob'][0], sample_information_sheets['1136_Rob'][1], row_offset=13)
    .rename('7. Study Sample Id', 'OxfordSrcCode')
    .convert('OxfordSrcCode', lambda v: v.replace(' ', ''))
    .rename('9. Collection date', 'sis_Date_%s' % sis)
    .rename(3, 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1136_Rob', lambda rec: str(rec['sis_Date_%s' % '1136_Rob'])[0:4])
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1136_Rob', 'sis_Year_%s' % '1136_Rob', 'sis_Location_%s' % sis])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

95
95

sis_Year_1136_Rob,count,frequency
2014,93,0.9789473684210527
2015,2,0.021052631578947368

In [34]:
# Note have removed spaces in source codes
sis = '1137_Rob'
tbl_sis['1137_Rob'] = (
    etl
    .fromxlsx(sample_information_sheets['1137_Rob'][0], sample_information_sheets['1137_Rob'][1], row_offset=13)
    .rename('7. Study Sample Id', 'OxfordSrcCode')
    .convert('OxfordSrcCode', lambda v: v.replace(' ', ''))
    .rename('9. Collection date', 'sis_Date_%s' % sis)
    .rename(3, 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1137_Rob', lambda rec: (
            str(rec['sis_Date_%s' % '1137_Rob'])[0:4] if str(rec['sis_Date_%s' % '1137_Rob'])[0:3] == '201'
            else str(rec['sis_Date_%s' % '1137_Rob'])[-4:] if str(rec['sis_Date_%s' % '1137_Rob'])[-4:-1] == '201'
            else 'N/A'))
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1137_Rob', 'sis_Year_%s' % '1137_Rob', 'sis_Location_%s' % sis])
    .distinct('OxfordSrcCode')
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

123
123

sis_Year_1137_Rob,count,frequency
2013,63,0.5121951219512195
2014,40,0.3252032520325203
N/A,20,0.16260162601626016

In [35]:
tbl_sis[sis].duplicates('OxfordSrcCode').displayall()

In [36]:
tbl_sis['1137_Rob'].selecteq('OxfordSrcCode', 'E0060808')

+---------------+-------------------+-------------------+-----------------------+
| OxfordSrcCode | sis_Date_1137_Rob | sis_Year_1137_Rob | sis_Location_1137_Rob |
+===============+===================+===================+=======================+
| 'E0060808'    | 'not indicated'   | 'N/A'             | 'Dongoroba'           |
+---------------+-------------------+-------------------+-----------------------+

In [37]:
sis = '1044_Oct2012_NIH'
tbl_sis['1044_Oct2012_NIH'] = (
    etl
    .fromxlsx(sample_information_sheets['1044_Oct2012_NIH'][0], sample_information_sheets['1044_Oct2012_NIH'][1], row_offset=1)
    .rename('Code', 'OxfordSrcCode')
    .rename('Collection date', 'sis_Date_%s' % '1044_Oct2012_NIH')
    .rename('Origine', 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1044_Oct2012_NIH', lambda rec: str(rec['sis_Date_%s' % '1044_Oct2012_NIH'])[0:4])
    .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
    .cut(['OxfordSrcCode', 'sis_Date_%s' % sis, 'sis_Year_%s' % '1044_Oct2012_NIH', 'sis_Location_%s' % sis])
    .distinct('OxfordSrcCode')
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

31
31

sis_Year_1044_Oct2012_NIH,count,frequency
2012,31,1.0

In [38]:
tbl_sis[sis].valuecounts('sis_Location_%s' % sis).displayall()

sis_Location_1044_Oct2012_NIH,count,frequency
Pursat,23,0.7419354838709677
Ratanakiri,8,0.25806451612903225

In [39]:
sis = '1044_Dec2012'
tbl_sis['1044_Dec2012'] = (
    etl
    .fromxlsx(sample_information_sheets['1044_Dec2012'][0], sample_information_sheets['1044_Dec2012'][1], row_offset=1)
    .rename('Code', 'OxfordSrcCode')
    .rename('Collection date', 'sis_Date_%s' % '1044_Dec2012')
    .addfield('sis_Year_%s' % '1044_Dec2012', lambda rec: str(rec['sis_Date_%s' % '1044_Dec2012'])[0:4])
    .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
    .cut(['OxfordSrcCode', 'sis_Date_%s' % sis, 'sis_Year_%s' % '1044_Dec2012'])
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

67
67

sis_Year_1044_Dec2012,count,frequency
2012,67,1.0

In [40]:
sis = '1044_Oct2012_TRAC'
tbl_sis['1044_Oct2012_TRAC'] = (
    etl
    .fromxlsx(sample_information_sheets['1044_Oct2012_TRAC'][0], sample_information_sheets['1044_Oct2012_TRAC'][1], row_offset=1)
    .rename('Code', 'OxfordSrcCode')
    .rename('Collection date', 'sis_Date_%s' % '1044_Oct2012_TRAC')
    .rename('Origine', 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1044_Oct2012_TRAC', lambda rec: str(rec['sis_Date_%s' % '1044_Oct2012_TRAC'])[0:4])
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % sis, 'sis_Year_%s' % '1044_Oct2012_TRAC', 'sis_Location_%s' % sis])
    .distinct('OxfordSrcCode')
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

11
11

sis_Year_1044_Oct2012_TRAC,count,frequency
2012,11,1.0

In [41]:
tbl_sis[sis].valuecounts('sis_Location_%s' % sis).displayall()

sis_Location_1044_Oct2012_TRAC,count,frequency
Preah Vihear,11,1.0

In [42]:
sis = '1044_Jan2014'
tbl_sis['1044_Jan2014'] = (
    etl
    .fromxlsx(sample_information_sheets['1044_Jan2014'][0], sample_information_sheets['1044_Jan2014'][1], row_offset=12)
    .rename('Sample ID*', 'OxfordSrcCode')
    .rename('Date/Month/Year of Collection*', 'sis_Date_%s' % sis)
    .rename('Province/Region/Town of Origin*', 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1044_Jan2014', lambda rec: str(rec['sis_Date_%s' % '1044_Jan2014'])[0:4])
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1044_Jan2014', 'sis_Year_%s' % '1044_Jan2014', 'sis_Location_%s' % sis])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

68
68

sis_Year_1044_Jan2014,count,frequency
2012,46,0.6764705882352942
2013,22,0.3235294117647059

In [43]:
tbl_sis[sis].valuecounts('sis_Location_%s' % sis).displayall()

sis_Location_1044_Jan2014,count,frequency
Pursat,52,0.7647058823529411
Preah Vihear,16,0.23529411764705882

In [44]:
sis = '1101_Apr2013'
tbl_sis['1101_Apr2013'] = (
    etl
    .fromxlsx(sample_information_sheets['1101_Apr2013'][0], sample_information_sheets['1101_Apr2013'][1], row_offset=12)
    .rename('Sample ID*', 'OxfordSrcCode')
    .rename('Date/Month/Year of Collection*', 'sis_Date_%s' % sis)
    .addfield('sis_Year_%s' % '1101_Apr2013', lambda rec: str(rec['sis_Date_%s' % '1101_Apr2013'])[0:4])
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1101_Apr2013', 'sis_Year_%s' % '1101_Apr2013'])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

175
175

sis_Year_1101_Apr2013,count,frequency
2012,175,1.0

In [45]:
# Note have converted spaces to underscores in source codes
sis = '1052_Sep2015'
tbl_sis['1052_Sep2015'] = (
    etl
    .fromxlsx(sample_information_sheets['1052_Sep2015'][0], sample_information_sheets['1052_Sep2015'][1], row_offset=13)
    .rename('7. Study Sample Id', 'OxfordSrcCode')
    .convert('OxfordSrcCode', lambda v: v.replace(' ', '_'))
    .rename('9. Collection date', 'sis_Date_%s' % sis)
    .addfield('sis_Year_%s' % '1052_Sep2015', lambda rec: str(rec['sis_Date_%s' % '1052_Sep2015'])[0:4])
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1052_Sep2015', 'sis_Year_%s' % '1052_Sep2015'])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

131
131

sis_Year_1052_Sep2015,count,frequency
2013,83,0.6335877862595419
2014,45,0.3435114503816794
2012,3,0.022900763358778626

In [50]:
sis = '1138_Mar2015'
tbl_sis['1138_Mar2015'] = (
    etl
    .fromxlsx(sample_information_sheets['1138_Mar2015'][0], sample_information_sheets['1138_Mar2015'][1], row_offset=13)
    .rename('7. Study Sample Id', 'OxfordSrcCode')
    .rename('9. Collection date', 'sis_Date_%s' % sis)
    .addfield('sis_Year_%s' % '1138_Mar2015', lambda rec: (
            str(rec['sis_Date_%s' % '1138_Mar2015'])[0:4] if str(rec['sis_Date_%s' % '1138_Mar2015'])[0:2] == '20'
            else str(rec['sis_Date_%s' % '1138_Mar2015'])[-4:] if str(rec['sis_Date_%s' % '1138_Mar2015'])[-4:-2] == '20'
            else 'N/A'))
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1138_Mar2015', 'sis_Year_%s' % '1138_Mar2015'])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

217
217

sis_Year_1138_Mar2015,count,frequency
2014,148,0.6820276497695853
2015,69,0.31797235023041476

In [51]:
# Note have converted hyphens to underscores in source codes
sis = '1155_May2015'
tbl_sis['1155_May2015'] = (
    etl
    .fromxlsx(sample_information_sheets['1155_May2015'][0], sample_information_sheets['1155_May2015'][1], row_offset=13)
    .rename('7. Study Sample Id', 'OxfordSrcCode')
    .convert('OxfordSrcCode', lambda v: v.replace('-', '_'))
    .rename('9. Collection date', 'sis_Date_%s' % sis)
    .addfield('sis_Year_%s' % '1155_May2015', lambda rec: str(rec['sis_Date_%s' % '1155_May2015'])[0:4])
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1155_May2015', 'sis_Year_%s' % '1155_May2015'])
    .distinct('OxfordSrcCode')
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

156
156

sis_Year_1155_May2015,count,frequency
2014,59,0.3782051282051282
2012,42,0.2692307692307692
2013,33,0.21153846153846154
2011,20,0.1282051282051282
2008,1,0.00641025641025641
2010,1,0.00641025641025641

In [52]:
sis = '1134_May2015'
tbl_sis['1134_May2015'] = (
    etl
    .fromxlsx(sample_information_sheets['1134_May2015'][0], sample_information_sheets['1134_May2015'][1], row_offset=12)
    .rename('Sample ID*', 'OxfordSrcCode')
    .rename('Date/Month/Year of Collection*', 'sis_Date_%s' % sis)
    .addfield('sis_Year_%s' % '1134_May2015', lambda rec: str(rec['sis_Date_%s' % '1134_May2015'])[0:4])
    .rename('Province/Region/Town of Origin*', 'sis_Location_%s' % sis)
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1134_May2015', 'sis_Year_%s' % '1134_May2015', 'sis_Location_%s' % sis])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

49
49

sis_Year_1134_May2015,count,frequency
2014,49,1.0

In [53]:
tbl_sis[sis].valuecounts('sis_Location_%s' % sis).displayall()

sis_Location_1134_May2015,count,frequency
Nioro du Sahel,49,1.0

In [54]:
# Note have converted hyphens to underscores in source codes
sis = '1062_Sep2013'
tbl_sis['1062_Sep2013'] = (
    etl
    .fromxlsx(sample_information_sheets['1062_Sep2013'][0], sample_information_sheets['1062_Sep2013'][1], row_offset=0)
    .rename('Source Code', 'OxfordSrcCode')
    .convert('OxfordSrcCode', lambda v: v.replace('-', '_'))
    .rename('Date of Collection', 'sis_Date_%s' % sis)
    .addfield('sis_Year_%s' % '1062_Sep2013', lambda rec: (
            str(rec['sis_Date_%s' % '1062_Sep2013'])[0:4] if str(rec['sis_Date_%s' % '1062_Sep2013'])[0:3] == '201'
            else '2012' if str(rec['sis_Date_%s' % '1062_Sep2013'])[-2:] == '12'
            else 'N/A'))
#     .addfield('sis_Year_%s' % '1062_Sep2013', lambda rec: str(rec['sis_Date_%s' % '1062_Sep2013'])[0:4])
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1062_Sep2013', 'sis_Year_%s' % '1062_Sep2013'])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

61
61

/Users/rpearson/miniconda3/envs/biipy/lib/python3.5/site-packages/openpyxl/workbook/names/named_range.py:125: UserWarning: Discarded range with reserved name
  warnings.warn("Discarded range with reserved name")

sis_Year_1062_Sep2013,count,frequency
2012,24,0.39344262295081966
2013,22,0.36065573770491804
N/A,15,0.2459016393442623

In [55]:
source_code_changes_1021 = {
    'XUA 001': 'PfXUA001',
    'XUC 017': 'PfXUC017',
    'XUC 007': 'pfXUC007',
    'XUA 034': 'PfXUA034',
    'XUA 035': 'PfXUA035',
    'XUC 022': 'PfXUC022',
    'XPA 147': 'pfXPA147',
    'XPM 016': 'pfXPM016',
    'XPM 017': 'pfXPM017',
    'XUA 008': 'pfXUA008',
    'XUA 010': 'pfXUA010',
    'XUA 013': 'pfXUA013',
    'XUA 017': 'pfXUA017',
    'XUA 020': 'pfXUA020',
    'XUC 006': 'pfXUC006',
    'XUC 035': 'ukXUC035',
}

# Note have extensively modified source codes
sis = '1021_Apr2010'
tbl_sis['1021_Apr2010'] = (
    etl
    .fromxlsx(sample_information_sheets['1021_Apr2010'][0], sample_information_sheets['1021_Apr2010'][1], row_offset=0)
    .rename(0, 'OxfordSrcCode')
    .convert('OxfordSrcCode', lambda v, r: source_code_changes_1021[r['OxfordSrcCode']], where=lambda r: r['OxfordSrcCode'] in source_code_changes_1021, pass_row=True)
    .convert('OxfordSrcCode', lambda v, r: r['Old Oxford code'].replace('PF', 'Pf'), where=lambda r: not r['OxfordSrcCode'] in list(source_code_changes_1021.values()) and not r['Old Oxford code'] in ['-', '', None, 'None'], pass_row=True)
#     .convert('OxfordSrcCode', lambda v: "Pf%s" % v.replace(' ', ''), where=lambda r: not r['SANGER code'] in ['', None, 'None'])
    .convert('OxfordSrcCode', lambda v: "pf%s" % v.replace(' ', ''), where=lambda r: not r['OxfordSrcCode'] in list(source_code_changes_1021.values()) and r['Old Oxford code'] in ['-', '', None, 'None'])
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
#     .rename('Date collected', 'sis_Date_%s' % sis)
    .addfield('sis_Date_%s' % sis, lambda rec: '2007-11-15 00:00:00' if str(rec['Date collected'])[1:4] == 'Nov' else rec['Date collected'])
    .addfield('sis_Year_%s' % '1021_Apr2010', lambda rec: str(rec['sis_Date_%s' % '1021_Apr2010'])[0:4])
#     .addfield('sis_Year_%s' % '1062_Sep2013', lambda rec: str(rec['sis_Date_%s' % '1062_Sep2013'])[0:4])
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1021_Apr2010', 'sis_Year_%s' % '1021_Apr2010'])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

93
93

sis_Year_1021_Apr2010,count,frequency
2008,56,0.6021505376344086
2009,32,0.34408602150537637
2010,3,0.03225806451612903
2007,2,0.021505376344086023

In [56]:
# Note have removed spaces in source codes
# Also, this spreadsheet (Chanaki samples 1044.xlsx) has multiple records for source codes, in some cases with
# inconsistent dates. Have decided to go with it for now and just select the first date for each sample
sis = '1044_Jul2015'
tbl_sis['1044_Jul2015'] = (
    etl
    .fromxlsx(sample_information_sheets['1044_Jul2015'][0], sample_information_sheets['1044_Jul2015'][1], row_offset=13)
    .rename('7. Study Sample Id', 'OxfordSrcCode')
    .convert('OxfordSrcCode', lambda v: v.replace(' ', ''))
    .rename('9. Collection date', 'sis_Date_%s' % sis)
    .rename(3, 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1044_Jul2015', lambda rec: str(rec['sis_Date_%s' % '1044_Jul2015'])[0:4])
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1044_Jul2015', 'sis_Year_%s' % '1044_Jul2015', 'sis_Location_%s' % sis])
    .distinct('OxfordSrcCode')
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

40
40

sis_Year_1044_Jul2015,count,frequency
2015,30,0.75
2014,10,0.25

In [57]:
tbl_sis[sis].valuecounts('sis_Location_%s' % sis).displayall()

sis_Location_1044_Jul2015,count,frequency
Pursat,40,1.0

In [58]:
# Note have removed spaces in source codes
sis = '1044_Aug2015'
tbl_sis['1044_Aug2015'] = (
    etl
    .fromxlsx(sample_information_sheets['1044_Aug2015'][0], sample_information_sheets['1044_Aug2015'][1], row_offset=13)
    .rename('7. Study Sample Id', 'OxfordSrcCode')
    .convert('OxfordSrcCode', lambda v: v.replace(' ', ''))
    .rename('9. Collection date', 'sis_Date_%s' % sis)
    .rename(3, 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1044_Aug2015', lambda rec: str(rec['sis_Date_%s' % '1044_Aug2015'])[0:4])
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1044_Aug2015', 'sis_Year_%s' % '1044_Aug2015', 'sis_Location_%s' % sis])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

/Users/rpearson/miniconda3/envs/biipy/lib/python3.5/site-packages/openpyxl/workbook/names/named_range.py:125: UserWarning: Discarded range with reserved name
  warnings.warn("Discarded range with reserved name")

268
268

sis_Year_1044_Aug2015,count,frequency
2014,243,0.9067164179104478
2015,25,0.09328358208955224

In [59]:
sis = '1141_Oct2015'
tbl_sis['1141_Oct2015'] = (
    etl
    .fromxlsx(sample_information_sheets['1141_Oct2015'][0], sample_information_sheets['1141_Oct2015'][1], row_offset=13)
    .rename('7. Study Sample Id', 'OxfordSrcCode')
    .rename('9. Collection date', 'sis_Date_%s' % sis)
    .rename(3, 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1141_Oct2015', lambda rec: str(rec['sis_Date_%s' % '1141_Oct2015'])[-4:])
    .convert('sis_Year_%s' % '1141_Oct2015', lambda v: 'Lab', where=lambda r: r['sis_Year_1141_Oct2015'] == 'trol')
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1141_Oct2015', 'sis_Year_%s' % '1141_Oct2015', 'sis_Location_%s' % sis])
    .distinct('OxfordSrcCode')
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

225
225

sis_Year_1141_Oct2015,count,frequency
2014,213,0.9466666666666667
Lab,12,0.05333333333333334

In [60]:
tbl_sis[sis].valuecounts('sis_Location_%s' % sis).displayall()

sis_Location_1141_Oct2015,count,frequency
Madina Samako,112,0.49777777777777776
Njaiyel,102,0.4533333333333333
None,11,0.04888888888888889

In [61]:
tbl_sis[sis].duplicates('OxfordSrcCode').displayall()

In [62]:
sis = '1125_Nov2013'
tbl_sis['1125_Nov2013'] = (
    etl
    .fromxlsx(sample_information_sheets['1125_Nov2013'][0], sample_information_sheets['1125_Nov2013'][1], row_offset=13)
    .rename('Source Sample ID*', 'OxfordSrcCode')
    .rename('Month/Year of Collection*', 'sis_Date_%s' % sis)
    .addfield('sis_Year_%s' % '1125_Nov2013', lambda rec: str(rec['sis_Date_%s' % '1125_Nov2013'])[0:4])
#     .convert('sis_Year_%s' % '1141_Oct2015', lambda v: 'Lab', where=lambda r: r['sis_Year_1141_Oct2015'] == 'trol')
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1125_Nov2013', 'sis_Year_%s' % '1125_Nov2013'])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

/Users/rpearson/miniconda3/envs/biipy/lib/python3.5/site-packages/openpyxl/workbook/names/named_range.py:125: UserWarning: Discarded range with reserved name
  warnings.warn("Discarded range with reserved name")

803
803

sis_Year_1125_Nov2013,count,frequency
2008,317,0.39476961394769616
2013,115,0.1432129514321295
2003,84,0.10460772104607721
2002,83,0.10336239103362391
2004,58,0.0722291407222914
2001,39,0.048567870485678705
2007,30,0.037359900373599
2012,27,0.033623910336239106
2010,17,0.021170610211706103
2009,16,0.019925280199252802
2011,14,0.017434620174346202
2005,3,0.0037359900373599006

In [63]:
sis = '1098_Oct2016'
tbl_sis['1098_Oct2016'] = (
    etl
    .fromxlsx(sample_information_sheets['1098_Oct2016'][0], sample_information_sheets['1098_Oct2016'][1], row_offset=13)
    .rename('7. Study Sample Id', 'OxfordSrcCode')
    .rename('9. Collection date', 'sis_Date_%s' % sis)
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .addfield('sis_Location_%s' % sis, lambda rec: 'Amhara region' if rec['OxfordSrcCode'].startswith('Sh') else 'Oromia region') # See locations tab
    .addfield('sis_Year_%s' % '1098_Oct2016', lambda rec: (
            str(rec['sis_Date_%s' % '1098_Oct2016'])[0:4] if str(rec['sis_Date_%s' % '1098_Oct2016'])[0:3] == '201'
            else str(rec['sis_Date_%s' % '1098_Oct2016'])[-4:] if str(rec['sis_Date_%s' % '1098_Oct2016'])[-4:-1] == '201'
            else '2013' if str(rec['sis_Date_%s' % '1098_Oct2016'])[-5:-1] == '2013'
            else '2013' if str(rec['sis_Date_%s' % '1098_Oct2016'])[-3:] == '203'
            else 'N/A'))
    .select(lambda rec: rec['OxfordSrcCode'][0:4] != 'Note')
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1098_Oct2016', 'sis_Year_%s' % '1098_Oct2016', 'sis_Location_%s' % '1098_Oct2016'])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

48
48

sis_Year_1098_Oct2016,count,frequency
2015,42,0.875
2014,6,0.125

In [64]:
tbl_sis[sis].valuecounts('sis_Location_%s' % sis).displayall()

sis_Location_1098_Oct2016,count,frequency
Amhara region,42,0.875
Oromia region,6,0.125

In [65]:
sis = '1127_Feb2014'
tbl_sis['1127_Feb2014'] = (
    etl
    .fromxlsx(sample_information_sheets['1127_Feb2014'][0], sample_information_sheets['1127_Feb2014'][1], row_offset=12)
    .rename('Sample ID*', 'OxfordSrcCode')
    .rename('Date/Month/Year of Collection*', 'sis_Date_%s' % sis)
    .rename('Province/Region/Town of Origin*', 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1127_Feb2014', lambda rec: (
            str(rec['sis_Date_%s' % '1127_Feb2014'])[0:4] if str(rec['sis_Date_%s' % '1127_Feb2014'])[0:3] == '201'
            else str(rec['sis_Date_%s' % '1127_Feb2014'])[-4:] if str(rec['sis_Date_%s' % '1127_Feb2014'])[-4:-1] == '201'
            else '2012' if str(rec['sis_Date_%s' % '1127_Feb2014'])[-5:-1] == '2012'
            else 'N/A'))
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .select(lambda rec: rec['OxfordSrcCode'][0:4] != 'Note')
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1127_Feb2014', 'sis_Year_%s' % '1127_Feb2014', 'sis_Location_%s' % '1127_Feb2014'])
    .distinct('OxfordSrcCode')
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

189
189

/Users/rpearson/miniconda3/envs/biipy/lib/python3.5/site-packages/openpyxl/workbook/names/named_range.py:125: UserWarning: Discarded range with reserved name
  warnings.warn("Discarded range with reserved name")

sis_Year_1127_Feb2014,count,frequency
2013,184,0.9735449735449735
2012,4,0.021164021164021163
N/A,1,0.005291005291005291

In [66]:
tbl_sis[sis].valuecounts('sis_Location_%s' % sis).displayall()

sis_Location_1127_Feb2014,count,frequency
Bamako,189,1.0

In [67]:
sis = '1134_Feb2015'
tbl_sis['1134_Feb2015'] = (
    etl
    .fromxlsx(sample_information_sheets['1134_Feb2015'][0], sample_information_sheets['1134_Feb2015'][1], row_offset=0)
    .rename('Sample ID*', 'OxfordSrcCode')
    .rename('Date/Month/Year of Collection*', 'sis_Date_%s' % sis)
    .rename('Province/Region/Town of Origin*', 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1134_Feb2015', lambda rec: (
            str(rec['sis_Date_%s' % '1134_Feb2015'])[0:4] if str(rec['sis_Date_%s' % '1134_Feb2015'])[0:3] == '201'
            else str(rec['sis_Date_%s' % '1134_Feb2015'])[-4:] if str(rec['sis_Date_%s' % '1134_Feb2015'])[-4:-1] == '201'
            else '2012' if str(rec['sis_Date_%s' % '1134_Feb2015'])[-5:-1] == '2012'
            else 'N/A'))
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .select(lambda rec: rec['OxfordSrcCode'][0:4] != 'Note')
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1134_Feb2015', 'sis_Year_%s' % '1134_Feb2015', 'sis_Location_%s' % '1134_Feb2015'])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

130
130

sis_Year_1134_Feb2015,count,frequency
2013,128,0.9846153846153847
2014,2,0.015384615384615385

In [68]:
tbl_sis[sis].valuecounts('sis_Location_%s' % sis).displayall()
# Both 1134 and 1135 in this study
# 1026-PF-GN-CONWAY, 1083-PF-GH-CONWAY, 1135-PF-SN-CONWAY, 1147-PF-MR-CONWAY, 1006-PF-GM-CONWAY, 1134-PF-ML-CONWAY

sis_Location_1134_Feb2015,count,frequency
Pikine,84,0.6461538461538462
Nioro du Sahel,46,0.35384615384615387

In [69]:
sis = '1135_May2015'
tbl_sis['1135_May2015'] = (
    etl
    .fromxlsx(sample_information_sheets['1135_May2015'][0], sample_information_sheets['1135_May2015'][1], row_offset=13)
    .rename('7. Study Sample Id', 'OxfordSrcCode')
    .rename('9. Collection date', 'sis_Date_%s' % sis)
    .rename(3, 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1135_May2015', lambda rec: (
            str(rec['sis_Date_%s' % '1135_May2015'])[0:4] if str(rec['sis_Date_%s' % '1135_May2015'])[0:3] == '201'
            else str(rec['sis_Date_%s' % '1135_May2015'])[-4:] if str(rec['sis_Date_%s' % '1135_May2015'])[-4:-1] == '201'
            else '2012' if str(rec['sis_Date_%s' % '1135_May2015'])[-5:-1] == '2012'
            else 'N/A'))
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .select(lambda rec: rec['OxfordSrcCode'][0:4] != 'Note')
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1135_May2015', 'sis_Year_%s' % '1135_May2015', 'sis_Location_%s' % '1135_May2015'])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

28
28

sis_Year_1135_May2015,count,frequency
N/A,28,1.0

In [70]:
tbl_sis[sis].valuecounts('sis_Location_%s' % sis).displayall()
# 1026-PF-GN-CONWAY, 1083-PF-GH-CONWAY, 1135-PF-SN-CONWAY, 1147-PF-MR-CONWAY, 1006-PF-GM-CONWAY, 1134-PF-ML-CONWAY

sis_Location_1135_May2015,count,frequency
Pikine,28,1.0

In [71]:
sis = '1147_Jul2015'
tbl_sis['1147_Jul2015'] = (
    etl
    .fromxlsx(sample_information_sheets['1147_Jul2015'][0], sample_information_sheets['1147_Jul2015'][1], row_offset=13)
    .rename('7. Study Sample Id', 'OxfordSrcCode')
    .rename('9. Collection date', 'sis_Date_%s' % sis)
    .rename(3, 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1147_Jul2015', lambda rec: (
            str(rec['sis_Date_%s' % '1147_Jul2015'])[0:4] if str(rec['sis_Date_%s' % '1147_Jul2015'])[0:3] == '201'
            else str(rec['sis_Date_%s' % '1147_Jul2015'])[-4:] if str(rec['sis_Date_%s' % '1147_Jul2015'])[-4:-1] == '201'
            else '2012' if str(rec['sis_Date_%s' % '1147_Jul2015'])[-5:-1] == '2012'
            else 'N/A'))
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .select(lambda rec: rec['OxfordSrcCode'][0:4] != 'Note')
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1147_Jul2015', 'sis_Year_%s' % '1147_Jul2015', 'sis_Location_%s' % '1147_Jul2015'])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

134
134

sis_Year_1147_Jul2015,count,frequency
2014,134,1.0

In [72]:
tbl_sis[sis].valuecounts('sis_Location_%s' % sis).displayall()
# 1026-PF-GN-CONWAY, 1083-PF-GH-CONWAY, 1135-PF-SN-CONWAY, 1147-PF-MR-CONWAY, 1006-PF-GM-CONWAY, 1134-PF-ML-CONWAY

sis_Location_1147_Jul2015,count,frequency
Nema,63,0.4701492537313433
Kobeni,31,0.23134328358208955
Selibaby,28,0.208955223880597
Aioun,12,0.08955223880597014

In [73]:
sis = '1102_Nov2013'
tbl_sis['1102_Nov2013'] = (
    etl
    .fromxlsx(sample_information_sheets['1102_Nov2013'][0], sample_information_sheets['1102_Nov2013'][1], row_offset=12)
    .rename('Sample ID*', 'OxfordSrcCode')
    .rename('Date/Month/Year of Collection*', 'sis_Date_%s' % sis)
    .rename('Province/Region/Town of Origin*', 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1102_Nov2013', lambda rec: str(rec['sis_Date_%s' % '1102_Nov2013'])[0:4])
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1102_Nov2013', 'sis_Year_%s' % '1102_Nov2013', 'sis_Location_%s' % sis])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

12
12

sis_Year_1102_Nov2013,count,frequency
2012,12,1.0

In [74]:
tbl_sis[sis].valuecounts('sis_Location_%s' % sis).displayall()

sis_Location_1102_Nov2013,count,frequency
Maevatanana,12,1.0

In [75]:
sis = '1102_Jan2014'
tbl_sis['1102_Jan2014'] = (
    etl
    .fromxlsx(sample_information_sheets['1102_Jan2014'][0], sample_information_sheets['1102_Jan2014'][1], row_offset=12)
    .rename('Sample ID*', 'OxfordSrcCode')
    .rename('Date/Month/Year of Collection*', 'sis_Date_%s' % sis)
    .rename('Province/Region/Town of Origin*', 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1102_Jan2014', lambda rec: str(rec['sis_Date_%s' % '1102_Jan2014'])[0:4])
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1102_Jan2014', 'sis_Year_%s' % '1102_Jan2014', 'sis_Location_%s' % sis])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

48
48

/Users/rpearson/miniconda3/envs/biipy/lib/python3.5/site-packages/openpyxl/workbook/names/named_range.py:125: UserWarning: Discarded range with reserved name
  warnings.warn("Discarded range with reserved name")

sis_Year_1102_Jan2014,count,frequency
2013,48,1.0

In [76]:
tbl_sis[sis].valuecounts('sis_Location_%s' % sis).displayall()

/Users/rpearson/miniconda3/envs/biipy/lib/python3.5/site-packages/openpyxl/workbook/names/named_range.py:125: UserWarning: Discarded range with reserved name
  warnings.warn("Discarded range with reserved name")

sis_Location_1102_Jan2014,count,frequency
Maevatanana,48,1.0

In [77]:
sis = '1102_Apr2014'
tbl_sis['1102_Apr2014'] = (
    etl
    .fromxlsx(sample_information_sheets['1102_Apr2014'][0], sample_information_sheets['1102_Apr2014'][1], row_offset=12)
    .rename('Sample ID*', 'OxfordSrcCode')
    .rename('Date/Month/Year of Collection*', 'sis_Date_%s' % sis)
    .rename('Province/Region/Town of Origin*', 'sis_Location_%s' % sis)
    .addfield('sis_Year_%s' % '1102_Apr2014', lambda rec: str(rec['sis_Date_%s' % '1102_Apr2014'])[0:4])
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1102_Apr2014', 'sis_Year_%s' % '1102_Apr2014', 'sis_Location_%s' % sis])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

82
82

/Users/rpearson/miniconda3/envs/biipy/lib/python3.5/site-packages/openpyxl/workbook/names/named_range.py:125: UserWarning: Discarded range with reserved name
  warnings.warn("Discarded range with reserved name")

sis_Year_1102_Apr2014,count,frequency
2014,74,0.9024390243902439
2013,8,0.0975609756097561

In [78]:
tbl_sis[sis].valuecounts('sis_Location_%s' % sis).displayall()

/Users/rpearson/miniconda3/envs/biipy/lib/python3.5/site-packages/openpyxl/workbook/names/named_range.py:125: UserWarning: Discarded range with reserved name
  warnings.warn("Discarded range with reserved name")

sis_Location_1102_Apr2014,count,frequency
Farafangana,50,0.6097560975609756
Antsohihy,22,0.2682926829268293
Maevatanana,8,0.0975609756097561
Miandrivazo,2,0.024390243902439025

In [79]:
# Note have replaced spaces with underscores in source code
sis = '1155_Jun2013'
tbl_sis['1155_Jun2013'] = (
    etl
    .fromxlsx(sample_information_sheets['1155_Jun2013'][0], sample_information_sheets['1155_Jun2013'][1], row_offset=0)
    .rename('Donor Source Code', 'OxfordSrcCode')
    .convert('OxfordSrcCode', lambda v: v.replace(' ', '_'))
    .rename('Date of Blood Collection', 'sis_Date_%s' % sis)
    .addfield('sis_Year_%s' % '1155_Jun2013', lambda rec: str(rec['sis_Date_%s' % '1155_Jun2013'])[0:4])
    .select(lambda rec: rec['OxfordSrcCode'] is not None)
    .cut(['OxfordSrcCode', 'sis_Date_%s' % '1155_Jun2013', 'sis_Year_%s' % '1155_Jun2013'])
#     .select(lambda rec: rec['OxfordSrcCode'] is not None and rec['OxfordSrcCode'].startswith('163'))
)
print(len(tbl_sis[sis].data()))
print(len(tbl_sis[sis].distinct('OxfordSrcCode').data()))
tbl_sis[sis].valuecounts('sis_Year_%s' % sis).displayall()

/Users/rpearson/miniconda3/envs/biipy/lib/python3.5/site-packages/openpyxl/workbook/names/named_range.py:125: UserWarning: Discarded range with reserved name
  warnings.warn("Discarded range with reserved name")

151
151

sis_Year_1155_Jun2013,count,frequency
2011,73,0.48344370860927155
2012,60,0.3973509933774834
2013,18,0.11920529801324503

# Solaris SQL queries

In [80]:
oxford_table_fn

'/nfs/team112_internal/rp7/data/methods-dev/builds/Pf6.0/20161214_samples_which_release/oxford.txt'

# Ran the following manually on malsrv2
mysql -u solaris_ro -hmalloc-db -P3309 solaris -e "select * from oxford;" \
> /nfs/team112_internal/rp7/data/methods-dev/builds/Pf6.0/20161214_samples_which_release/oxford.txt

In [81]:
sampling_date_fn

'/nfs/team112_internal/rp7/data/methods-dev/builds/Pf6.0/20161214_samples_which_release/sampling_date.txt'

# Ran the following manually on malsrv2
mysql -u solaris_ro -hmalloc-db -P3309 solaris -e "\
    select vstoc.value as oxford_code, cs.sampling_date \
    from vw_sample_tag_ox_code vstoc, contributed_sample cs \
    where vstoc.sample_id = cs.sample_id;" \
> /nfs/team112_internal/rp7/data/methods-dev/builds/Pf6.0/20161214_samples_which_release/sampling_date.txt

In [82]:
solaris_dates_fn

'/nfs/team112_internal/rp7/data/methods-dev/builds/Pf6.0/20161214_samples_which_release/solaris_dates.txt'

# Ran the following manually on malsrv2
mysql -u solaris_ro -hmalloc-db -P3309 solaris -e "\
    select vstoc.value as oxford_code, c.arrival_date, cs.sampling_date \
    from vw_sample_tag_ox_code vstoc, contribution c, contributed_sample cs \
    where vstoc.sample_id = cs.sample_id and
    cs.contribution_id = c.id;" \
> /nfs/team112_internal/rp7/data/methods-dev/builds/Pf6.0/20161214_samples_which_release/solaris_dates.txt

# Create individual tables

In [83]:
tbl_oxford = (
    etl
    .fromtsv(oxford_table_fn)
    .distinct('oxford_code')
    .addfield('batch_arrived_year', lambda rec: rec['batch_arrived'][-4:])
#     .convert('country_code', lambda v: 'MM', where=lambda r: r['oxford_code'].startswith('QC'))
#     .convert('country_name', lambda v: 'Myanmar', where=lambda r: r['oxford_code'].startswith('QC'))
)
print(len(tbl_oxford.distinct('oxford_code').data()))
print(len(tbl_oxford.data()))
tbl_oxford

210873
210873

+--------------------+-------------+-----------+--------------------+--------------------------+--------------------------+-------------+--------------+--------------+--------------------+---------------+-------------+-----------+--------+---------------+----------+------------+---------------------+----------+---------------+----------------------------------------------------+---------------------------------------------------------------+-----------------+----------------+----------+--------------------+
| sanger_sample_code | oxford_code | oxford_id | oxford_source_code | oxford_donor_source_code | donor_type               | sample_type | country_code | country_name | institution_code   | freezer_code  | box_code    | slot_code | volume | concentration | donor_id | study_code | species             | batch_id | batch_arrived | batch_description                                  | batch_comments                                                | batch_source1   | batch_source2  | id       | batch_arrived_year |
+====================+=============+===========+====================+==========================+==========================+=============+==============+==============+====================+===============+=============+===========+========+===============+==========+============+=====================+==========+===============+====================================================+===============================================================+=================+================+==========+====================+
| 'NULL'             | 'AA0001-C'  | '142090'  | 'Ghana_18-F6'      | 'Ghana_18-F6'            | 'anopheles wild isolate' | 'DNA'       | 'GH'         | 'Ghana'      | 'NULL'             | 'NULL'        | 'NULL'      | 'NULL'    | 'NULL' | 'NULL'        | '217737' | 'AA'       | 'Anopheles gambiae' | '195'    | '12 Nov 2008' | '2 mosquito samples in Sanger sequencing pipeline' | 'Samples sourced from Professor Janet Hemmingway'             | 'Gareth Maslen' | 'Kirk Rockett' | '87'     | '2008'             |
+--------------------+-------------+-----------+--------------------+--------------------------+--------------------------+-------------+--------------+--------------+--------------------+---------------+-------------+-----------+--------+---------------+----------+------------+---------------------+----------+---------------+----------------------------------------------------+---------------------------------------------------------------+-----------------+----------------+----------+--------------------+
| 'NULL'             | 'AA0002-C'  | '142091'  | 'Ghana_18-G1'      | 'Ghana_18-G1'            | 'anopheles wild isolate' | 'DNA'       | 'GH'         | 'Ghana'      | 'NULL'             | 'NULL'        | 'NULL'      | 'NULL'    | 'NULL' | 'NULL'        | '217738' | 'AA'       | 'Anopheles gambiae' | '195'    | '12 Nov 2008' | '2 mosquito samples in Sanger sequencing pipeline' | 'Samples sourced from Professor Janet Hemmingway'             | 'Gareth Maslen' | 'Kirk Rockett' | '1'      | '2008'             |
+--------------------+-------------+-----------+--------------------+--------------------------+--------------------------+-------------+--------------+--------------+--------------------+---------------+-------------+-----------+--------+---------------+----------+------------+---------------------+----------+---------------+----------------------------------------------------+---------------------------------------------------------------+-----------------+----------------+----------+--------------------+
| '2572STDY5505702'  | 'AA0003-C'  | '163232'  | '3-C7'             | '3-C7'                   | 'anopheles wild isolate' | 'DNA'       | 'GH'         | 'Ghana'      | 'Sanger Institute' | 'Freezer_177' | 'DN275926R' | 'E03'     | '49'   | '4.65'        | '236424' | 'AA'       | 'Anopheles gambiae' | '312'    | '20 May 2010' | 'anopheles gambiae samples sent by D. Weetman'     | '7 S. form kdr resistant, 7 M form susc. and 6 M form resis.' | 'David Weetman' | 'Daniel Mead'  | '258707' | '2010'             |
+--------------------+-------------+-----------+--------------------+--------------------------+--------------------------+-------------+--------------+--------------+--------------------+---------------+-------------+-----------+--------+---------------+----------+------------+---------------------+----------+---------------+----------------------------------------------------+---------------------------------------------------------------+-----------------+----------------+----------+--------------------+
| 'NULL'             | 'AA0003-Cx' | '199048'  | '3-C7'             | '3-C7'                   | 'anopheles wild isolate' | 'DNA'       | 'GH'         | 'Ghana'      | 'NULL'             | 'NULL'        | 'NULL'      | 'NULL'    | 'NULL' | 'NULL'        | '236424' | 'AA'       | 'Anopheles gambiae' | '312'    | '20 May 2010' | 'anopheles gambiae samples sent by D. Weetman'     | '7 S. form kdr resistant, 7 M form susc. and 6 M form resis.' | 'David Weetman' | 'Daniel Mead'  | '104'    | '2010'             |
+--------------------+-------------+-----------+--------------------+--------------------------+--------------------------+-------------+--------------+--------------+--------------------+---------------+-------------+-----------+--------+---------------+----------+------------+---------------------+----------+---------------+----------------------------------------------------+---------------------------------------------------------------+-----------------+----------------+----------+--------------------+
| 'NULL'             | 'AA0004-C'  | '163233'  | '3-B10'            | '3-B10'                  | 'anopheles wild isolate' | 'DNA'       | 'GH'         | 'Ghana'      | 'Sanger Institute' | 'Freezer_177' | 'A2A4'      | 'E02'     | '49'   | '3.02'        | '236425' | 'AA'       | 'Anopheles gambiae' | '312'    | '20 May 2010' | 'anopheles gambiae samples sent by D. Weetman'     | '7 S. form kdr resistant, 7 M form susc. and 6 M form resis.' | 'David Weetman' | 'Daniel Mead'  | '70'     | '2010'             |
+--------------------+-------------+-----------+--------------------+--------------------------+--------------------------+-------------+--------------+--------------+--------------------+---------------+-------------+-----------+--------+---------------+----------+------------+---------------------+----------+---------------+----------------------------------------------------+---------------------------------------------------------------+-----------------+----------------+----------+--------------------+
...

In [84]:
tbl_solaris_dates = (
    etl
    .fromtsv(solaris_dates_fn)
#     .selectne('sampling_date', 'NULL')
    .addfield('sampling_Year', lambda rec: rec['sampling_date'][0:4])
#     .addfield('solaris_Date', lambda rec: rec['sampling_date'])
#     .addfield('solaris_Year', lambda rec: rec['solaris_Date'][0:4])
    .addfield('arrival_Year', lambda rec: rec['arrival_date'][0:4])
    .distinct('oxford_code')
)
print(len(tbl_solaris_dates.data()))
print(len(tbl_solaris_dates.distinct('oxford_code').data()))
tbl_solaris_dates

25447
25447

+-------------+-----------------------+---------------+---------------+--------------+
| oxford_code | arrival_date          | sampling_date | sampling_Year | arrival_Year |
+=============+=======================+===============+===============+==============+
| '3315'      | '2008-12-01 00:00:00' | 'NULL'        | 'NULL'        | '2008'       |
+-------------+-----------------------+---------------+---------------+--------------+
| '3541'      | '2008-11-01 00:00:00' | 'NULL'        | 'NULL'        | '2008'       |
+-------------+-----------------------+---------------+---------------+--------------+
| '6390'      | '2009-01-01 00:00:00' | 'NULL'        | 'NULL'        | '2009'       |
+-------------+-----------------------+---------------+---------------+--------------+
| '9050'      | '2008-12-01 00:00:00' | 'NULL'        | 'NULL'        | '2008'       |
+-------------+-----------------------+---------------+---------------+--------------+
| 'AA0001-C'  | 'NULL'                | 'NULL'        | 'NULL'        | 'NULL'       |
+-------------+-----------------------+---------------+---------------+--------------+
...

In [85]:
tbl_olivo = (etl
    .fromxlsx(olivo_fn)
)
print(len(tbl_olivo.data()))
tbl_olivo.tail()

7979

+------+------------+---------------+-----------------+----------------------+----------------------+-------+--------------+------+-------+------------------+---------------------------+------------+-------------+-------------+-------------+------+--------------------------------------+--------------+--------------------+------------------+-------------------------------------------------------------------------------------------------------------------------+---------------------+-----------+-----------+-----------+-------------------------+-----------------------+----------------+--------------------------+-----------------+------------------+------------------+-------------------------------------------------------------------------------------+---------------+----------+--------+-------------+------------------+-----------+-----------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+------------+-------------+--------------+---------------+-------------+-----------+------------+---------------+--------------------+---------------------+-------------+-------------+---------------------+-----------+-----------------+---------+---------------+-----------+
| Num  | Sample     | OxfordSrcCode | OxfordDonorCode | AlfrescoStudyCode    | Study                | Type  | NotAmplified | InV5 | InV4  | SubContinentCode | SubContinentName          | RegionCode | CountryCode | CountryName | Location    | Year | Date                                 | HasDuplicate | DiscardAsDuplicate | ManuallyExcluded | Usable                                                                                                                  | Typability-100kSnps | Typable75 | Typable80 | Typable95 | MedianCoverage-100kSnps | MeanCoverage-100kSnps | Stdev-100kSnps | CoefVarCoverage-100kSnps | Bases5Xcoverage | MeanReadCoverage | Sequencing reads | BamFile                                                                             | Species       | Fws      | Clonal | ArtHalfLife | crt_72-76[CVMNK] | crt_24[D] | crt_97[H] | crt_144[A] | crt_148[L] | crt_194[I] | crt_220[A] | crt_271[Q] | crt_326[N] | crt_333[T] | crt_342[T] | crt_356[I] | crt_371[R] | dhfr_51[N] | dhfr_59[C] | dhfr_108[S] | dhfr_164[I] | dhps_436[S] | dhps_437[G] | dhps_540[K] | dhps_581[A] | dhps_613[A] | mdr1_86[N] | mdr1_184[Y] | mdr1_1246[D] | arps10_127[V] | mdr2_484[T] | fd_193[D] | exo_415[E] | arps10-128[D] | mdr1-CN-refgenecov | mdr1-CN-covAnalysis | mdr1-CN-HMM | pm23-CN-HMM | pm23-join-amplified | K13Common | K13CommonAllele | WAF-PC1 | WAF-PC1-Class | aat-S258L |
+======+============+===============+=================+======================+======================+=======+==============+======+=======+==================+===========================+============+=============+=============+=============+======+======================================+==============+====================+==================+=========================================================================================================================+=====================+===========+===========+===========+=========================+=======================+================+==========================+=================+==================+==================+=====================================================================================+===============+==========+========+=============+==================+===========+===========+============+============+============+============+============+============+============+============+============+============+============+============+=============+=============+=============+=============+=============+=============+=============+============+=============+==============+===============+=============+===========+============+===============+====================+=====================+=============+=============+=====================+===========+=================+=========+===============+===========+
| 1282 | 'PD1405-C' | 'OHP-00308'   | 'OHP-00308'     | '1125-PF-TH-NOSTEN'  | '1125-PF-TH-NOSTEN'  | 'dna' | True         | True | True  | 'WSEA'           | 'Western south-east Asia' | 'WTH'      | 'TH'        | 'Thailand'  | 'Mae La'    | 2004 | datetime.datetime(2004, 4, 30, 0, 0) | False        | False              | False            | '=IF(T7976,"Duplicate",IF(NOT(X7976),"Lt75PcCoverage",IF(N7976="Lab","Lab",IF(U7976<>FALSE,"ManuallyExcluded",TRUE))))' |  0.9968891886722171 | True      | True      | True      |                      44 |             43.213605 |      12.638989 |       0.2924770798455718 |        19954345 |            32.49 | 'ERS498435'      | '/lustre/scratch109/malaria/pfalciparum/output/c/2/0/e/247383/1_bam_merge/pe.1.bam' | 'Pf,Pv*,Pow*' | 0.996414 | True   | '-'         | 'CVIET'          | 'D'       | 'H'       | 'A'        | 'L'        | 'I'        | 'S'        | 'e'        | 's'        | 'T'        | 'T'        | 'T'        | 'I'        | 'I'        | 'R'        | 'N'         | 'I'         | 'S'         | 'G'         | 'E'         | 'G'         | 'A'         | 'N'        | 'Y'         | 'D'          | 'V'           | 'T'         | 'D'       | 'E'        | 'D'           | '-'                |                   2 |           2 |           1 | False               | 'WT'      | '-'             | '-'     | '-'           | 'S'       |
+------+------------+---------------+-----------------+----------------------+----------------------+-------+--------------+------+-------+------------------+---------------------------+------------+-------------+-------------+-------------+------+--------------------------------------+--------------+--------------------+------------------+-------------------------------------------------------------------------------------------------------------------------+---------------------+-----------+-----------+-----------+-------------------------+-----------------------+----------------+--------------------------+-----------------+------------------+------------------+-------------------------------------------------------------------------------------+---------------+----------+--------+-------------+------------------+-----------+-----------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+------------+-------------+--------------+---------------+-------------+-----------+------------+---------------+--------------------+---------------------+-------------+-------------+---------------------+-----------+-----------------+---------+---------------+-----------+
| 7600 | 'QS0060-C' | 'A-21'        | 'A-21'          | '1098-PF-ET-GOLASSA' | '1098-PF-ET-GOLASSA' | 'dna' | True         | True | False | 'EAF'            | 'East Africa'             | 'ET'       | 'ET'        | 'Ethiopia'  | '-'         | '-'  | '-'                                  | False        | False              | False            | '=IF(T7977,"Duplicate",IF(NOT(X7977),"Lt75PcCoverage",IF(N7977="Lab","Lab",IF(U7977<>FALSE,"ManuallyExcluded",TRUE))))' |                   0 | False     | False     | False     |                       1 |              1.004281 |       0.157547 |      0.15687541634263716 | '-'             | '-'              | 'ERS690493'      | '/lustre/scratch111/malaria/pdna/output/5/0/7/f/558363/1_bam_merge/pe.1.bam'        | 'Pv'          | '-'      | True   | '-'         | '-'              | '-'       | '-'       | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'         | '-'         | '-'         | '-'         | '-'         | '-'         | '-'         | '-'        | '-'         | '-'          | '-'           | '-'         | '-'       | '-'        | '-'           | '-'                | '-'                 | '-'         | '-'         | '-'                 | 'MI'      | '-'             | '-'     | '-'           | '-'       |
+------+------------+---------------+-----------------+----------------------+----------------------+-------+--------------+------+-------+------------------+---------------------------+------------+-------------+-------------+-------------+------+--------------------------------------+--------------+--------------------+------------------+-------------------------------------------------------------------------------------------------------------------------+---------------------+-----------+-----------+-----------+-------------------------+-----------------------+----------------+--------------------------+-----------------+------------------+------------------+-------------------------------------------------------------------------------------+---------------+----------+--------+-------------+------------------+-----------+-----------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+------------+-------------+--------------+---------------+-------------+-----------+------------+---------------+--------------------+---------------------+-------------+-------------+---------------------+-----------+-----------------+---------+---------------+-----------+
| 7610 | 'QS0131-C' | 'I-20'        | 'I-20'          | '1098-PF-ET-GOLASSA' | '1098-PF-ET-GOLASSA' | 'dna' | True         | True | False | 'EAF'            | 'East Africa'             | 'ET'       | 'ET'        | 'Ethiopia'  | '-'         | '-'  | '-'                                  | False        | False              | False            | '=IF(T7978,"Duplicate",IF(NOT(X7978),"Lt75PcCoverage",IF(N7978="Lab","Lab",IF(U7978<>FALSE,"ManuallyExcluded",TRUE))))' |                   0 | False     | False     | False     |                       1 |              1.030617 |       0.251218 |       0.2437549545563483 | '-'             | '-'              | 'ERS690620'      | '/lustre/scratch111/malaria/pdna/output/0/0/6/7/558427/1_bam_merge/pe.1.bam'        | 'Pv'          | '-'      | True   | '-'         | '-'              | '-'       | '-'       | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'         | '-'         | '-'         | '-'         | '-'         | '-'         | '-'         | '-'        | '-'         | '-'          | '-'           | '-'         | '-'       | '-'        | '-'           | '-'                | '-'                 | '-'         | '-'         | '-'                 | 'MI'      | '-'             | '-'     | '-'           | '-'       |
+------+------------+---------------+-----------------+----------------------+----------------------+-------+--------------+------+-------+------------------+---------------------------+------------+-------------+-------------+-------------+------+--------------------------------------+--------------+--------------------+------------------+-------------------------------------------------------------------------------------------------------------------------+---------------------+-----------+-----------+-----------+-------------------------+-----------------------+----------------+--------------------------+-----------------+------------------+------------------+-------------------------------------------------------------------------------------+---------------+----------+--------+-------------+------------------+-----------+-----------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+------------+-------------+--------------+---------------+-------------+-----------+------------+---------------+--------------------+---------------------+-------------+-------------+---------------------+-----------+-----------------+---------+---------------+-----------+
| 7616 | 'QS0145-C' | 'M-06'        | 'M-06'          | '1098-PF-ET-GOLASSA' | '1098-PF-ET-GOLASSA' | 'dna' | True         | True | False | 'EAF'            | 'East Africa'             | 'ET'       | 'ET'        | 'Ethiopia'  | '-'         | '-'  | '-'                                  | False        | False              | False            | '=IF(T7979,"Duplicate",IF(NOT(X7979),"Lt75PcCoverage",IF(N7979="Lab","Lab",IF(U7979<>FALSE,"ManuallyExcluded",TRUE))))' |                   0 | False     | False     | False     |                       1 |              0.991143 |        0.16816 |       0.1696627025565433 | '-'             | '-'              | 'ERS690643'      | '/lustre/scratch111/malaria/pdna/output/9/c/b/6/558438/1_bam_merge/pe.1.bam'        | 'Pv'          | '-'      | True   | '-'         | '-'              | '-'       | '-'       | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'         | '-'         | '-'         | '-'         | '-'         | '-'         | '-'         | '-'        | '-'         | '-'          | '-'           | '-'         | '-'       | '-'        | '-'           | '-'                | '-'                 | '-'         | '-'         | '-'                 | 'MI'      | '-'             | '-'     | '-'           | '-'       |
+------+------------+---------------+-----------------+----------------------+----------------------+-------+--------------+------+-------+------------------+---------------------------+------------+-------------+-------------+-------------+------+--------------------------------------+--------------+--------------------+------------------+-------------------------------------------------------------------------------------------------------------------------+---------------------+-----------+-----------+-----------+-------------------------+-----------------------+----------------+--------------------------+-----------------+------------------+------------------+-------------------------------------------------------------------------------------+---------------+----------+--------+-------------+------------------+-----------+-----------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+------------+-------------+--------------+---------------+-------------+-----------+------------+---------------+--------------------+---------------------+-------------+-------------+---------------------+-----------+-----------------+---------+---------------+-----------+
| 7617 | 'QS0153-C' | 'M-14'        | 'M-14'          | '1098-PF-ET-GOLASSA' | '1098-PF-ET-GOLASSA' | 'dna' | True         | True | False | 'EAF'            | 'East Africa'             | 'ET'       | 'ET'        | 'Ethiopia'  | 'West_Arsi' | '-'  | '-'                                  | False        | False              | False            | '=IF(T7980,"Duplicate",IF(NOT(X7980),"Lt75PcCoverage",IF(N7980="Lab","Lab",IF(U7980<>FALSE,"ManuallyExcluded",TRUE))))' |                   0 | False     | False     | False     |                       1 |              1.019513 |        0.18954 |      0.18591229341852433 | '-'             | '-'              | 'ERS690561'      | '/lustre/scratch111/malaria/pdna/output/a/f/5/9/558443/1_bam_merge/pe.1.bam'        | 'Pv'          | '-'      | True   | '-'         | '-'              | '-'       | '-'       | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'        | '-'         | '-'         | '-'         | '-'         | '-'         | '-'         | '-'         | '-'        | '-'         | '-'          | '-'           | '-'         | '-'       | '-'        | '-'           | '-'                | '-'                 | '-'         | '-'         | '-'                 | 'MI'      | '-'             | '-'     | '-'           | '-'       |
+------+------------+---------------+-----------------+----------------------+----------------------+-------+--------------+------+-------+------------------+---------------------------+------------+-------------+-------------+-------------+------+--------------------------------------+--------------+--------------------+------------------+-------------------------------------------------------------------------------------------------------------------------+---------------------+-----------+-----------+-----------+-------------------------+-----------------------+----------------+--------------------------+-----------------+------------------+------------------+-------------------------------------------------------------------------------------+---------------+----------+--------+-------------+------------------+-----------+-----------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+------------+-------------+--------------+---------------+-------------+-----------+------------+---------------+--------------------+---------------------+-------------+-------------+---------------------+-----------+-----------------+---------+---------------+-----------+

In [86]:
tbl_elife = (etl
    .fromxlsx(elife_fn)
    .convert('Year', str)
)
print(len(tbl_elife.data()))
tbl_elife.tail()

/Users/rpearson/miniconda3/envs/biipy/lib/python3.5/site-packages/openpyxl/workbook/names/named_range.py:125: UserWarning: Discarded range with reserved name
  warnings.warn("Discarded range with reserved name")

3411

+------------+----------------------+------+------------------+-----------+--------+-------+------------+---------+
| Sample     | AlfrescoStudy        | #    | Sequencing Reads | Country   | Year   | Study | Sample ID  | In Pf3k |
+============+======================+======+==================+===========+========+=======+============+=========+
| 'PV0344-C' | '1052-PF-TRAC-WHITE' | 3407 | 'ERS347482'      | 'Vietnam' | '2011' |  1052 | 'PV0344-C' | 'Yes'   |
+------------+----------------------+------+------------------+-----------+--------+-------+------------+---------+
| 'PV0345-C' | '1052-PF-TRAC-WHITE' | 3408 | 'ERS347490'      | 'Vietnam' | '2011' |  1052 | 'PV0345-C' | 'Yes'   |
+------------+----------------------+------+------------------+-----------+--------+-------+------------+---------+
| 'PV0347-C' | '1052-PF-TRAC-WHITE' | 3409 | 'ERS347506'      | 'Vietnam' | '2011' |  1052 | 'PV0347-C' | 'Yes'   |
+------------+----------------------+------+------------------+-----------+--------+-------+------------+---------+
| 'PV0355-C' | '1052-PF-TRAC-WHITE' | 3410 | 'ERS347475'      | 'Vietnam' | '2012' |  1052 | 'PV0355-C' | 'Yes'   |
+------------+----------------------+------+------------------+-----------+--------+-------+------------+---------+
| 'PV0358-C' | '1052-PF-TRAC-WHITE' | 3411 | 'ERS347499'      | 'Vietnam' | '2012' |  1052 | 'PV0358-C' | 'Yes'   |
+------------+----------------------+------+------------------+-----------+--------+-------+------------+---------+

In [87]:
tbl_sample_4_0 = (etl
    .fromtsv(sample_4_0_fn)
    .pushheader(['study', 'oxford_code'])
)
print(len(tbl_sample_4_0.data()))
tbl_sample_4_0.tail()
samples_4_0 = tbl_sample_4_0.values('oxford_code').array()
print(len(samples_4_0))

5158
5158

In [88]:
tbl_sample_5_0 = (etl
    .fromtsv(sample_5_0_fn)
    .pushheader(['study', 'oxford_code'])
)
print(len(tbl_sample_5_0.data()))
tbl_sample_5_0.tail()
samples_5_0 = tbl_sample_5_0.values('oxford_code').array()
print(len(samples_5_0))

6073
6073

In [89]:
tbl_sample_5_1 = (etl
    .fromtsv(sample_5_1_fn)
    .pushheader(['study', 'oxford_code'])
)
print(len(tbl_sample_5_1.data()))
tbl_sample_5_1.tail()
samples_5_1 = tbl_sample_5_1.values('oxford_code').array()
print(len(samples_5_1))

7283
7283

In [90]:
def which_release(rec):
    if rec['pf60_InV5']:
        if (not rec['pf60_InV5.1']) or (not rec['in_6_0']):
            return('5_0_NOT_SUBSEQUENT')
        else:
            return('5_0')
    elif rec['pf60_InV5.1']:
        if (not rec['in_6_0']):
            return('5_1_NOT_SUBSEQUENT')
        else:
            return('5_1')
    elif rec['in_6_0']:
        return('6_0')
    elif rec['State'] == 'in progress':
        return('in_progress')
    else:
        return('no_release')

In [91]:
panoptes_columns = [
    'Num',
    'Sample',
    'OxfordSrcCode',
    'OxfordDonorCode',
    'AlfrescoStudyCode',
    'Study',
    'Type',
    'NotAmplified',
    'InV5',
    'InV4',
    'SubContinentCode',
    'SubContinentName',
    'RegionCode',
    'CountryCode',
    'CountryName',
    'Location',
    'Year',
    'Date',
    'HasDuplicate',
    'DiscardAsDuplicate',
    'ManuallyExcluded',
    'run_accessions',
    'sampling_date',
    'sampling_Year',
    'arrival_date',
    'arrival_Year',
    'batch_arrived',
    'batch_arrived_year',
    'elife_Year',
    'pf60_OxfordSrcCode',
    'pf60_OxfordDonorCode',
    'pf60_AlfrescoStudyCode',
    'pf60_Type',
#     'InV6_public_interim',
    'pf60_InV5.1',
    'pf60_InV5',
    'pf60_InV4',
    'pf60_CountryCode',
    'pf60_CountryName',
    'Individual_ID',
    'pf60_HasDuplicate',
    'pf60_DiscardAsDuplicate',
    'pc_pass_missing',
    'pc_genome_covered_at_1x',
    'sis_Location_1093_Rob',
    'sis_Location_1094_Rob',
    'sis_Location_1095_Rob',
    'sis_Location_1096_Rob',
    'sis_Location_1097_Rob',
    'sis_Location_1098_Rob',
    'sis_Location_1100_Rob',
    'sis_Location_1102_Rob',
    'sis_Location_1103_Rob',
    'sis_Location_1107_Rob',
    'sis_Location_1136_Rob',
    'sis_Location_1137_Rob',
    'sis_Location_1044_Oct2012_NIH',
    'sis_Location_1044_Oct2012_TRAC',
    'sis_Location_1044_Jan2014',
    'sis_Location_1044_Jul2015',
    'sis_Location_1044_Aug2015',
    'sis_Location_1141_Oct2015',
    'sis_Location_1098_Oct2016',
    'sis_Location_1127_Feb2014',
    'sis_Location_1134_Feb2015',
    'sis_Location_1135_May2015',
    'sis_Location_1147_Jul2015',
    'sis_Location_1102_Nov2013',
    'sis_Location_1102_Jan2014',
    'sis_Location_1102_Apr2014',
    'sis_Location_1134_May2015',
    
    'sort_AlfrescoStudyCode',
    'Lucas_Date',
    'Lucas_Year',

#     'solaris_Year',
#     'solaris_Date',
#     'sis_Date_1044_Oct2012',
#     'sis_Year_1044_Oct2012',
#     'sis_Date_1044_Dec2012',
#     'sis_Year_1044_Dec2012',
#     'sis_Date_1044_Jan2014',
#     'sis_Year_1044_Jan2014',
#     'sis_Date_1101_Apr2013',
#     'sis_Year_1101_Apr2013',
]

for sis in sample_information_sheets:
    panoptes_columns.append('sis_Date_%s' % sis)
    panoptes_columns.append('sis_Year_%s' % sis)

In [92]:
sample_information_sheets.keys()

odict_keys(['1044_Oct2012_NIH', '1044_Oct2012_TRAC', '1044_Dec2012', '1044_Jan2014', '1101_Apr2013', '1052_Sep2015', '1138_Mar2015', '1155_May2015', '1134_May2015', '1062_Sep2013', '1021_Apr2010', '1044_Aug2015', '1044_Jul2015', '1141_Oct2015', '1125_Nov2013', '1098_Oct2016', '1127_Feb2014', '1134_Feb2015', '1135_May2015', '1147_Jul2015', '1102_Nov2013', '1102_Jan2014', '1102_Apr2014', '1155_Jun2013', '1093_Rob', '1094_Rob', '1095_Rob', '1096_Rob', '1097_Rob', '1098_Rob', '1100_Rob', '1102_Rob', '1103_Rob', '1107_Rob', '1136_Rob', '1137_Rob'])

In [139]:
final_columns = collections.OrderedDict()
final_columns['Sample'] = 'Sample'
final_columns['pf60_OxfordSrcCode'] = 'OxfordSrcCode'
final_columns['pf60_OxfordDonorCode'] = 'OxfordDonorCode'
final_columns['Individual_ID'] = 'Individual_ID'
final_columns['pf60_AlfrescoStudyCode'] = 'AlfrescoStudyCode'
final_columns['pf60_Type'] = 'Type'
final_columns['pf60_InV5.1'] = 'InV5.1'
final_columns['pf60_InV5'] = 'InV5'
# final_columns['pf60_InV4'] = 'InV4'
final_columns['pf60_SubContinentCode'] = 'SubContinentCode'
final_columns['pf60_SubContinentName'] = 'SubContinentName'
final_columns['pf60_RegionCode'] = 'RegionCode'
final_columns['pf60_CountryCode'] = 'CountryCode'
final_columns['pf60_CountryName'] = 'CountryName'
final_columns['Site'] = 'Site'
final_columns['pf60_Year'] = 'Year'
final_columns['pf60_Date'] = 'Date'
final_columns['pf60_HasDuplicate'] = 'HasDuplicate'
final_columns['pf60_DiscardAsDuplicate'] = 'DiscardAsDuplicate'
final_columns['run_accessions'] = 'run_accessions'
final_columns['pc_pass_missing'] = 'pc_pass_missing'
final_columns['pc_genome_covered_at_1x'] = 'pc_genome_covered_at_1x'
final_columns['pf60_Year_source'] = 'Year_source'

In [94]:
RegionCode_lkp = collections.OrderedDict()
RegionCode_lkp['Bangladesh']       = 'BD'
RegionCode_lkp['Benin']            = 'BJ'
RegionCode_lkp['Burkina Faso']     = 'BF'
RegionCode_lkp['Cambodia']         = '?'
RegionCode_lkp['Cameroon']         = 'CM'
RegionCode_lkp['Colombia']         = 'CO'
RegionCode_lkp['Congo DR']         = 'CD'
RegionCode_lkp['Ethiopia']         = 'ET'
RegionCode_lkp['Gambia']           = 'GM'
RegionCode_lkp['Ghana']            = 'GH'
RegionCode_lkp['Guinea']           = 'GN'
RegionCode_lkp['Indonesia']        = 'ID'
RegionCode_lkp['Ivory Coast']      = 'CI'
RegionCode_lkp['Kenya']            = 'KE'
RegionCode_lkp['Lab']              = 'Lab'
RegionCode_lkp['Laos']             = 'LA'
RegionCode_lkp['Madagascar']       = 'MG'
RegionCode_lkp['Malawi']           = 'MW'
RegionCode_lkp['Mali']             = 'ML'
RegionCode_lkp['Mauritania']       = 'MR'
RegionCode_lkp['Mozambique']       = 'MZ'
RegionCode_lkp['Myanmar']          = '?'
RegionCode_lkp['Nigeria']          = 'NG'
RegionCode_lkp['Papua New Guinea'] = 'PG'
RegionCode_lkp['Peru']             = 'PE'
RegionCode_lkp['Senegal']          = 'SN'
RegionCode_lkp['Tanzania']         = 'TZ'
RegionCode_lkp['Thailand']         = '?'
RegionCode_lkp['Uganda']           = 'UG'
RegionCode_lkp['Viet Nam']         = 'VN'

In [95]:
SubContinentCode_lkp = collections.OrderedDict()
SubContinentCode_lkp['Bangladesh']       = 'SAS'
SubContinentCode_lkp['Benin']            = 'WAF'
SubContinentCode_lkp['Burkina Faso']     = 'WAF'
SubContinentCode_lkp['Cambodia']         = 'ESEA'
SubContinentCode_lkp['Cameroon']         = 'WAF'
SubContinentCode_lkp['Colombia']         = 'SAM'
SubContinentCode_lkp['Congo DR']         = 'CAF'
SubContinentCode_lkp['Ethiopia']         = 'EAF'
SubContinentCode_lkp['Gambia']           = 'WAF'
SubContinentCode_lkp['Ghana']            = 'WAF'
SubContinentCode_lkp['Guinea']           = 'WAF'
SubContinentCode_lkp['Indonesia']        = 'OCE'
SubContinentCode_lkp['Ivory Coast']      = 'WAF'
SubContinentCode_lkp['Kenya']            = 'EAF'
SubContinentCode_lkp['Lab']              = 'Lab'
SubContinentCode_lkp['Laos']             = 'ESEA'
SubContinentCode_lkp['Madagascar']       = 'ISL'
SubContinentCode_lkp['Malawi']           = 'EAF'
SubContinentCode_lkp['Mali']             = 'WAF'
SubContinentCode_lkp['Mauritania']       = 'WAF'
SubContinentCode_lkp['Mozambique']       = 'EAF'
SubContinentCode_lkp['Myanmar']          = 'WSEA'
SubContinentCode_lkp['Nigeria']          = 'WAF'
SubContinentCode_lkp['Papua New Guinea'] = 'OCE'
SubContinentCode_lkp['Peru']             = 'SAM'
SubContinentCode_lkp['Senegal']          = 'WAF'
SubContinentCode_lkp['Tanzania']         = 'EAF'
SubContinentCode_lkp['Thailand']         = '?'
SubContinentCode_lkp['Uganda']           = 'EAF'
SubContinentCode_lkp['Viet Nam']         = 'ESEA'

In [96]:
SubContinentName_lkp = collections.OrderedDict()
SubContinentName_lkp['CAF'] = 'Central Africa'
SubContinentName_lkp['EAF'] = 'East Africa'
SubContinentName_lkp['ESEA'] = 'Eastern south-east Asia'
SubContinentName_lkp['ISL'] = 'Insular Africa'
SubContinentName_lkp['Lab'] = 'Lab'
SubContinentName_lkp['OCE'] = 'Oceania'
SubContinentName_lkp['SAM'] = 'South America'
SubContinentName_lkp['SAS'] = 'South Asia'
SubContinentName_lkp['WAF'] = 'West Africa'
SubContinentName_lkp['WSEA'] = 'Western south-east Asia'

In [97]:
def is_duplicate(prv, cur, nxt):
    if prv is None and (nxt['Individual_ID'] == cur['Individual_ID']):
        return(True)
    elif prv is None and (nxt['Individual_ID'] != cur['Individual_ID']):
        return(False)
    elif nxt is None and (prv['Individual_ID'] == cur['Individual_ID']):
        return(True)
    elif nxt is None and (prv['Individual_ID'] != cur['Individual_ID']):
        return(False)
    elif(
            (prv['Individual_ID'] == cur['Individual_ID']) or
            (nxt['Individual_ID'] == cur['Individual_ID'])
        ):
        return(True)
    else:
        return(False)
    
def discard_as_duplicate(prv, cur, nxt):
    if prv is None:
        return(False)
    elif (prv['Individual_ID'] == cur['Individual_ID']):
        return(True)
    else:
        return(False)

In [207]:
tbl_panoptes_samples = (
    tbl_sample_6_0
    .rename('study', 'pf60_AlfrescoStudyCode')
    .rename('sample', 'Sample')
    .leftjoin(tbl_oxford, lkey='Sample', rkey='oxford_code')
    .rename('oxford_source_code', 'pf60_OxfordSrcCode')
    .rename('oxford_donor_source_code', 'pf60_OxfordDonorCode')
    .rename('sample_type', 'pf60_Type')
    .rename('country_code', 'pf60_CountryCode')
    .rename('country_name', 'pf60_CountryName')
    .leftjoin(tbl_solaris_dates, lkey='Sample', rkey='oxford_code')
    .leftjoin(tbl_olivo, key='Sample')
    .leftjoin(tbl_elife, key='Sample', rprefix="elife_")
    .leftjoin(tbl_sis['1093_Rob'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1094_Rob'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1095_Rob'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1096_Rob'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1097_Rob'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1098_Rob'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1100_Rob'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1102_Rob'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1103_Rob'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1107_Rob'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1136_Rob'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1137_Rob'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1044_Oct2012_NIH'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1044_Oct2012_TRAC'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1044_Dec2012'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1044_Jan2014'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1101_Apr2013'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1052_Sep2015'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
#     .leftjoin(tbl_sis['1136_Jun2015'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1138_Mar2015'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
#     .leftjoin(tbl_sis['1137_Jul2015'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1155_May2015'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1134_May2015'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
#     .leftjoin(tbl_sis['1098_May2015'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1062_Sep2013'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1021_Apr2010'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1044_Aug2015'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1044_Jul2015'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1141_Oct2015'], lkey='pf60_OxfordDonorCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1125_Nov2013'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1098_Oct2016'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1127_Feb2014'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1134_Feb2015'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1135_May2015'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1147_Jul2015'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1102_Nov2013'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1102_Jan2014'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1102_Apr2014'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_sis['1155_Jun2013'], lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
    .leftjoin(tbl_lucas.distinct('OxfordSrcCode'), lkey='pf60_OxfordSrcCode', rkey='OxfordSrcCode')
#     .addfield('InV6_public_interim', lambda rec: not rec['pf60_AlfrescoStudyCode'] in expected_6_0_exclusion_studies)
    .addfield('pf60_InV5', lambda rec: rec['Sample'] in samples_5_0)
    .addfield('pf60_InV4', lambda rec: rec['Sample'] in samples_4_0)
    .addfield('pf60_InV5.1', lambda rec: rec['Sample'] in samples_5_1)
    .addfield('in_6_0', lambda rec: rec['Sample'] in samples_6_0)
    .addfield('release', which_release)
    .addfield('sort_AlfrescoStudyCode', lambda rec: '1151_1152' if rec['pf60_AlfrescoStudyCode'] in ['1151-PF-GH-AMENGA-ETEGO', '1152-PF-DBS-GH-AMENGA-ETEGO'] else rec['pf60_AlfrescoStudyCode'])
    .addfield('Individual_ID', lambda rec: rec['pf60_OxfordDonorCode'])
    .convert('Individual_ID', lambda v, r: 'LPC13', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1008-PF-SEA-RINGWALD' and r['Individual_ID'] == 'LPC13-R', pass_row=True)
    .convert('Individual_ID', lambda v, r: 'MKT07', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1008-PF-SEA-RINGWALD' and r['Individual_ID'] == 'MKT07_Dx', pass_row=True)
    .convert('Individual_ID', lambda v, r: 'ARC08-080', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1031-PF-SEA-PLOWE' and r['Individual_ID'] == 'ARC08-080R', pass_row=True)
    .convert('Individual_ID', lambda v, r: 'ARC08-088', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1031-PF-SEA-PLOWE' and r['Individual_ID'] == 'ARC08-088R', pass_row=True)
    .convert('Individual_ID', lambda v, r: 'ARC08-147', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1031-PF-SEA-PLOWE' and r['Individual_ID'] == 'ARC08-147R', pass_row=True)
    .convert('Individual_ID', lambda v, r: 'CP002', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1031-PF-SEA-PLOWE' and r['Individual_ID'] == 'CP002R', pass_row=True)
    .convert('Individual_ID', lambda v, r: 'CP012', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1031-PF-SEA-PLOWE' and r['Individual_ID'] == 'CP012R', pass_row=True)
    .convert('Individual_ID', lambda v, r: 'CP014', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1031-PF-SEA-PLOWE' and r['Individual_ID'] == 'CP014R', pass_row=True)
    .convert('Individual_ID', lambda v, r: 'CP059', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1031-PF-SEA-PLOWE' and r['Individual_ID'] == 'CP059R', pass_row=True)
    .convert('Individual_ID', lambda v, r: r['Individual_ID'][0:5], where=lambda r: r['pf60_AlfrescoStudyCode'] == '1015-PF-KE-NZILA', pass_row=True)
    .convert('Individual_ID', lambda v, r: r['Individual_ID'][0:11], where=lambda r: r['pf60_AlfrescoStudyCode'] == '1044-PF-KH-FAIRHURST' and r['Individual_ID'].startswith('163'), pass_row=True)
    .convert('Individual_ID', lambda v, r: r['Individual_ID'].replace('_MACS_1', '').replace('_MACS_2', '').replace('_MACS', '').replace('MACS', '').replace('_CF11', '').replace('CF11', '').replace('_LP', '').replace('.2', ''), where=lambda r: r['pf60_AlfrescoStudyCode'] == '1044-PF-KH-FAIRHURST', pass_row=True)
    .sort(['sort_AlfrescoStudyCode', 'Individual_ID', 'pc_pass_missing'])
    .addfieldusingcontext('pf60_HasDuplicate', is_duplicate)
    .addfieldusingcontext('pf60_DiscardAsDuplicate', discard_as_duplicate)
    .cut(panoptes_columns)
    .convert('pf60_CountryName', lambda v: 'Myanmar', where=lambda r: r['Sample'].startswith('QC'))
    .convert('pf60_CountryCode', lambda v: 'MM', where=lambda r: r['Sample'].startswith('QC'))
    .convert('pf60_CountryName', lambda v: 'Lab', where=lambda r: r['pf60_CountryCode'] == 'GB')
    .convert('pf60_CountryCode', lambda v: 'Lab', where=lambda r: r['pf60_CountryCode'] == 'GB')
    .convert('pf60_CountryName', lambda v: 'Lab', where=lambda r: r['pf60_CountryCode'] == 'US')
    .convert('pf60_CountryCode', lambda v: 'Lab', where=lambda r: r['pf60_CountryCode'] == 'US')
    .convert('pf60_CountryName', lambda v: 'Lab', where=lambda r: r['pf60_OxfordSrcCode'] in source_code_sites and source_code_sites[r['pf60_OxfordSrcCode']] == 'Lab')
    .convert('pf60_CountryCode', lambda v: 'Lab', where=lambda r: r['pf60_OxfordSrcCode'] in source_code_sites and source_code_sites[r['pf60_OxfordSrcCode']] == 'Lab')
    .convert('pf60_CountryName', lambda v: 'Ghana', where=lambda r: r['Sample'] in ['PL0001-01', 'PL0004-C', 'PL0004-CW'])
    .convert('pf60_CountryCode', lambda v: 'GH', where=lambda r: r['Sample'] in ['PL0001-01', 'PL0004-C', 'PL0004-CW'])
    .convert('pf60_CountryName', lambda v: 'Mozambique', where=lambda r: r['Sample'] in ['PL0002-01'])
    .convert('pf60_CountryCode', lambda v: 'MZ', where=lambda r: r['Sample'] in ['PL0002-01'])
    .convert('pf60_CountryName', lambda v: 'Uganda', where=lambda r: r['Sample'] in ['PL0003-01', 'PL0003-01W'])
    .convert('pf60_CountryCode', lambda v: 'UG', where=lambda r: r['Sample'] in ['PL0003-01', 'PL0003-01W'])
    .convert('pf60_CountryName', lambda v: 'Kenya', where=lambda r: r['Sample'] in ['PL0005-C', 'PL0005-CW'])
    .convert('pf60_CountryCode', lambda v: 'KE', where=lambda r: r['Sample'] in ['PL0005-C', 'PL0005-CW'])
    .convert('pf60_CountryName', lambda v: 'Lab', where=lambda r: r['Sample'] in ['PP0001-C', 'PP0003-C', 'PP0006-C', 'PP0007-C', 'PP0008-C'])
    .convert('pf60_CountryCode', lambda v: 'Lab', where=lambda r: r['Sample'] in ['PP0001-C', 'PP0003-C', 'PP0006-C', 'PP0007-C', 'PP0008-C'])
    .convert('pf60_CountryName', lambda v: 'Peru', where=lambda r: r['Sample'] in ['PP0012-C'])
    .convert('pf60_CountryCode', lambda v: 'PE', where=lambda r: r['Sample'] in ['PP0012-C'])
    .convert('pf60_CountryName', lambda v: 'Congo DR', where=lambda r: r['pf60_CountryName'] == 'Democratic Republic of Congo (Congo-Kinshasa)')
    .convert('pf60_CountryName', lambda v: 'Ivory Coast', where=lambda r: r['pf60_CountryName'] == 'Cote d\'Ivoire')
#     .convert('solaris_Year', lambda v, r: str(r['batch_arrived_year']), where=lambda r: (
#             r['batch_arrived_year'] is not None and
#             r['solaris_Year'] is not None and
#             r['batch_arrived_year'] < r['solaris_Year']), pass_row=True)
    .addfield('pf60_Year', lambda rec: str(rec['Year']))
    .addfield('pf60_Year_source', lambda rec: 'Olivo' if str(rec['Year']) is not None else '')
    .convert('pf60_Year', lambda v, r: study_years[r['pf60_AlfrescoStudyCode']], where=lambda r: r['pf60_AlfrescoStudyCode'] in study_years, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'study', where=lambda r: r['pf60_AlfrescoStudyCode'] in study_years, pass_row=True)
    .convert('pf60_Year', lambda v, r: 'Lab', where=lambda r: r['pf60_CountryCode'] == 'Lab', pass_row=True)
    .addfield('pf60_Date', lambda rec: str(rec['Date']))
    .convert('pf60_Year', lambda v, r: r['sis_Year_1093_Rob'], where=lambda r: r['sis_Year_1093_Rob'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1094_Rob'], where=lambda r: r['sis_Year_1094_Rob'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1095_Rob'], where=lambda r: r['sis_Year_1095_Rob'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1096_Rob'], where=lambda r: r['sis_Year_1096_Rob'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1097_Rob'], where=lambda r: r['sis_Year_1097_Rob'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1098_Rob'], where=lambda r: r['sis_Year_1098_Rob'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1100_Rob'], where=lambda r: r['sis_Year_1100_Rob'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1102_Rob'], where=lambda r: r['sis_Year_1102_Rob'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1103_Rob'], where=lambda r: r['sis_Year_1103_Rob'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1107_Rob'], where=lambda r: r['sis_Year_1107_Rob'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1136_Rob'], where=lambda r: r['sis_Year_1136_Rob'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1137_Rob'], where=lambda r: r['sis_Year_1137_Rob'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1044_Oct2012_NIH'], where=lambda r: r['sis_Year_1044_Oct2012_NIH'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1044_Oct2012_TRAC'], where=lambda r: r['sis_Year_1044_Oct2012_TRAC'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1044_Dec2012'], where=lambda r: r['sis_Year_1044_Dec2012'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1044_Jan2014'], where=lambda r: r['sis_Year_1044_Jan2014'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1101_Apr2013'], where=lambda r: r['sis_Year_1101_Apr2013'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1052_Sep2015'], where=lambda r: r['sis_Year_1052_Sep2015'] is not None, pass_row=True)
#     .convert('pf60_Year', lambda v, r: r['sis_Year_1136_Jun2015'], where=lambda r: r['sis_Year_1136_Jun2015'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1138_Mar2015'], where=lambda r: r['sis_Year_1138_Mar2015'] is not None, pass_row=True)
#     .convert('pf60_Year', lambda v, r: r['sis_Year_1137_Jul2015'], where=lambda r: r['sis_Year_1137_Jul2015'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1155_May2015'], where=lambda r: r['sis_Year_1155_May2015'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1134_May2015'], where=lambda r: r['sis_Year_1134_May2015'] is not None, pass_row=True)
#     .convert('pf60_Year', lambda v, r: r['sis_Year_1098_May2015'], where=lambda r: r['sis_Year_1098_May2015'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1062_Sep2013'], where=lambda r: r['sis_Year_1062_Sep2013'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1021_Apr2010'], where=lambda r: r['sis_Year_1021_Apr2010'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1044_Aug2015'], where=lambda r: r['sis_Year_1044_Aug2015'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1044_Jul2015'], where=lambda r: r['sis_Year_1044_Jul2015'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1141_Oct2015'], where=lambda r: r['sis_Year_1141_Oct2015'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1125_Nov2013'], where=lambda r: r['sis_Year_1125_Nov2013'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1127_Feb2014'], where=lambda r: r['sis_Year_1127_Feb2014'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1102_Nov2013'], where=lambda r: r['sis_Year_1102_Nov2013'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1102_Jan2014'], where=lambda r: r['sis_Year_1102_Jan2014'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1102_Apr2014'], where=lambda r: r['sis_Year_1102_Apr2014'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sis_Year_1155_Jun2013'], where=lambda r: r['sis_Year_1155_Jun2013'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['Lucas_Year'], where=lambda r: r['Lucas_Year'] is not None, pass_row=True)
    .convert('pf60_Year', lambda v, r: '2010', where=lambda r: r['pf60_OxfordSrcCode'] in ['PFD735', 'PFD736'], pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'Inferred', where=lambda r: r['pf60_OxfordSrcCode'] in ['PFD735', 'PFD736'], pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'Rob', where=lambda r: r['sis_Year_1093_Rob'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'Rob', where=lambda r: r['sis_Year_1094_Rob'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'Rob', where=lambda r: r['sis_Year_1095_Rob'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'Rob', where=lambda r: r['sis_Year_1096_Rob'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'Rob', where=lambda r: r['sis_Year_1097_Rob'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'Rob', where=lambda r: r['sis_Year_1098_Rob'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'Rob', where=lambda r: r['sis_Year_1100_Rob'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'Rob', where=lambda r: r['sis_Year_1102_Rob'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'Rob', where=lambda r: r['sis_Year_1103_Rob'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'Rob', where=lambda r: r['sis_Year_1107_Rob'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'Rob', where=lambda r: r['sis_Year_1136_Rob'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'Rob', where=lambda r: r['sis_Year_1137_Rob'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'SIS', where=lambda r: r['sis_Year_1044_Oct2012_NIH'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'SIS', where=lambda r: r['sis_Year_1044_Oct2012_TRAC'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'SIS', where=lambda r: r['sis_Year_1044_Dec2012'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'SIS', where=lambda r: r['sis_Year_1044_Jan2014'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'SIS', where=lambda r: r['sis_Year_1101_Apr2013'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'SIS', where=lambda r: r['sis_Year_1052_Sep2015'] is not None, pass_row=True)
#     .convert('pf60_Year_source', lambda v, r: 'SIS', where=lambda r: r['sis_Year_1136_Jun2015'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'SIS', where=lambda r: r['sis_Year_1138_Mar2015'] is not None, pass_row=True)
#     .convert('pf60_Year_source', lambda v, r: 'SIS',  where=lambda r: r['sis_Year_1137_Jul2015'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'SIS', where=lambda r: r['sis_Year_1155_May2015'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'SIS', where=lambda r: r['sis_Year_1134_May2015'] is not None, pass_row=True)
#     .convert('pf60_Year_source', lambda v, r: 'SIS', where=lambda r: r['sis_Year_1098_May2015'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'SIS', where=lambda r: r['sis_Year_1062_Sep2013'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'SIS', where=lambda r: r['sis_Year_1021_Apr2010'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'SIS', where=lambda r: r['sis_Year_1044_Aug2015'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'SIS', where=lambda r: r['sis_Year_1044_Jul2015'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'SIS', where=lambda r: r['sis_Year_1141_Oct2015'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'SIS', where=lambda r: r['sis_Year_1125_Nov2013'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'SIS', where=lambda r: r['sis_Year_1127_Feb2014'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'SIS', where=lambda r: r['sis_Year_1102_Nov2013'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'SIS', where=lambda r: r['sis_Year_1102_Jan2014'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'SIS', where=lambda r: r['sis_Year_1102_Apr2014'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'SIS', where=lambda r: r['sis_Year_1155_Jun2013'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'Lucas', where=lambda r: r['Lucas_Year'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1093_Rob'], where=lambda r: r['sis_Date_1093_Rob'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1094_Rob'], where=lambda r: r['sis_Date_1094_Rob'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1095_Rob'], where=lambda r: r['sis_Date_1095_Rob'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1096_Rob'], where=lambda r: r['sis_Date_1096_Rob'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1097_Rob'], where=lambda r: r['sis_Date_1097_Rob'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1098_Rob'], where=lambda r: r['sis_Date_1098_Rob'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1100_Rob'], where=lambda r: r['sis_Date_1100_Rob'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1102_Rob'], where=lambda r: r['sis_Date_1102_Rob'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1103_Rob'], where=lambda r: r['sis_Date_1103_Rob'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1107_Rob'], where=lambda r: r['sis_Date_1107_Rob'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1136_Rob'], where=lambda r: r['sis_Date_1136_Rob'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1137_Rob'], where=lambda r: r['sis_Date_1137_Rob'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1044_Oct2012_NIH'], where=lambda r: r['sis_Date_1044_Oct2012_NIH'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1044_Oct2012_TRAC'], where=lambda r: r['sis_Date_1044_Oct2012_TRAC'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1044_Dec2012'], where=lambda r: r['sis_Date_1044_Dec2012'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1044_Jan2014'], where=lambda r: r['sis_Date_1044_Jan2014'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1101_Apr2013'], where=lambda r: r['sis_Date_1101_Apr2013'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1052_Sep2015'], where=lambda r: r['sis_Date_1052_Sep2015'] is not None, pass_row=True)
#     .convert('pf60_Date', lambda v, r: r['sis_Date_1136_Jun2015'], where=lambda r: r['sis_Date_1136_Jun2015'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1138_Mar2015'], where=lambda r: r['sis_Date_1138_Mar2015'] is not None, pass_row=True)
#     .convert('pf60_Date', lambda v, r: r['sis_Date_1137_Jul2015'], where=lambda r: r['sis_Date_1137_Jul2015'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1155_May2015'], where=lambda r: r['sis_Date_1155_May2015'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1134_May2015'], where=lambda r: r['sis_Date_1134_May2015'] is not None, pass_row=True)
#     .convert('pf60_Date', lambda v, r: r['sis_Date_1098_May2015'], where=lambda r: r['sis_Date_1098_May2015'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1062_Sep2013'], where=lambda r: r['sis_Date_1062_Sep2013'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1021_Apr2010'], where=lambda r: r['sis_Date_1021_Apr2010'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1044_Aug2015'], where=lambda r: r['sis_Date_1044_Aug2015'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1044_Jul2015'], where=lambda r: r['sis_Date_1044_Jul2015'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1141_Oct2015'], where=lambda r: r['sis_Date_1141_Oct2015'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1125_Nov2013'], where=lambda r: r['sis_Date_1125_Nov2013'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1127_Feb2014'], where=lambda r: r['sis_Date_1127_Feb2014'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1102_Nov2013'], where=lambda r: r['sis_Date_1102_Nov2013'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1102_Jan2014'], where=lambda r: r['sis_Date_1102_Jan2014'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1102_Apr2014'], where=lambda r: r['sis_Date_1102_Apr2014'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sis_Date_1155_Jun2013'], where=lambda r: r['sis_Date_1155_Jun2013'] is not None, pass_row=True)
    .convert('pf60_Date', lambda v, r: r['Lucas_Date'], where=lambda r: r['Lucas_Date'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'elife', where=lambda r: (r['pf60_Year'] is None or r['pf60_Year'] == 'None' or r['pf60_Year'] == '-') and (r['elife_Year'] is not None), pass_row=True)
    .convert('pf60_Year', lambda v, r: r['elife_Year'], where=lambda r: (r['pf60_Year'] is None or r['pf60_Year'] == 'None' or r['pf60_Year'] == '-') and (r['elife_Year'] is not None), pass_row=True)
    .convert('pf60_Date', lambda v, r: r['elife_Year'], where=lambda r: (r['pf60_Date'] is None or r['pf60_Date'] in ['None', 'N/A', '-', 'not indicated']) and (r['elife_Year'] is not None), pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'sampling_date', where=lambda r: (
            (r['pf60_Year'] is None or r['pf60_Year'] == 'None' or r['pf60_Year'] == '-') and
            r['sampling_Year'] is not None and
            r['sampling_Year'] != 'NULL' and
            r['batch_arrived_year'] >= r['sampling_Year']), pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sampling_Year'], where=lambda r: (
            (r['pf60_Year'] is None or r['pf60_Year'] == 'None' or r['pf60_Year'] == '-') and
            r['sampling_Year'] is not None and
            r['sampling_Year'] != 'NULL' and
            r['batch_arrived_year'] >= r['sampling_Year']), pass_row=True)
    .convert('pf60_Date', lambda v, r: r['sampling_date'], where=lambda r: (
            (r['pf60_Date'] is None or r['pf60_Date'] in ['None', 'N/A', '-', 'not indicated']) and
            r['sampling_date'] is not None and
            r['sampling_date'] != 'NULL' and
            r['batch_arrived'] >= r['sampling_date']), pass_row=True)
    .convert('pf60_Year_source', lambda v: 'Lab', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1133-PF-LAB-MERRICK')
    .convert('pf60_Year', lambda v: 'Lab', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1133-PF-LAB-MERRICK')
    .convert('pf60_Date', lambda v: 'Lab', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1133-PF-LAB-MERRICK')
    .convert('pf60_Year', lambda v, r: ox_code_year[r['Sample']], where=lambda r: r['Sample'] in ox_code_year, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'duplicate', where=lambda r: r['Sample'] in ox_code_year, pass_row=True)
    .convert('pf60_Year', lambda v, r: r['sampling_Year'], where=lambda r: r['pf60_AlfrescoStudyCode'] == '1044-PF-KH-FAIRHURST' and r['pf60_Year_source'] =='Olivo' and r['sampling_Year'] != 'NULL', pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'sampling_date', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1044-PF-KH-FAIRHURST' and r['pf60_Year_source'] =='Olivo' and r['sampling_Year'] != 'NULL', pass_row=True)
    .convert('pf60_Year', lambda v, r: r['elife_Year'], where=lambda r: r['pf60_AlfrescoStudyCode'] == '1044-PF-KH-FAIRHURST' and r['pf60_Year_source'] =='Olivo' and r['elife_Year'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'elife', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1044-PF-KH-FAIRHURST' and r['pf60_Year_source'] =='Olivo' and r['elife_Year'] is not None, pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'inferred', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1127-PF-ML-SOULEYMANE' and r['pf60_Year'] == '-', pass_row=True)
    .convert('pf60_Year', lambda v, r: '2013', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1127-PF-ML-SOULEYMANE' and r['pf60_Year'] == '-', pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'inferred', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1135-PF-SN-CONWAY', pass_row=True)
    .convert('pf60_Year', lambda v, r: '2013', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1135-PF-SN-CONWAY' and r['pf60_OxfordDonorCode'].endswith('13'), pass_row=True)
    .convert('pf60_Year', lambda v, r: '2014', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1135-PF-SN-CONWAY' and r['pf60_OxfordDonorCode'].endswith('14'), pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'inferred', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1155-PF-ID-PRICE' and r['pf60_OxfordSrcCode'].startswith('UNKNOWN_'), pass_row=True)
    .convert('pf60_Year', lambda v, r: '2011†', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1155-PF-ID-PRICE' and r['pf60_OxfordSrcCode'].startswith('UNKNOWN_'), pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'inferred', where=lambda r: r['pf60_Year'] == 'N/A' and r['pf60_AlfrescoStudyCode'] == '1062-PF-PG-BARRY' and r['pf60_OxfordSrcCode'].startswith('YSA_0'), pass_row=True)
    .convert('pf60_Year', lambda v, r: '2013', where=lambda r: r['pf60_Year'] == 'N/A' and r['pf60_AlfrescoStudyCode'] == '1062-PF-PG-BARRY' and r['pf60_OxfordSrcCode'].startswith('YSA_0'), pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'inferred', where=lambda r: r['pf60_Year'] == 'N/A' and r['pf60_AlfrescoStudyCode'] == '1062-PF-PG-BARRY' and r['pf60_OxfordSrcCode'].startswith('YSM_0'), pass_row=True)
    .convert('pf60_Year', lambda v, r: '2012', where=lambda r: r['pf60_Year'] == 'N/A' and r['pf60_AlfrescoStudyCode'] == '1062-PF-PG-BARRY' and r['pf60_OxfordSrcCode'].startswith('YSM_0'), pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'inferred', where=lambda r: r['pf60_Year'] == '-' and r['pf60_AlfrescoStudyCode'] == '1062-PF-PG-BARRY' and r['pf60_OxfordSrcCode'].startswith('YSM_1'), pass_row=True)
    .convert('pf60_Year', lambda v, r: '2013', where=lambda r: r['pf60_Year'] == '-' and r['pf60_AlfrescoStudyCode'] == '1062-PF-PG-BARRY' and r['pf60_OxfordSrcCode'].startswith('YSM_1'), pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'inferred', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1083-PF-GH-CONWAY' and r['pf60_OxfordSrcCode'] >= 'EIMK002' and r['pf60_OxfordSrcCode'] <= 'EIMK020', pass_row=True)
    .convert('pf60_Year', lambda v, r: '2011', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1083-PF-GH-CONWAY' and r['pf60_OxfordSrcCode'] >= 'EIMK002' and r['pf60_OxfordSrcCode'] <= 'EIMK020', pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'inferred', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1083-PF-GH-CONWAY' and r['pf60_OxfordSrcCode'] >= 'EIMK077' and r['pf60_OxfordSrcCode'] <= 'EIMK293', pass_row=True)
    .convert('pf60_Year', lambda v, r: '2012', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1083-PF-GH-CONWAY' and r['pf60_OxfordSrcCode'] >= 'EIMK077' and r['pf60_OxfordSrcCode'] <= 'EIMK293', pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'inferred', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1083-PF-GH-CONWAY' and r['pf60_OxfordSrcCode'] >= 'EIMK356' and r['pf60_OxfordSrcCode'] <= 'EIMK388', pass_row=True)
    .convert('pf60_Year', lambda v, r: '2013', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1083-PF-GH-CONWAY' and r['pf60_OxfordSrcCode'] >= 'EIMK356' and r['pf60_OxfordSrcCode'] <= 'EIMK388', pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'inferred', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1083-PF-GH-CONWAY' and r['pf60_OxfordSrcCode'].startswith('EIMN'), pass_row=True)
    .convert('pf60_Year', lambda v, r: '2012', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1083-PF-GH-CONWAY' and r['pf60_OxfordSrcCode'].startswith('EIMN'), pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'inferred', where=lambda r: r['pf60_Year'] in ['-', None] and r['pf60_AlfrescoStudyCode'] == '1098-PF-ET-GOLASSA' and r['pf60_OxfordSrcCode'][0] in ['A', 'B', 'I', 'J', 'M'], pass_row=True)
    .convert('pf60_Year', lambda v, r: '2013', where=lambda r: r['pf60_Year'] in ['-', None] and r['pf60_AlfrescoStudyCode'] == '1098-PF-ET-GOLASSA' and r['pf60_OxfordSrcCode'][0] in ['A', 'B', 'I', 'J', 'M'], pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'inferred', where=lambda r: r['pf60_Year'] == '-' and r['pf60_AlfrescoStudyCode'] == '1020-PF-VN-BONI', pass_row=True)
    .convert('pf60_Year', lambda v, r: '2009', where=lambda r: r['pf60_Year'] == '-' and r['pf60_AlfrescoStudyCode'] == '1020-PF-VN-BONI', pass_row=True)
    .convert('pf60_Year_source', lambda v, r: 'inferred', where=lambda r: r['pf60_Year'] == 'N/A' and r['pf60_AlfrescoStudyCode'] == '1137-PF-GM-DALESSANDRO', pass_row=True)
    .convert('pf60_Year', lambda v, r: '2013', where=lambda r: r['pf60_Year'] == 'N/A' and r['pf60_AlfrescoStudyCode'] == '1137-PF-GM-DALESSANDRO', pass_row=True)
    .convert('pf60_Date', lambda v, r: '23/06/2011', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1155-PF-ID-PRICE' and r['pf60_OxfordSrcCode'] == 'UFM_27_RECODED', pass_row=True)
    .convert('pf60_Year', lambda v, r: '2011', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1155-PF-ID-PRICE' and r['pf60_OxfordSrcCode'] == 'UFM_27_RECODED', pass_row=True)
    .convert('pf60_Date', lambda v, r: '07/03/2012', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1155-PF-ID-PRICE' and r['pf60_OxfordSrcCode'] == 'UNKNOWN_UFC_65_RECODED', pass_row=True)
    .convert('pf60_Year', lambda v, r: '2012', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1155-PF-ID-PRICE' and r['pf60_OxfordSrcCode'] == 'UNKNOWN_UFC_65_RECODED', pass_row=True)
#     .convert('pf60_Year_source', lambda v, r: 'batch_arrived_year', where=lambda r: r['pf60_Year'] is None or r['pf60_Year'] in ['None', 'N/A', '-'], pass_row=True)
#     .convert('pf60_Year', lambda v, r: r['batch_arrived_year'], where=lambda r: r['pf60_Year'] is None or r['pf60_Year'] in ['None', 'N/A', '-'], pass_row=True)
#     .convert('pf60_Date', lambda v, r: r['batch_arrived'], where=lambda r: r['pf60_Date'] is None or r['pf60_Date'] in ['None', 'N/A', '-', 'not indicated'], pass_row=True)
    .addfield('pf60_SubContinentCode', lambda rec: SubContinentCode_lkp[rec['pf60_CountryName']])
    .convert('pf60_SubContinentCode', lambda v, r: r['SubContinentCode'], where=lambda r: r['pf60_SubContinentCode'] == '?', pass_row=True)
    .convert('pf60_SubContinentCode', lambda v, r: 'WSEA', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1010-PF-TH-ANDERSON' and r['pf60_SubContinentCode'] is None, pass_row=True)
    .convert('pf60_SubContinentCode', lambda v, r: 'WSEA', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1125-PF-TH-NOSTEN' and r['pf60_SubContinentCode'] is None, pass_row=True)
    .addfield('pf60_SubContinentName', lambda rec: SubContinentName_lkp[rec['pf60_SubContinentCode']])
    .addfield('pf60_Location', lambda rec: rec['Location'])
    .convert('pf60_Location', lambda v, r: r['sis_Location_1044_Jul2015'], where=lambda r: r['pf60_AlfrescoStudyCode'] == '1044-PF-KH-FAIRHURST' and (r['pf60_Location'] is None or r['pf60_Location'] in ['None', '-', '?', 'N/A']) , pass_row=True)
    .convert('pf60_Location', lambda v, r: r['sis_Location_1044_Aug2015'], where=lambda r: r['pf60_AlfrescoStudyCode'] == '1044-PF-KH-FAIRHURST' and (r['pf60_Location'] is None or r['pf60_Location'] in ['None', '-', '?', 'N/A']), pass_row=True)
    .convert('pf60_Location', lambda v, r: r['sis_Location_1044_Oct2012_NIH'], where=lambda r: r['pf60_AlfrescoStudyCode'] == '1044-PF-KH-FAIRHURST' and (r['pf60_Location'] is None or r['pf60_Location'] in ['None', '-', '?', 'N/A']), pass_row=True)
    .convert('pf60_Location', lambda v, r: r['sis_Location_1044_Oct2012_TRAC'], where=lambda r: r['pf60_AlfrescoStudyCode'] == '1044-PF-KH-FAIRHURST' and (r['pf60_Location'] is None or r['pf60_Location'] in ['None', '-', '?', 'N/A']), pass_row=True)
    .convert('pf60_Location', lambda v, r: r['sis_Location_1044_Jan2014'], where=lambda r: r['pf60_AlfrescoStudyCode'] == '1044-PF-KH-FAIRHURST' and (r['pf60_Location'] is None or r['pf60_Location'] in ['None', '-', '?', 'N/A']), pass_row=True)
    .convert('pf60_Location', lambda v, r: r['sis_Location_1141_Oct2015'], where=lambda r: r['pf60_AlfrescoStudyCode'] == '1141-PF-GM-CLAESSENS' and (r['pf60_Location'] is None or r['pf60_Location'] in ['None', '-', '?', 'N/A']), pass_row=True)
    .convert('pf60_Location', lambda v, r: r['sis_Location_1098_Oct2016'], where=lambda r: r['pf60_AlfrescoStudyCode'] == '1098-PF-ET-GOLASSA' and (r['pf60_Location'] is None or r['pf60_Location'] in ['None', '-', '?', 'N/A']), pass_row=True)
    .convert('pf60_Location', lambda v, r: r['sis_Location_1127_Feb2014'], where=lambda r: r['pf60_AlfrescoStudyCode'] == '1127-PF-ML-SOULEYMANE' and (r['pf60_Location'] is None or r['pf60_Location'] in ['None', '-', '?', 'N/A']), pass_row=True)
    .convert('pf60_Location', lambda v, r: r['sis_Location_1134_Feb2015'], where=lambda r: r['pf60_AlfrescoStudyCode'] in ['1134-PF-ML-CONWAY', '1135-PF-SN-CONWAY'] and (r['pf60_Location'] is None or r['pf60_Location'] in ['None', '-', '?', 'N/A']), pass_row=True)
    .convert('pf60_Location', lambda v, r: r['sis_Location_1135_May2015'], where=lambda r: r['pf60_AlfrescoStudyCode'] == '1135-PF-SN-CONWAY' and (r['pf60_Location'] is None or r['pf60_Location'] in ['None', '-', '?', 'N/A']), pass_row=True)
    .convert('pf60_Location', lambda v, r: r['sis_Location_1147_Jul2015'], where=lambda r: r['pf60_AlfrescoStudyCode'] == '1147-PF-MR-CONWAY' and (r['pf60_Location'] is None or r['pf60_Location'] in ['None', '-', '?', 'N/A']), pass_row=True)
    .convert('pf60_Location', lambda v, r: r['sis_Location_1102_Nov2013'], where=lambda r: r['sis_Location_1102_Nov2013'] is not None, pass_row=True)
    .convert('pf60_Location', lambda v, r: r['sis_Location_1102_Jan2014'], where=lambda r: r['sis_Location_1102_Jan2014'] is not None, pass_row=True)
    .convert('pf60_Location', lambda v, r: r['sis_Location_1102_Apr2014'], where=lambda r: r['sis_Location_1102_Apr2014'] is not None, pass_row=True)
    .convert('pf60_Location', lambda v, r: r['sis_Location_1134_May2015'], where=lambda r: r['pf60_AlfrescoStudyCode'] in ['1134-PF-ML-CONWAY', '1135-PF-SN-CONWAY'] and (r['pf60_Location'] is None or r['pf60_Location'] in ['None', '-', '?', 'N/A']), pass_row=True)
#     .convert('pf60_Location', lambda v, r: 'Pursat', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1044-PF-KH-FAIRHURST' and r['pf60_Location'] is None, pass_row=True) # Manually checked and all these appeared to be in Chanaki spreadsheet, but with _CF11 appended to source code
    .convert('pf60_Location', lambda v, r: 'Preah Vihear', where=lambda r: r['pf60_OxfordSrcCode'] in ['163-KH2-039', 'KH002-106'], pass_row=True) # Manually checked and all this appear to be in 1044_Jan2014 spreadsheet, but different sheets
    .convert('pf60_Location', lambda v, r: 'Pursat', where=lambda r: r['pf60_Location'] == 'Pursat ', pass_row=True) 
    .convert('pf60_Location', lambda v, r: 'Bobo-Dioulasso', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1004-PF-BF-OUEDRAOGO' and r['pf60_Location'] is None, pass_row=True)
#     .convert('pf60_Location', lambda v, r: 'Pursat', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1011-PF-KH-SU' and r['pf60_Location'] is None, pass_row=True)
    .convert('pf60_Location', lambda v, r: 'Papua', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1155-PF-ID-PRICE' and r['pf60_Location'] in [None, 'None', '-', '?', 'N/A'], pass_row=True)
    .convert('pf60_Location', lambda v, r: 'Kilifi', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1015-PF-KE-NZILA' and r['pf60_Location'] is None, pass_row=True)
    .convert('pf60_Location', lambda v, r: 'Bamako', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1127-PF-ML-SOULEYMANE' and r['pf60_Location'] is None, pass_row=True) # Manually checked and these appeared on upload tab
    .convert('pf60_Location', lambda v, r: 'Lab', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1133-PF-LAB-MERRICK' and r['pf60_Location'] is None, pass_row=True)
    .convert('pf60_Location', lambda v, r: 'Faladje', where=lambda r: r['pf60_Location'] == 'Falaje', pass_row=True) 
    .convert('pf60_Location', lambda v, r: 'Faladje', where=lambda r: r['pf60_Location'] == 'Faladie', pass_row=True) 
    .convert('pf60_Location', lambda v, r: 'Buea', where=lambda r: r['pf60_Location'] == 'Buea Town', pass_row=True) 
    .convert('pf60_Location', lambda v, r: 'Pursat', where=lambda r: r['pf60_Location'] == None and r['pf60_AlfrescoStudyCode'] == '1044-PF-KH-FAIRHURST' and 'KH1' in r['pf60_OxfordSrcCode'], pass_row=True)
    .addfield('Site', lambda rec: rec['pf60_Location'])
    .convert('Site', lambda v, r: location_sites[r['pf60_Location']], where=lambda r: r['pf60_Location'] in location_sites, pass_row=True)
    .convert('Site', lambda v, r: study_sites[r['pf60_AlfrescoStudyCode']], where=lambda r: r['pf60_AlfrescoStudyCode'] in study_sites, pass_row=True)
    .convert('Site', lambda v, r: source_code_sites[r['pf60_OxfordSrcCode']], where=lambda r: r['pf60_OxfordSrcCode'] in source_code_sites, pass_row=True)
    .convert('Site', lambda v, r: 'Chikwawa', where=lambda r: r['Site'] == None and r['pf60_AlfrescoStudyCode'] == '1022-PF-MW-OCHOLLA' and r['pf60_OxfordSrcCode'].startswith('H'), pass_row=True)
    .convert('Site', lambda v, r: 'Zomba', where=lambda r: r['Site'] == None and r['pf60_AlfrescoStudyCode'] == '1022-PF-MW-OCHOLLA' and r['pf60_OxfordSrcCode'].startswith('Z'), pass_row=True)
    .convert('Site', lambda v, r: 'Faranah', where=lambda r: r['Site'] == None and r['pf60_AlfrescoStudyCode'] == '1026-PF-GN-CONWAY' and r['pf60_OxfordSrcCode'].startswith('G'), pass_row=True)
    .convert('Site', lambda v, r: 'Nzerekore', where=lambda r: r['Site'] == None and r['pf60_AlfrescoStudyCode'] == '1026-PF-GN-CONWAY' and r['pf60_OxfordSrcCode'].startswith('Z'), pass_row=True)
    .convert('Site', lambda v, r: 'Pursat', where=lambda r: r['Site'] == None and r['pf60_AlfrescoStudyCode'] == '1044-PF-KH-FAIRHURST' and 'KH1' in r['pf60_OxfordSrcCode'], pass_row=True)
    .convert('Site', lambda v, r: 'West Arsi Zone', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1098-PF-ET-GOLASSA' and r['pf60_OxfordSrcCode'][0] in ['A', 'B', 'I', 'J', 'M'], pass_row=True)
    .convert('Site', lambda v, r: 'Lab', where=lambda r: r['pf60_CountryCode'] == 'Lab', pass_row=True)
#     .convert('Site', lambda v, r: 'Pursat', where=lambda r: r['Site'] == None and r['Sample'] in pursat_samples, pass_row=True)
    .convert('Site', lambda v, r: '%s returning traveller' % r['pf60_CountryName'], where=lambda r: r['pf60_AlfrescoStudyCode'] == '1014-PF-SSA-SUTHERLAND', pass_row=True)
    .addfield('pf60_RegionCode', lambda rec: RegionCode_lkp[rec['pf60_CountryName']])
    .convert('pf60_RegionCode', lambda v, r: r['RegionCode'], where=lambda r: r['pf60_RegionCode'] == '?', pass_row=True)
    .convert('pf60_RegionCode', lambda v, r: 'WKH', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1011-PF-KH-SU' and r['pf60_RegionCode'] is None, pass_row=True)
    .convert('pf60_RegionCode', lambda v, r: 'WTH', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1125-PF-TH-NOSTEN' and r['pf60_RegionCode'] is None, pass_row=True)
    .convert('pf60_RegionCode', lambda v, r: 'WTH', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1010-PF-TH-ANDERSON' and r['pf60_RegionCode'] is None, pass_row=True)
    .convert('pf60_RegionCode', lambda v, r: 'NEKH', where=lambda r: r['pf60_Location'] == 'Ratanakiri' and r['pf60_RegionCode'] is None, pass_row=True)
    .convert('pf60_RegionCode', lambda v, r: 'NKH', where=lambda r: r['pf60_Location'] in ['Preah Vihear', 'Preah Vihear '] and r['pf60_RegionCode'] is None, pass_row=True)
    .convert('pf60_RegionCode', lambda v, r: 'WKH', where=lambda r: r['pf60_Location'] in ['Pursat', 'Pursat '] and r['pf60_RegionCode'] is None, pass_row=True)
    .convert('pf60_Type', lambda v, r: 'sWGA', where=lambda r: r['pf60_AlfrescoStudyCode'] == '1152-PF-DBS-GH-AMENGA-ETEGO', pass_row=True)
    .convert('pf60_Type', lambda v, r: 'sWGA', where=lambda r: r['Sample'] in swga_samples, pass_row=True)
    .convert('pf60_Year', lambda v, r: '2011†', where=lambda r: r['pf60_Year'] == '2011† ', pass_row=True)
    .convert('pf60_Year', lambda v, r: '-', where=lambda r: r['pf60_Year'] in [None, 'None', '', '?', 'N/A'], pass_row=True)
    .convert('Site', lambda v, r: '-', where=lambda r: r['Site'] in [None, 'None', '', '?'], pass_row=True)
)
print(len(tbl_panoptes_samples.data()))
print(len(tbl_panoptes_samples.distinct('Sample').data()))
tbl_panoptes_samples.tail()

/Users/rpearson/miniconda3/envs/biipy/lib/python3.5/site-packages/openpyxl/workbook/names/named_range.py:125: UserWarning: Discarded range with reserved name
  warnings.warn("Discarded range with reserved name")

7182
7182

+------+-------------+---------------+-----------------+-----------------------+-----------------------+-------+------------------+------+-------+------------------+------------------+------------+-------------+-------------+----------+------+------+--------------+--------------------+------------------+----------------+---------------+---------------+-----------------------+--------------+---------------+--------------------+------------+--------------------+----------------------+------------------------+-----------+-------------+-----------+-----------+------------------+------------------+---------------+-------------------+-------------------------+------------------------+-------------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-------------------------------+--------------------------------+---------------------------+---------------------------+---------------------------+---------------------------+---------------------------+---------------------------+---------------------------+---------------------------+---------------------------+---------------------------+---------------------------+---------------------------+---------------------------+------------------------+------------+------------+---------------------------+---------------------------+----------------------------+----------------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+--------------------------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+---------------------------------------+-----------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-----------+------------------+---------------------------------------+-----------------------+-----------------------+---------------+----------+-----------------+
| Num  | Sample      | OxfordSrcCode | OxfordDonorCode | AlfrescoStudyCode     | Study                 | Type  | NotAmplified     | InV5 | InV4  | SubContinentCode | SubContinentName | RegionCode | CountryCode | CountryName | Location | Year | Date | HasDuplicate | DiscardAsDuplicate | ManuallyExcluded | run_accessions | sampling_date | sampling_Year | arrival_date          | arrival_Year | batch_arrived | batch_arrived_year | elife_Year | pf60_OxfordSrcCode | pf60_OxfordDonorCode | pf60_AlfrescoStudyCode | pf60_Type | pf60_InV5.1 | pf60_InV5 | pf60_InV4 | pf60_CountryCode | pf60_CountryName | Individual_ID | pf60_HasDuplicate | pf60_DiscardAsDuplicate | pc_pass_missing        | pc_genome_covered_at_1x | sis_Location_1093_Rob | sis_Location_1094_Rob | sis_Location_1095_Rob | sis_Location_1096_Rob | sis_Location_1097_Rob | sis_Location_1098_Rob | sis_Location_1100_Rob | sis_Location_1102_Rob | sis_Location_1103_Rob | sis_Location_1107_Rob | sis_Location_1136_Rob | sis_Location_1137_Rob | sis_Location_1044_Oct2012_NIH | sis_Location_1044_Oct2012_TRAC | sis_Location_1044_Jan2014 | sis_Location_1044_Jul2015 | sis_Location_1044_Aug2015 | sis_Location_1141_Oct2015 | sis_Location_1098_Oct2016 | sis_Location_1127_Feb2014 | sis_Location_1134_Feb2015 | sis_Location_1135_May2015 | sis_Location_1147_Jul2015 | sis_Location_1102_Nov2013 | sis_Location_1102_Jan2014 | sis_Location_1102_Apr2014 | sis_Location_1134_May2015 | sort_AlfrescoStudyCode | Lucas_Date | Lucas_Year | sis_Date_1044_Oct2012_NIH | sis_Year_1044_Oct2012_NIH | sis_Date_1044_Oct2012_TRAC | sis_Year_1044_Oct2012_TRAC | sis_Date_1044_Dec2012 | sis_Year_1044_Dec2012 | sis_Date_1044_Jan2014 | sis_Year_1044_Jan2014 | sis_Date_1101_Apr2013 | sis_Year_1101_Apr2013 | sis_Date_1052_Sep2015 | sis_Year_1052_Sep2015 | sis_Date_1138_Mar2015 | sis_Year_1138_Mar2015 | sis_Date_1155_May2015                | sis_Year_1155_May2015 | sis_Date_1134_May2015 | sis_Year_1134_May2015 | sis_Date_1062_Sep2013 | sis_Year_1062_Sep2013 | sis_Date_1021_Apr2010 | sis_Year_1021_Apr2010 | sis_Date_1044_Aug2015 | sis_Year_1044_Aug2015 | sis_Date_1044_Jul2015 | sis_Year_1044_Jul2015 | sis_Date_1141_Oct2015 | sis_Year_1141_Oct2015 | sis_Date_1125_Nov2013 | sis_Year_1125_Nov2013 | sis_Date_1098_Oct2016 | sis_Year_1098_Oct2016 | sis_Date_1127_Feb2014 | sis_Year_1127_Feb2014 | sis_Date_1134_Feb2015 | sis_Year_1134_Feb2015 | sis_Date_1135_May2015 | sis_Year_1135_May2015 | sis_Date_1147_Jul2015 | sis_Year_1147_Jul2015 | sis_Date_1102_Nov2013 | sis_Year_1102_Nov2013 | sis_Date_1102_Jan2014 | sis_Year_1102_Jan2014 | sis_Date_1102_Apr2014 | sis_Year_1102_Apr2014 | sis_Date_1155_Jun2013                 | sis_Year_1155_Jun2013 | sis_Date_1093_Rob | sis_Year_1093_Rob | sis_Date_1094_Rob | sis_Year_1094_Rob | sis_Date_1095_Rob | sis_Year_1095_Rob | sis_Date_1096_Rob | sis_Year_1096_Rob | sis_Date_1097_Rob | sis_Year_1097_Rob | sis_Date_1098_Rob | sis_Year_1098_Rob | sis_Date_1100_Rob | sis_Year_1100_Rob | sis_Date_1102_Rob | sis_Year_1102_Rob | sis_Date_1103_Rob | sis_Year_1103_Rob | sis_Date_1107_Rob | sis_Year_1107_Rob | sis_Date_1136_Rob | sis_Year_1136_Rob | sis_Date_1137_Rob | sis_Year_1137_Rob | pf60_Year | pf60_Year_source | pf60_Date                             | pf60_SubContinentCode | pf60_SubContinentName | pf60_Location | Site     | pf60_RegionCode |
+======+=============+===============+=================+=======================+=======================+=======+==================+======+=======+==================+==================+============+=============+=============+==========+======+======+==============+====================+==================+================+===============+===============+=======================+==============+===============+====================+============+====================+======================+========================+===========+=============+===========+===========+==================+==================+===============+===================+=========================+========================+=========================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+===============================+================================+===========================+===========================+===========================+===========================+===========================+===========================+===========================+===========================+===========================+===========================+===========================+===========================+===========================+========================+============+============+===========================+===========================+============================+============================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+======================================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================+=======================================+=======================+===================+===================+===================+===================+===================+===================+===================+===================+===================+===================+===================+===================+===================+===================+===================+===================+===================+===================+===================+===================+===================+===================+===================+===================+===========+==================+=======================================+=======================+=======================+===============+==========+=================+
| 3672 | 'PJ0137-Cx' | 'UFM_42'      | 'UFM_42'        | '1106-PV-MULTI-PRICE' | '1106-PV-MULTI-PRICE' | 'dna' | 'FromSampleCode' | True | True  | 'OCE'            | 'Oceania'        | 'ID'       | 'ID'        | 'Indonesia' | 'Papua'  | '-'  | '-'  | False        | False              | False            | 'NULL'         | '2011-08-08'  | '2011'        | '2013-11-27 00:00:00' | '2013'       | '27 Nov 2013' | '2013'             | '2011†'    | 'UFM_42'           | 'UFM_42'             | '1155-PF-ID-PRICE'     | 'DNA'     | True        | True      | True      | 'ID'             | 'Indonesia'      | 'UFM_42'      | False             | False                   | '0.02940740217544851'  | '0.9927'                | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                          | None                           | None                      | None                      | None                      | None                      | None                      | None                      | None                      | None                      | None                      | None                      | None                      | None                      | None                      | '1155-PF-ID-PRICE'     | None       | None       | None                      | None                      | None                       | None                       | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                                 | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | datetime.datetime(2011, 10, 11, 0, 0) | '2011'                | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | '2011'    | 'SIS'            | datetime.datetime(2011, 10, 11, 0, 0) | 'OCE'                 | 'Oceania'             | 'Papua'       | 'Timika' | 'ID'            |
+------+-------------+---------------+-----------------+-----------------------+-----------------------+-------+------------------+------+-------+------------------+------------------+------------+-------------+-------------+----------+------+------+--------------+--------------------+------------------+----------------+---------------+---------------+-----------------------+--------------+---------------+--------------------+------------+--------------------+----------------------+------------------------+-----------+-------------+-----------+-----------+------------------+------------------+---------------+-------------------+-------------------------+------------------------+-------------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-------------------------------+--------------------------------+---------------------------+---------------------------+---------------------------+---------------------------+---------------------------+---------------------------+---------------------------+---------------------------+---------------------------+---------------------------+---------------------------+---------------------------+---------------------------+------------------------+------------+------------+---------------------------+---------------------------+----------------------------+----------------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+--------------------------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+-----------------------+---------------------------------------+-----------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-----------+------------------+---------------------------------------+-----------------------+-----------------------+---------------+----------+-----------------+
| 3673 | 'PJ0138-Cx' | 'UFM_44'      | 'UFM_44'        | '1106-PV-MULTI-PRICE' | '1106-PV-MULTI-PRICE' | 'dna' | 'FromSampleCode' | True | True  | 'OCE'            | 'Oceania'        | 'ID'       | 'ID'        | 'Indonesia' | 'Papua'  | '-'  | '-'  | False        | False              | False            | 'NULL'         | '2011-10-11'  | '2011'        | '2013-11-27 00:00:00' | '2013'       | '27 Nov 2013' | '2013'             | '2011†'    | 'UFM_44'           | 'UFM_44'             | '1155-PF-ID-PRICE'     | 'DNA'     | True        | True      | True      | 'ID'             | 'Indonesia'      | 'UFM_44'      | False             | False                   | '0.02528188367643093'  | '0.9913'                | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                          | None                           | None                      | None                      | None                      | None                      | None                      | None                      | None                      | None                      | None                      | None                      | None                      | None                      | None                      | '1155-PF-ID-PRICE'     | None       | None       | None                      | None                      | None                       | None                       | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                                 | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | None                  | datetime.datetime(2011, 10, 13, 0, 0) | '2011'                | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | None              | '2011'    | 'SIS'            | datetime.datetime(2011, 10, 13, 0, 0) | 'OCE'                 | 'Oceania'             | 'Papua'       | 'Timika' | 'ID'            |

In [208]:
tbl_panoptes_samples.totsv(panoptes_metadata_fn, lineterminator='\n')

# Location by study

In [209]:
(
    tbl_panoptes_samples
    .valuecounts('pf60_AlfrescoStudyCode', 'pf60_InV5', 'pf60_CountryName', 'pf60_Location', 'Site')
    .sort(['pf60_AlfrescoStudyCode', 'pf60_InV5', 'pf60_CountryName', 'pf60_Location', 'Site'])
    .toxlsx('%s/location_by_study_20160123.xlsx' % output_dir)
)

# Year by study

In [210]:
(
    tbl_panoptes_samples
    .valuecounts('pf60_AlfrescoStudyCode', 'pf60_InV5', 'pf60_Year')
    .sort(['pf60_AlfrescoStudyCode', 'pf60_InV5', 'pf60_Year'])
    .toxlsx('%s/year_by_study_20160123.xlsx' % output_dir)
)

# Determining duplicates

In [211]:
(
    tbl_panoptes_samples
    .sort(['pf60_AlfrescoStudyCode', 'Individual_ID', 'pf60_OxfordSrcCode', 'Sample'])
    .cut(['pf60_AlfrescoStudyCode', 'Individual_ID', 'pf60_OxfordDonorCode', 'pf60_OxfordSrcCode', 'Sample',
          'Site', 'pf60_Year', 'pf60_Date', 'pf60_Year_source', 'pf60_DiscardAsDuplicate', 'pf60_HasDuplicate'])
    .toxlsx('%s/samples_sorted_donorcode_20160123.xlsx' % output_dir)
)

In [212]:
(
    tbl_panoptes_samples
    .sort(['pf60_AlfrescoStudyCode', 'pf60_OxfordSrcCode', 'Individual_ID', 'Sample'])
    .cut(['pf60_AlfrescoStudyCode', 'Individual_ID', 'pf60_OxfordDonorCode', 'pf60_OxfordSrcCode', 'Sample',
          'Site', 'pf60_Year', 'pf60_Date', 'pf60_Year_source', 'pf60_DiscardAsDuplicate', 'pf60_HasDuplicate'])
    .toxlsx('%s/samples_sorted_srccode_20160123.xlsx' % output_dir)
)

In [213]:
(
    tbl_panoptes_samples
    .sort(['pf60_AlfrescoStudyCode', 'Sample', 'Individual_ID', 'pf60_OxfordSrcCode'])
    .cut(['pf60_AlfrescoStudyCode', 'Sample', 'Individual_ID', 'pf60_OxfordDonorCode', 'pf60_OxfordSrcCode',
          'Site', 'pf60_Year', 'pf60_Date', 'pf60_Year_source', 'pf60_DiscardAsDuplicate', 'pf60_HasDuplicate'])
    .toxlsx('%s/samples_sorted_oxcode_20160123.xlsx' % output_dir)
)

# Create final table

In [214]:
dict(final_columns)

{'Individual_ID': 'Individual_ID',
 'Sample': 'Sample',
 'Site': 'Site',
 'pc_genome_covered_at_1x': 'pc_genome_covered_at_1x',
 'pc_pass_missing': 'pc_pass_missing',
 'pf60_AlfrescoStudyCode': 'AlfrescoStudyCode',
 'pf60_CountryCode': 'CountryCode',
 'pf60_CountryName': 'CountryName',
 'pf60_Date': 'Date',
 'pf60_DiscardAsDuplicate': 'DiscardAsDuplicate',
 'pf60_HasDuplicate': 'HasDuplicate',
 'pf60_InV5': 'InV5',
 'pf60_InV5.1': 'InV5.1',
 'pf60_OxfordDonorCode': 'OxfordDonorCode',
 'pf60_OxfordSrcCode': 'OxfordSrcCode',
 'pf60_RegionCode': 'RegionCode',
 'pf60_SubContinentCode': 'SubContinentCode',
 'pf60_SubContinentName': 'SubContinentName',
 'pf60_Type': 'Type',
 'pf60_Year': 'Year',
 'pf60_Year_source': 'Year_source',
 'run_accessions': 'run_accessions'}

In [215]:
tbl_panoptes_samples_temp = (
    tbl_panoptes_samples
    .cut(list(final_columns.keys()) + ['sort_AlfrescoStudyCode'])
    .rename(dict(final_columns))
#     .cut(list(final_columns.values()))
    .sort(['AlfrescoStudyCode', 'Sample'])
)
print(len(tbl_panoptes_samples_temp.data()))

tbl_panoptes_samples_distinct = (
    tbl_panoptes_samples_temp
    .distinct(['sort_AlfrescoStudyCode', 'Individual_ID'])
    .addrownumbers()
    .rename('row', 'IndividualGroup')
    .cut(['sort_AlfrescoStudyCode', 'Individual_ID', 'IndividualGroup'])
)

tbl_panoptes_samples_final = (
    tbl_panoptes_samples_temp
    .join(tbl_panoptes_samples_distinct, key=['sort_AlfrescoStudyCode', 'Individual_ID'])
)
print(len(tbl_panoptes_samples_final.data()))
tbl_panoptes_samples_final

7182
7182

+------------+---------------+-----------------+---------------+---------------------+-------+--------+------+------------------+------------------+------------+-------------+-------------+-----------+--------+--------+--------------+--------------------+-------------------------------------------+-----------------------+-------------------------+-------------+------------------------+-----------------+
| Sample     | OxfordSrcCode | OxfordDonorCode | Individual_ID | AlfrescoStudyCode   | Type  | InV5.1 | InV5 | SubContinentCode | SubContinentName | RegionCode | CountryCode | CountryName | Site      | Year   | Date   | HasDuplicate | DiscardAsDuplicate | run_accessions                            | pc_pass_missing       | pc_genome_covered_at_1x | Year_source | sort_AlfrescoStudyCode | IndividualGroup |
+============+===============+=================+===============+=====================+=======+========+======+==================+==================+============+=============+=============+===========+========+========+==============+====================+===========================================+=======================+=========================+=============+========================+=================+
| 'PM0001-C' | '215C'        | '215C'          | '215C'        | '1001-PF-ML-DJIMDE' | 'DNA' | True   | True | 'WAF'            | 'West Africa'    | 'ML'       | 'ML'        | 'Mali'      | 'Kolle'   | '2007' | '2007' | False        | False              | 'ERR012350,ERR012360,ERR012305'           | '0.15139786050931692' | '0.9696'                | 'study'     | '1001-PF-ML-DJIMDE'    |               1 |
+------------+---------------+-----------------+---------------+---------------------+-------+--------+------+------------------+------------------+------------+-------------+-------------+-----------+--------+--------+--------------+--------------------+-------------------------------------------+-----------------------+-------------------------+-------------+------------------------+-----------------+
| 'PM0002-C' | '217C'        | '217C'          | '217C'        | '1001-PF-ML-DJIMDE' | 'DNA' | True   | True | 'WAF'            | 'West Africa'    | 'ML'       | 'ML'        | 'Mali'      | 'Kolle'   | '2007' | '2007' | False        | False              | 'ERR012520,ERR012331,ERR012327'           | '0.28678549872221293' | '0.864'                 | 'study'     | '1001-PF-ML-DJIMDE'    |               2 |
+------------+---------------+-----------------+---------------+---------------------+-------+--------+------+------------------+------------------+------------+-------------+-------------+-----------+--------+--------+--------------+--------------------+-------------------------------------------+-----------------------+-------------------------+-------------+------------------------+-----------------+
| 'PM0003-C' | '520C'        | '520C'          | '520C'        | '1001-PF-ML-DJIMDE' | 'DNA' | True   | True | 'WAF'            | 'West Africa'    | 'ML'       | 'ML'        | 'Mali'      | 'Kolle'   | '2007' | '2007' | False        | False              | 'ERR012492,ERR012457,ERR012532'           | '0.1662372060768727'  | '0.9586'                | 'study'     | '1001-PF-ML-DJIMDE'    |               3 |
+------------+---------------+-----------------+---------------+---------------------+-------+--------+------+------------------+------------------+------------+-------------+-------------+-----------+--------+--------+--------------+--------------------+-------------------------------------------+-----------------------+-------------------------+-------------+------------------------+-----------------+
| 'PM0004-C' | 'A336TPI7C'   | 'A336TPI7C'     | 'A336TPI7C'   | '1001-PF-ML-DJIMDE' | 'DNA' | True   | True | 'WAF'            | 'West Africa'    | 'ML'       | 'ML'        | 'Mali'      | 'Kolle'   | '2007' | '2007' | False        | False              | 'ERR015438,ERR015329,ERR015422,ERR015315' | '0.11811536041300132' | '0.9648'                | 'study'     | '1001-PF-ML-DJIMDE'    |               4 |
+------------+---------------+-----------------+---------------+---------------------+-------+--------+------+------------------+------------------+------------+-------------+-------------+-----------+--------+--------+--------------+--------------------+-------------------------------------------+-----------------------+-------------------------+-------------+------------------------+-----------------+
| 'PM0103-C' | 'ALF003'      | 'ALF003'        | 'ALF003'      | '1001-PF-ML-DJIMDE' | 'DNA' | True   | True | 'WAF'            | 'West Africa'    | 'ML'       | 'ML'        | 'Mali'      | 'Faladje' | '2007' | '2007' | False        | False              | 'ERR199991'                               | '0.13763789184399441' | '0.9485'                | 'study'     | '1001-PF-ML-DJIMDE'    |               5 |
+------------+---------------+-----------------+---------------+---------------------+-------+--------+------+------------------+------------------+------------+-------------+-------------+-----------+--------+--------+--------------+--------------------+-------------------------------------------+-----------------------+-------------------------+-------------+------------------------+-----------------+
...

In [216]:
tbl_panoptes_samples_final.totsv(panoptes_final_metadata_fn, lineterminator='\n')

In [217]:
tbl_panoptes_samples_final = etl.fromtsv(panoptes_final_metadata_fn)
print(len(tbl_panoptes_samples_final.data()))
tbl_panoptes_samples_final

7182

+------------+---------------+-----------------+---------------+---------------------+-------+--------+--------+------------------+------------------+------------+-------------+-------------+-----------+--------+--------+--------------+--------------------+-------------------------------------------+-----------------------+-------------------------+-------------+------------------------+-----------------+
| Sample     | OxfordSrcCode | OxfordDonorCode | Individual_ID | AlfrescoStudyCode   | Type  | InV5.1 | InV5   | SubContinentCode | SubContinentName | RegionCode | CountryCode | CountryName | Site      | Year   | Date   | HasDuplicate | DiscardAsDuplicate | run_accessions                            | pc_pass_missing       | pc_genome_covered_at_1x | Year_source | sort_AlfrescoStudyCode | IndividualGroup |
+============+===============+=================+===============+=====================+=======+========+========+==================+==================+============+=============+=============+===========+========+========+==============+====================+===========================================+=======================+=========================+=============+========================+=================+
| 'PM0001-C' | '215C'        | '215C'          | '215C'        | '1001-PF-ML-DJIMDE' | 'DNA' | 'True' | 'True' | 'WAF'            | 'West Africa'    | 'ML'       | 'ML'        | 'Mali'      | 'Kolle'   | '2007' | '2007' | 'False'      | 'False'            | 'ERR012350,ERR012360,ERR012305'           | '0.15139786050931692' | '0.9696'                | 'study'     | '1001-PF-ML-DJIMDE'    | '1'             |
+------------+---------------+-----------------+---------------+---------------------+-------+--------+--------+------------------+------------------+------------+-------------+-------------+-----------+--------+--------+--------------+--------------------+-------------------------------------------+-----------------------+-------------------------+-------------+------------------------+-----------------+
| 'PM0002-C' | '217C'        | '217C'          | '217C'        | '1001-PF-ML-DJIMDE' | 'DNA' | 'True' | 'True' | 'WAF'            | 'West Africa'    | 'ML'       | 'ML'        | 'Mali'      | 'Kolle'   | '2007' | '2007' | 'False'      | 'False'            | 'ERR012520,ERR012331,ERR012327'           | '0.28678549872221293' | '0.864'                 | 'study'     | '1001-PF-ML-DJIMDE'    | '2'             |
+------------+---------------+-----------------+---------------+---------------------+-------+--------+--------+------------------+------------------+------------+-------------+-------------+-----------+--------+--------+--------------+--------------------+-------------------------------------------+-----------------------+-------------------------+-------------+------------------------+-----------------+
| 'PM0003-C' | '520C'        | '520C'          | '520C'        | '1001-PF-ML-DJIMDE' | 'DNA' | 'True' | 'True' | 'WAF'            | 'West Africa'    | 'ML'       | 'ML'        | 'Mali'      | 'Kolle'   | '2007' | '2007' | 'False'      | 'False'            | 'ERR012492,ERR012457,ERR012532'           | '0.1662372060768727'  | '0.9586'                | 'study'     | '1001-PF-ML-DJIMDE'    | '3'             |
+------------+---------------+-----------------+---------------+---------------------+-------+--------+--------+------------------+------------------+------------+-------------+-------------+-----------+--------+--------+--------------+--------------------+-------------------------------------------+-----------------------+-------------------------+-------------+------------------------+-----------------+
| 'PM0004-C' | 'A336TPI7C'   | 'A336TPI7C'     | 'A336TPI7C'   | '1001-PF-ML-DJIMDE' | 'DNA' | 'True' | 'True' | 'WAF'            | 'West Africa'    | 'ML'       | 'ML'        | 'Mali'      | 'Kolle'   | '2007' | '2007' | 'False'      | 'False'            | 'ERR015438,ERR015329,ERR015422,ERR015315' | '0.11811536041300132' | '0.9648'                | 'study'     | '1001-PF-ML-DJIMDE'    | '4'             |
+------------+---------------+-----------------+---------------+---------------------+-------+--------+--------+------------------+------------------+------------+-------------+-------------+-----------+--------+--------+--------------+--------------------+-------------------------------------------+-----------------------+-------------------------+-------------+------------------------+-----------------+
| 'PM0103-C' | 'ALF003'      | 'ALF003'        | 'ALF003'      | '1001-PF-ML-DJIMDE' | 'DNA' | 'True' | 'True' | 'WAF'            | 'West Africa'    | 'ML'       | 'ML'        | 'Mali'      | 'Faladje' | '2007' | '2007' | 'False'      | 'False'            | 'ERR199991'                               | '0.13763789184399441' | '0.9485'                | 'study'     | '1001-PF-ML-DJIMDE'    | '5'             |
+------------+---------------+-----------------+---------------+---------------------+-------+--------+--------+------------------+------------------+------------+-------------+-------------+-----------+--------+--------+--------------+--------------------+-------------------------------------------+-----------------------+-------------------------+-------------+------------------------+-----------------+
...

# Tables for follow up with partners

In [218]:
tbl_country_summary = (
    (
        tbl_panoptes_samples_final
        .selecteq('InV5', 'True')
        .valuecounts(
            'CountryName',
        )
        .rename('count', 'Total in 5.0')
        .cutout('frequency')
    ).outerjoin(
    (
        tbl_panoptes_samples_final
        .valuecounts(
            'CountryName',
        )
        .rename('count', 'Total in 6.0')
        .cutout('frequency')
    ), key='CountryName')
    .outerjoin(
    (
        tbl_panoptes_samples_final
        .selecteq('InV5', 'True')
        .selecteq('DiscardAsDuplicate', 'False')
        .select(lambda rec: float(rec['pc_genome_covered_at_1x']) >= 0.5)
        .valuecounts(
            'CountryName',
        )
        .rename('count', 'HQ 5.0')
        .cutout('frequency')
    ), key='CountryName')
    .outerjoin(
    (
        tbl_panoptes_samples_final
        .selecteq('DiscardAsDuplicate', 'False')
        .select(lambda rec: float(rec['pc_genome_covered_at_1x']) >= 0.5)
        .valuecounts(
            'CountryName',
        )
        .rename('count', 'HQ 6.0')
        .cutout('frequency')
    ), key='CountryName')
    .replaceall(None, 0)
    .sort(['CountryName'])
)

tbl_country_summary.displayall()

CountryName,Total in 5.0,Total in 6.0,HQ 5.0,HQ 6.0
Bangladesh,93,93,92,92
Benin,0,102,0,42
Burkina Faso,56,57,56,57
Cambodia,1105,1215,918,1019
Cameroon,239,239,239,239
Colombia,17,17,17,17
Congo DR,289,366,289,366
Ethiopia,0,34,0,30
Gambia,79,277,78,242
Ghana,849,1006,824,884
Guinea,191,197,177,177
Indonesia,26,92,20,84
Ivory Coast,70,70,70,70
Kenya,133,134,125,125
Lab,9,76,8,74
Laos,131,131,127,127
Madagascar,25,25,24,24
Malawi,349,351,257,258
Mali,399,451,395,447
Mauritania,0,86,0,81
Mozambique,1,1,1,1
Myanmar,145,250,111,216
Nigeria,8,42,5,33
Papua New Guinea,138,139,131,132
Peru,24,24,23,23
Senegal,0,86,0,86
Tanzania,350,350,337,337
Thailand,987,991,965,965
Uganda,16,16,14,14
Viet Nam,264,264,256,256

In [219]:
tbl_study_summary = (
    (
        tbl_panoptes_samples_final
        .selecteq('InV5', 'True')
        .valuecounts(
            'AlfrescoStudyCode',
        )
        .rename('count', 'Total in 5.0')
        .cutout('frequency')
    ).outerjoin(
    (
        tbl_panoptes_samples_final
        .valuecounts(
            'AlfrescoStudyCode',
        )
        .rename('count', 'Total in 6.0')
        .cutout('frequency')
    ), key='AlfrescoStudyCode')
    .addfield('New in 6.0', lambda rec: rec['Total in 6.0'] if rec['Total in 5.0'] is None else rec['Total in 6.0'] - rec['Total in 5.0'])
    .outerjoin(
    (
        tbl_panoptes_samples_final
            .selectin('Year', ['-', 'N/A'])
        .valuecounts(
            'AlfrescoStudyCode',
        )
        .rename('count', 'Missing year')
        .cutout('frequency')
    ), key='AlfrescoStudyCode')
    .outerjoin(
    (
        tbl_panoptes_samples_final
            .selectin('Site', ['-'])
        .valuecounts(
            'AlfrescoStudyCode',
        )
        .rename('count', 'Missing site')
        .cutout('frequency')
    ), key='AlfrescoStudyCode')
#     .outerjoin(
#     (
#         tbl_panoptes_samples_final
#         .selecteq('InV5', 'True')
#         .selecteq('DiscardAsDuplicate', 'False')
#         .select(lambda rec: float(rec['pc_genome_covered_at_1x']) >= 0.5)
#         .valuecounts(
#             'AlfrescoStudyCode',
#         )
#         .rename('count', 'HQ 5.0')
#         .cutout('frequency')
#     ), key='AlfrescoStudyCode')
#     .outerjoin(
#     (
#         tbl_panoptes_samples_final
#         .selecteq('DiscardAsDuplicate', 'False')
#         .select(lambda rec: float(rec['pc_genome_covered_at_1x']) >= 0.5)
#         .valuecounts(
#             'AlfrescoStudyCode',
#         )
#         .rename('count', 'HQ 6.0')
#         .cutout('frequency')
#     ), key='AlfrescoStudyCode')
    .replaceall(None, 0)
    .sort(['AlfrescoStudyCode'])
)
tbl_study_summary.toxlsx('%s/study_summary_20170123_v2.xlsx' % output_dir)
tbl_study_summary.displayall()

AlfrescoStudyCode,Total in 5.0,Total in 6.0,New in 6.0,Missing year,Missing site
1001-PF-ML-DJIMDE,96,96,0,0,0
1004-PF-BF-OUEDRAOGO,56,57,1,0,0
1006-PF-GM-CONWAY,79,79,0,0,0
1007-PF-TZ-DUFFY,50,50,0,0,0
1008-PF-SEA-RINGWALD,234,234,0,0,0
1009-PF-KH-PLOWE,5,5,0,0,0
1010-PF-TH-ANDERSON,107,108,1,0,0
1011-PF-KH-SU,40,41,1,0,0
1012-PF-KH-WHITE,2,2,0,0,0
1013-PF-PEGB-BRANCH,16,16,0,0,0
1014-PF-SSA-SUTHERLAND,10,10,0,0,0
1015-PF-KE-NZILA,59,60,1,0,0
1016-PF-TH-NOSTEN,21,21,0,0,0
1017-PF-GH-AMENGA-ETEGO,390,390,0,0,0
1018-PF-GB-NEWBOLD,1,1,0,0,0
1020-PF-VN-BONI,24,24,0,0,0
1021-PF-PG-MUELLER,56,57,1,0,0
1022-PF-MW-OCHOLLA,349,351,2,0,0
1023-PF-CO-ECHEVERRI-GARCIA,17,17,0,0,0
1024-PF-UG-BOUSEMA,14,14,0,0,0
1025-PF-KH-PLOWE,10,10,0,0,0
1026-PF-GN-CONWAY,191,197,6,0,0
1027-PF-KE-BULL,11,11,0,0,0
1031-PF-SEA-PLOWE,177,177,0,0,0
1044-PF-KH-FAIRHURST,494,602,108,0,0
1052-PF-TRAC-WHITE,1066,1172,106,0,0
1062-PF-PG-BARRY,82,82,0,0,0
1083-PF-GH-CONWAY,100,101,1,0,0
1093-PF-CM-APINJOH,239,239,0,0,0
1094-PF-GH-AMENGA-ETEGO,255,256,1,0,0
1095-PF-TZ-ISHENGOMA,300,300,0,0,0
1096-PF-GH-GHANSAH,101,101,0,0,0
1097-PF-ML-MAIGA,137,137,0,0,0
1098-PF-ET-GOLASSA,0,34,34,0,0
1100-PF-CI-YAVO,70,70,0,0,0
1101-PF-CD-ONYAMBOKO,174,174,0,0,0
1102-PF-MG-RANDRIANARIVELOJOSIA,25,25,0,0,0
1103-PF-PDN-GMSN-NGWA,0,34,34,0,0
1107-PF-KEN-KAMAU,61,61,0,0,0
1125-PF-TH-NOSTEN,671,674,3,0,0
1127-PF-ML-SOULEYMANE,164,164,0,0,0
1131-PF-BJ-BERTIN,0,102,102,0,0
1133-PF-LAB-MERRICK,0,66,66,0,0
1134-PF-ML-CONWAY,0,52,52,0,0
1135-PF-SN-CONWAY,0,86,86,0,0
1136-PF-GM-NGWA,0,100,100,0,0
1137-PF-GM-DALESSANDRO,0,68,68,0,0
1138-PF-CD-FANELLO,0,77,77,0,0
1141-PF-GM-CLAESSENS,0,31,31,0,0
1145-PF-PE-GAMBOA,13,13,0,0,0
1147-PF-MR-CONWAY,0,86,86,0,0
1151-PF-GH-AMENGA-ETEGO,0,111,111,0,0
1152-PF-DBS-GH-AMENGA-ETEGO,0,44,44,0,0
1155-PF-ID-PRICE,26,92,66,0,0

In [220]:
partner_columns = ['Sample', 'OxfordSrcCode', 'Site', 'Year', 'IndividualGroup']

In [221]:
from pandas import ExcelWriter

studies = tbl_study_summary.values('AlfrescoStudyCode').list()
writer = ExcelWriter('%s/samples_by_study_20170123_v2.xlsx' % output_dir)
for study in studies:
    print(study)
    if tbl_study_summary.selecteq('AlfrescoStudyCode', study).values('Total in 5.0')[0] > 0:
        df = (
            tbl_panoptes_samples_final
            .selecteq('AlfrescoStudyCode', study)
            .selecteq('InV5', 'True')
            .cut(partner_columns)
            .todataframe()
        )
        sheet_name = "%s_old" % study[0:4]
        df.to_excel(writer, sheet_name, index=False)
    if tbl_study_summary.selecteq('AlfrescoStudyCode', study).values('New in 6.0')[0] > 0:
        df = (
            tbl_panoptes_samples_final
            .selecteq('AlfrescoStudyCode', study)
            .selecteq('InV5', 'False')
            .cut(partner_columns)
            .todataframe()
        )
        sheet_name = "%s_new" % study[0:4]
        df.to_excel(writer, sheet_name, index=False)
writer.save()

1001-PF-ML-DJIMDE
1004-PF-BF-OUEDRAOGO
1006-PF-GM-CONWAY
1007-PF-TZ-DUFFY
1008-PF-SEA-RINGWALD
1009-PF-KH-PLOWE
1010-PF-TH-ANDERSON
1011-PF-KH-SU
1012-PF-KH-WHITE
1013-PF-PEGB-BRANCH
1014-PF-SSA-SUTHERLAND
1015-PF-KE-NZILA
1016-PF-TH-NOSTEN
1017-PF-GH-AMENGA-ETEGO
1018-PF-GB-NEWBOLD
1020-PF-VN-BONI
1021-PF-PG-MUELLER
1022-PF-MW-OCHOLLA
1023-PF-CO-ECHEVERRI-GARCIA
1024-PF-UG-BOUSEMA
1025-PF-KH-PLOWE
1026-PF-GN-CONWAY
1027-PF-KE-BULL
1031-PF-SEA-PLOWE
1044-PF-KH-FAIRHURST
1052-PF-TRAC-WHITE
1062-PF-PG-BARRY
1083-PF-GH-CONWAY
1093-PF-CM-APINJOH
1094-PF-GH-AMENGA-ETEGO
1095-PF-TZ-ISHENGOMA
1096-PF-GH-GHANSAH
1097-PF-ML-MAIGA
1098-PF-ET-GOLASSA
1100-PF-CI-YAVO
1101-PF-CD-ONYAMBOKO
1102-PF-MG-RANDRIANARIVELOJOSIA
1103-PF-PDN-GMSN-NGWA
1107-PF-KEN-KAMAU
1125-PF-TH-NOSTEN
1127-PF-ML-SOULEYMANE
1131-PF-BJ-BERTIN
1133-PF-LAB-MERRICK
1134-PF-ML-CONWAY
1135-PF-SN-CONWAY
1136-PF-GM-NGWA
1137-PF-GM-DALESSANDRO
1138-PF-CD-FANELLO
1141-PF-GM-CLAESSENS
1145-PF-PE-GAMBOA
1147-PF-MR-CONWAY
1151-PF-GH-AMENGA-ETEGO
1152-PF-DBS-GH-AMENGA-ETEGO
1155-PF-ID-PRICE

In [222]:
tbl_panoptes_samples_final

+------------+---------------+-----------------+---------------+---------------------+-------+--------+--------+------------------+------------------+------------+-------------+-------------+-----------+--------+--------+--------------+--------------------+-------------------------------------------+-----------------------+-------------------------+-------------+------------------------+-----------------+
| Sample     | OxfordSrcCode | OxfordDonorCode | Individual_ID | AlfrescoStudyCode   | Type  | InV5.1 | InV5   | SubContinentCode | SubContinentName | RegionCode | CountryCode | CountryName | Site      | Year   | Date   | HasDuplicate | DiscardAsDuplicate | run_accessions                            | pc_pass_missing       | pc_genome_covered_at_1x | Year_source | sort_AlfrescoStudyCode | IndividualGroup |
+============+===============+=================+===============+=====================+=======+========+========+==================+==================+============+=============+=============+===========+========+========+==============+====================+===========================================+=======================+=========================+=============+========================+=================+
| 'PM0001-C' | '215C'        | '215C'          | '215C'        | '1001-PF-ML-DJIMDE' | 'DNA' | 'True' | 'True' | 'WAF'            | 'West Africa'    | 'ML'       | 'ML'        | 'Mali'      | 'Kolle'   | '2007' | '2007' | 'False'      | 'False'            | 'ERR012350,ERR012360,ERR012305'           | '0.15139786050931692' | '0.9696'                | 'study'     | '1001-PF-ML-DJIMDE'    | '1'             |
+------------+---------------+-----------------+---------------+---------------------+-------+--------+--------+------------------+------------------+------------+-------------+-------------+-----------+--------+--------+--------------+--------------------+-------------------------------------------+-----------------------+-------------------------+-------------+------------------------+-----------------+
| 'PM0002-C' | '217C'        | '217C'          | '217C'        | '1001-PF-ML-DJIMDE' | 'DNA' | 'True' | 'True' | 'WAF'            | 'West Africa'    | 'ML'       | 'ML'        | 'Mali'      | 'Kolle'   | '2007' | '2007' | 'False'      | 'False'            | 'ERR012520,ERR012331,ERR012327'           | '0.28678549872221293' | '0.864'                 | 'study'     | '1001-PF-ML-DJIMDE'    | '2'             |
+------------+---------------+-----------------+---------------+---------------------+-------+--------+--------+------------------+------------------+------------+-------------+-------------+-----------+--------+--------+--------------+--------------------+-------------------------------------------+-----------------------+-------------------------+-------------+------------------------+-----------------+
| 'PM0003-C' | '520C'        | '520C'          | '520C'        | '1001-PF-ML-DJIMDE' | 'DNA' | 'True' | 'True' | 'WAF'            | 'West Africa'    | 'ML'       | 'ML'        | 'Mali'      | 'Kolle'   | '2007' | '2007' | 'False'      | 'False'            | 'ERR012492,ERR012457,ERR012532'           | '0.1662372060768727'  | '0.9586'                | 'study'     | '1001-PF-ML-DJIMDE'    | '3'             |
+------------+---------------+-----------------+---------------+---------------------+-------+--------+--------+------------------+------------------+------------+-------------+-------------+-----------+--------+--------+--------------+--------------------+-------------------------------------------+-----------------------+-------------------------+-------------+------------------------+-----------------+
| 'PM0004-C' | 'A336TPI7C'   | 'A336TPI7C'     | 'A336TPI7C'   | '1001-PF-ML-DJIMDE' | 'DNA' | 'True' | 'True' | 'WAF'            | 'West Africa'    | 'ML'       | 'ML'        | 'Mali'      | 'Kolle'   | '2007' | '2007' | 'False'      | 'False'            | 'ERR015438,ERR015329,ERR015422,ERR015315' | '0.11811536041300132' | '0.9648'                | 'study'     | '1001-PF-ML-DJIMDE'    | '4'             |
+------------+---------------+-----------------+---------------+---------------------+-------+--------+--------+------------------+------------------+------------+-------------+-------------+-----------+--------+--------+--------------+--------------------+-------------------------------------------+-----------------------+-------------------------+-------------+------------------------+-----------------+
| 'PM0103-C' | 'ALF003'      | 'ALF003'        | 'ALF003'      | '1001-PF-ML-DJIMDE' | 'DNA' | 'True' | 'True' | 'WAF'            | 'West Africa'    | 'ML'       | 'ML'        | 'Mali'      | 'Faladje' | '2007' | '2007' | 'False'      | 'False'            | 'ERR199991'                               | '0.13763789184399441' | '0.9485'                | 'study'     | '1001-PF-ML-DJIMDE'    | '5'             |
+------------+---------------+-----------------+---------------+---------------------+-------+--------+--------+------------------+------------------+------------+-------------+-------------+-----------+--------+--------+--------------+--------------------+-------------------------------------------+-----------------------+-------------------------+-------------+------------------------+-----------------+
...

# Sanity checks

## Sample

In [223]:
(tbl_panoptes_samples_final
    .selectnone('Sample')
)

+--------+---------------+-----------------+---------------+-------------------+------+--------+------+------------------+------------------+------------+-------------+-------------+------+------+------+--------------+--------------------+----------------+-----------------+-------------------------+-------------+------------------------+-----------------+
| Sample | OxfordSrcCode | OxfordDonorCode | Individual_ID | AlfrescoStudyCode | Type | InV5.1 | InV5 | SubContinentCode | SubContinentName | RegionCode | CountryCode | CountryName | Site | Year | Date | HasDuplicate | DiscardAsDuplicate | run_accessions | pc_pass_missing | pc_genome_covered_at_1x | Year_source | sort_AlfrescoStudyCode | IndividualGroup |
+========+===============+=================+===============+===================+======+========+======+==================+==================+============+=============+=============+======+======+======+==============+====================+================+=================+=========================+=============+========================+=================+

## OxfordSrcCode

In [224]:
(tbl_panoptes_samples_final
    .selectnone('OxfordSrcCode')
)

+--------+---------------+-----------------+---------------+-------------------+------+--------+------+------------------+------------------+------------+-------------+-------------+------+------+------+--------------+--------------------+----------------+-----------------+-------------------------+-------------+------------------------+-----------------+
| Sample | OxfordSrcCode | OxfordDonorCode | Individual_ID | AlfrescoStudyCode | Type | InV5.1 | InV5 | SubContinentCode | SubContinentName | RegionCode | CountryCode | CountryName | Site | Year | Date | HasDuplicate | DiscardAsDuplicate | run_accessions | pc_pass_missing | pc_genome_covered_at_1x | Year_source | sort_AlfrescoStudyCode | IndividualGroup |
+========+===============+=================+===============+===================+======+========+======+==================+==================+============+=============+=============+======+======+======+==============+====================+================+=================+=========================+=============+========================+=================+

## OxfordDonorCode

In [225]:
(tbl_panoptes_samples_final
    .selectnone('OxfordDonorCode')
)

+--------+---------------+-----------------+---------------+-------------------+------+--------+------+------------------+------------------+------------+-------------+-------------+------+------+------+--------------+--------------------+----------------+-----------------+-------------------------+-------------+------------------------+-----------------+
| Sample | OxfordSrcCode | OxfordDonorCode | Individual_ID | AlfrescoStudyCode | Type | InV5.1 | InV5 | SubContinentCode | SubContinentName | RegionCode | CountryCode | CountryName | Site | Year | Date | HasDuplicate | DiscardAsDuplicate | run_accessions | pc_pass_missing | pc_genome_covered_at_1x | Year_source | sort_AlfrescoStudyCode | IndividualGroup |
+========+===============+=================+===============+===================+======+========+======+==================+==================+============+=============+=============+======+======+======+==============+====================+================+=================+=========================+=============+========================+=================+

## Individual_ID

In [226]:
(tbl_panoptes_samples_final
    .selectnone('Individual_ID')
)

+--------+---------------+-----------------+---------------+-------------------+------+--------+------+------------------+------------------+------------+-------------+-------------+------+------+------+--------------+--------------------+----------------+-----------------+-------------------------+-------------+------------------------+-----------------+
| Sample | OxfordSrcCode | OxfordDonorCode | Individual_ID | AlfrescoStudyCode | Type | InV5.1 | InV5 | SubContinentCode | SubContinentName | RegionCode | CountryCode | CountryName | Site | Year | Date | HasDuplicate | DiscardAsDuplicate | run_accessions | pc_pass_missing | pc_genome_covered_at_1x | Year_source | sort_AlfrescoStudyCode | IndividualGroup |
+========+===============+=================+===============+===================+======+========+======+==================+==================+============+=============+=============+======+======+======+==============+====================+================+=================+=========================+=============+========================+=================+

## AlfrescoStudyCode

In [227]:
(tbl_panoptes_samples_final
    .selectnone('AlfrescoStudyCode')
)

+--------+---------------+-----------------+---------------+-------------------+------+--------+------+------------------+------------------+------------+-------------+-------------+------+------+------+--------------+--------------------+----------------+-----------------+-------------------------+-------------+------------------------+-----------------+
| Sample | OxfordSrcCode | OxfordDonorCode | Individual_ID | AlfrescoStudyCode | Type | InV5.1 | InV5 | SubContinentCode | SubContinentName | RegionCode | CountryCode | CountryName | Site | Year | Date | HasDuplicate | DiscardAsDuplicate | run_accessions | pc_pass_missing | pc_genome_covered_at_1x | Year_source | sort_AlfrescoStudyCode | IndividualGroup |
+========+===============+=================+===============+===================+======+========+======+==================+==================+============+=============+=============+======+======+======+==============+====================+================+=================+=========================+=============+========================+=================+

## Type

In [228]:
(tbl_panoptes_samples_final
    .selectnone('Type')
)

+--------+---------------+-----------------+---------------+-------------------+------+--------+------+------------------+------------------+------------+-------------+-------------+------+------+------+--------------+--------------------+----------------+-----------------+-------------------------+-------------+------------------------+-----------------+
| Sample | OxfordSrcCode | OxfordDonorCode | Individual_ID | AlfrescoStudyCode | Type | InV5.1 | InV5 | SubContinentCode | SubContinentName | RegionCode | CountryCode | CountryName | Site | Year | Date | HasDuplicate | DiscardAsDuplicate | run_accessions | pc_pass_missing | pc_genome_covered_at_1x | Year_source | sort_AlfrescoStudyCode | IndividualGroup |
+========+===============+=================+===============+===================+======+========+======+==================+==================+============+=============+=============+======+======+======+==============+====================+================+=================+=========================+=============+========================+=================+

In [229]:
tbl_panoptes_samples_final.valuecounts('Type')

+--------+-------+----------------------+
| Type   | count | frequency            |
+========+=======+======================+
| 'DNA'  |  6878 |   0.9576719576719577 |
+--------+-------+----------------------+
| 'MDA'  |   215 | 0.029935950988582566 |
+--------+-------+----------------------+
| 'sWGA' |    89 |  0.01239209133945976 |
+--------+-------+----------------------+

## InV5.1

In [230]:
tbl_panoptes_samples_final.valuecounts('InV5.1')

+---------+-------+---------------------+
| InV5.1  | count | frequency           |
+=========+=======+=====================+
| 'True'  |  6250 |  0.8702311333890281 |
+---------+-------+---------------------+
| 'False' |   932 | 0.12976886661097187 |
+---------+-------+---------------------+

## InV5

In [231]:
tbl_panoptes_samples_final.valuecounts('InV5')

+---------+-------+--------------------+
| InV5    | count | frequency          |
+=========+=======+====================+
| 'True'  |  5993 | 0.8344472291840713 |
+---------+-------+--------------------+
| 'False' |  1189 | 0.1655527708159287 |
+---------+-------+--------------------+

# CountryCode

In [232]:
tbl_panoptes_samples_final.selectnone('CountryCode').displayall()

# CountryName

In [233]:
tbl_panoptes_samples_final.selectnone('CountryName').displayall()

In [234]:
tbl_panoptes_samples_final.valuecounts('CountryCode', 'CountryName').displayall()

CountryCode,CountryName,count,frequency
KH,Cambodia,1215,0.16917293233082706
GH,Ghana,1006,0.14007240323029796
TH,Thailand,991,0.1379838485101643
ML,Mali,451,0.06279587858535227
CD,Congo DR,366,0.050960735171261484
MW,Malawi,351,0.04887218045112782
TZ,Tanzania,350,0.04873294346978557
GM,Gambia,277,0.038568643831801724
VN,Viet Nam,264,0.036758563074352546
MM,Myanmar,250,0.03480924533556112
CM,Cameroon,239,0.033277638540796434
GN,Guinea,197,0.027429685324422165
PG,Papua New Guinea,139,0.019353940406571984
KE,Kenya,134,0.018657755499860762
LA,Laos,131,0.01824004455583403
BJ,Benin,102,0.014202172096908938
BD,Bangladesh,93,0.012949039264828738
ID,Indonesia,92,0.012809802283486493
MR,Mauritania,86,0.011974380395433026
SN,Senegal,86,0.011974380395433026
Lab,Lab,76,0.010582010582010581
CI,Ivory Coast,70,0.009746588693957114
BF,Burkina Faso,57,0.007936507936507936
NG,Nigeria,42,0.005847953216374269
ET,Ethiopia,34,0.004734057365636313
MG,Madagascar,25,0.0034809245335561123
PE,Peru,24,0.003341687552213868
CO,Colombia,17,0.0023670286828181564
UG,Uganda,16,0.002227791701475912
MZ,Mozambique,1,0.0001392369813422445

# SubContinentCode

In [235]:
tbl_panoptes_samples_final.valuecounts('SubContinentCode', 'SubContinentName').displayall()

SubContinentCode,SubContinentName,count,frequency
WAF,West Africa,2613,0.3638262322472849
ESEA,Eastern south-east Asia,1638,0.22807017543859648
WSEA,Western south-east Asia,1213,0.16889445836814257
EAF,East Africa,886,0.12336396546922862
CAF,Central Africa,366,0.050960735171261484
OCE,Oceania,231,0.03216374269005848
SAS,South Asia,93,0.012949039264828738
Lab,Lab,76,0.010582010582010581
SAM,South America,41,0.005708716235032024
ISL,Insular Africa,25,0.0034809245335561123

# RegionCode

In [236]:
tbl_panoptes_samples_final.valuecounts('RegionCode').displayall()

RegionCode,count,frequency
GH,1006,0.14007240323029796
WTH,936,0.13032581453634084
WKH,762,0.1060985797827903
ML,451,0.06279587858535227
CD,366,0.050960735171261484
MW,351,0.04887218045112782
TZ,350,0.04873294346978557
GM,277,0.038568643831801724
VN,264,0.036758563074352546
NEKH,243,0.03383458646616541
CM,239,0.033277638540796434
NKH,210,0.029239766081871343
GN,197,0.027429685324422165
PG,139,0.019353940406571984
KE,134,0.018657755499860762
LA,131,0.01824004455583403
NMM,105,0.014619883040935672
BJ,102,0.014202172096908938
CMM,94,0.013088276246170982
BD,93,0.012949039264828738
ID,92,0.012809802283486493
MR,86,0.011974380395433026
SN,86,0.011974380395433026
Lab,76,0.010582010582010581
CI,70,0.009746588693957114
BF,57,0.007936507936507936
SMM,51,0.007101086048454469
NG,42,0.005847953216374269
ET,34,0.004734057365636313
ETH,28,0.003898635477582846
STH,27,0.0037593984962406013
MG,25,0.0034809245335561123
PE,24,0.003341687552213868
CO,17,0.0023670286828181564
UG,16,0.002227791701475912
MZ,1,0.0001392369813422445

# Site

In [237]:
tbl_panoptes_samples_final.valuecounts('Site', 'RegionCode', 'CountryCode', 'CountryName', 'SubContinentCode', 'SubContinentName').sort('Site').displayall()

Site,RegionCode,CountryCode,CountryName,SubContinentCode,SubContinentName,count,frequency
Abobo,CI,CI,Ivory Coast,WAF,West Africa,31,0.004316346421609579
Accra,GH,GH,Ghana,WAF,West Africa,101,0.014062935115566694
Aioun,MR,MR,Mauritania,WAF,West Africa,9,0.0012531328320802004
Amhara region,ET,ET,Ethiopia,EAF,East Africa,15,0.0020885547201336674
Antsohihy,MG,MG,Madagascar,ISL,Insular Africa,6,0.000835421888053467
Apac,UG,UG,Uganda,EAF,East Africa,14,0.001949317738791423
Attapeu,LA,LA,Laos,ESEA,Eastern south-east Asia,86,0.011974380395433026
Bagdary,NG,NG,Nigeria,WAF,West Africa,34,0.004734057365636313
Bago,CMM,MM,Myanmar,WSEA,Western south-east Asia,94,0.013088276246170982
Bamako,ML,ML,Mali,WAF,West Africa,164,0.022834864940128097
Bandarban,BD,BD,Bangladesh,SAS,South Asia,42,0.005847953216374269
Bandiagara,ML,ML,Mali,WAF,West Africa,9,0.0012531328320802004
Basse,GM,GM,Gambia,WAF,West Africa,124,0.017265385686438317
Binh Phuoc,VN,VN,Viet Nam,ESEA,Eastern south-east Asia,126,0.017543859649122806
Bobo-Dioulasso,BF,BF,Burkina Faso,WAF,West Africa,57,0.007936507936507936
Brikama,GM,GM,Gambia,WAF,West Africa,123,0.017126148705096073
Buea,CM,CM,Cameroon,WAF,West Africa,239,0.033277638540796434
Buenaventura,CO,CO,Colombia,SAM,South America,3,0.0004177109440267335
Chikwawa,MW,MW,Malawi,EAF,East Africa,300,0.04177109440267335
East Sepik,PG,PG,Papua New Guinea,OCE,Oceania,53,0.007379560011138958
Faladje,ML,ML,Mali,WAF,West Africa,173,0.024087997772208297
Farafangana,MG,MG,Madagascar,ISL,Insular Africa,1,0.0001392369813422445
Faranah,GN,GN,Guinea,WAF,West Africa,60,0.00835421888053467
Ghana returning traveller,GH,GH,Ghana,WAF,West Africa,3,0.0004177109440267335
Guapi,CO,CO,Colombia,SAM,South America,4,0.000556947925368978
Homel,BJ,BJ,Benin,WAF,West Africa,102,0.014202172096908938
Ilorin,NG,NG,Nigeria,WAF,West Africa,8,0.001113895850737956
"Iquitos, Loreto Province",PE,PE,Peru,SAM,South America,11,0.0015316067947646894
Kawthaung,SMM,MM,Myanmar,WSEA,Western south-east Asia,51,0.007101086048454469
Kenya returning traveller,KE,KE,Kenya,EAF,East Africa,2,0.000278473962684489
Kilifi,KE,KE,Kenya,EAF,East Africa,71,0.009885825675299359
Kinshasa,CD,CD,Congo DR,CAF,Central Africa,366,0.050960735171261484
Kintampo,GH,GH,Ghana,WAF,West Africa,61,0.008493455861876914
Kisumu,KE,KE,Kenya,EAF,East Africa,34,0.004734057365636313
Kobeni,MR,MR,Mauritania,WAF,West Africa,23,0.0032024505708716233
Kolle,ML,ML,Mali,WAF,West Africa,51,0.007101086048454469
Kombewa,KE,KE,Kenya,EAF,East Africa,27,0.0037593984962406013
Koumassi,CI,CI,Ivory Coast,WAF,West Africa,19,0.0026455026455026454
Lab,Lab,Lab,Lab,Lab,Lab,76,0.010582010582010581
Loreto,PE,PE,Peru,SAM,South America,13,0.0018100807574491784
Madang,PG,PG,Papua New Guinea,OCE,Oceania,56,0.007797270955165692
Madina Samako,GM,GM,Gambia,WAF,West Africa,14,0.001949317738791423
Mae Sot,WTH,TH,Thailand,WSEA,Western south-east Asia,936,0.13032581453634084
Maevatanana,MG,MG,Madagascar,ISL,Insular Africa,18,0.002506265664160401
Mali returning traveller,ML,ML,Mali,WAF,West Africa,2,0.000278473962684489
Milne Bay,PG,PG,Papua New Guinea,OCE,Oceania,30,0.004177109440267335
Morogoro,TZ,TZ,Tanzania,EAF,East Africa,34,0.004734057365636313
Mozambique returning traveller,MZ,MZ,Mozambique,EAF,East Africa,1,0.0001392369813422445
Muheza,TZ,TZ,Tanzania,EAF,East Africa,16,0.002227791701475912
Muleba,TZ,TZ,Tanzania,EAF,East Africa,61,0.008493455861876914
Myitkyina,NMM,MM,Myanmar,WSEA,Western south-east Asia,28,0.003898635477582846
Nachingwea,TZ,TZ,Tanzania,EAF,East Africa,79,0.010999721526037315
Navrongo,GH,GH,Ghana,WAF,West Africa,841,0.11709830130882762
Nema,MR,MR,Mauritania,WAF,West Africa,33,0.004594820384294068
Nioro du Sahel,ML,ML,Mali,WAF,West Africa,52,0.007240323029796714
Njaiyel,GM,GM,Gambia,WAF,West Africa,16,0.002227791701475912
Nzerekore,GN,GN,Guinea,WAF,West Africa,137,0.019075466443887495
Pailin,WKH,KH,Cambodia,ESEA,Eastern south-east Asia,157,0.021860206070732385
Phuoc Long,VN,VN,Viet Nam,ESEA,Eastern south-east Asia,138,0.01921470342522974
Pikine,SN,SN,Senegal,WAF,West Africa,86,0.011974380395433026
Preah Vihear,NKH,KH,Cambodia,ESEA,Eastern south-east Asia,210,0.029239766081871343
Pursat,WKH,KH,Cambodia,ESEA,Eastern south-east Asia,540,0.07518796992481203
Pyin Oo Lwin,NMM,MM,Myanmar,WSEA,Western south-east Asia,23,0.0032024505708716233
Quibdo,CO,CO,Colombia,SAM,South America,3,0.0004177109440267335
Ramu,BD,BD,Bangladesh,SAS,South Asia,51,0.007101086048454469
Ranong,STH,TH,Thailand,WSEA,Western south-east Asia,27,0.0037593984962406013
Ratanakiri,NEKH,KH,Cambodia,ESEA,Eastern south-east Asia,243,0.03383458646616541
Selibaby,MR,MR,Mauritania,WAF,West Africa,21,0.0029239766081871343
Sisakhet,ETH,TH,Thailand,ESEA,Eastern south-east Asia,28,0.003898635477582846
Tanga,TZ,TZ,Tanzania,EAF,East Africa,160,0.02227791701475912
Tasanh,WKH,KH,Cambodia,ESEA,Eastern south-east Asia,65,0.009050403787245892
Thabeikkyin,NMM,MM,Myanmar,WSEA,Western south-east Asia,54,0.007518796992481203
Timika,ID,ID,Indonesia,OCE,Oceania,92,0.012809802283486493
Tumaco,CO,CO,Colombia,SAM,South America,7,0.0009746588693957114
Uganda returning traveller,UG,UG,Uganda,EAF,East Africa,2,0.000278473962684489
West Arsi Zone,ET,ET,Ethiopia,EAF,East Africa,19,0.0026455026455026454
Xepon,LA,LA,Laos,ESEA,Eastern south-east Asia,45,0.006265664160401002
Yopougon,CI,CI,Ivory Coast,WAF,West Africa,20,0.00278473962684489
Zomba,MW,MW,Malawi,EAF,East Africa,51,0.007101086048454469

# Year

In [238]:
tbl_panoptes_samples_final.valuecounts('Year_source').displayall()

Year_source,count,frequency
Olivo,1903,0.2649679754942913
SIS,1681,0.234057365636313
study,1495,0.20815928710665552
sampling_date,584,0.08131439710387078
elife,492,0.06850459482038429
Rob,387,0.05388471177944862
Lucas,326,0.045391255917571705
inferred,236,0.0328599275967697
Lab,66,0.009189640768588136
duplicate,10,0.001392369813422445
Inferred,2,0.000278473962684489

In [239]:
tbl_panoptes_samples_final.valuecounts('Year').displayall()

Year,count,frequency
2013,1779,0.24770258980785295
2011,1351,0.1881091617933723
2014,873,0.12155388471177944
2012,862,0.12002227791701475
2008,644,0.08966861598440545
2010,605,0.08423837371205792
2007,240,0.03341687552213868
2009,228,0.031746031746031744
2015,205,0.02854358117516012
2003,87,0.01211361737677527
2004,77,0.010721247563352826
Lab,76,0.010582010582010581
2002,52,0.007240323029796714
2005,51,0.007101086048454469
2001,38,0.005291005291005291
2011†,12,0.001670843776106934
2006,2,0.000278473962684489

# Date

In [240]:
tbl_panoptes_samples_final.valuecounts('Date').display(50)

Date,count,frequency
-,832,0.11584516847674742
2011,542,0.07546644388749651
2010,329,0.04580896686159844
2008,237,0.032999164578111945
None,205,0.02854358117516012
2013,200,0.0278473962684489
2007,164,0.022834864940128097
2014-10-01,86,0.011974380395433026
2012,85,0.011835143414090782
Lab,70,0.009746588693957114
2009,46,0.006404901141743247
2014-11-13 00:00:00,40,0.00556947925368978
2014-12-13 00:00:00,23,0.0032024505708716233
2014-01-14 00:00:00,22,0.003063213589529379
2013-08-08 00:00:00,18,0.002506265664160401
2014-10-13 00:00:00,18,0.002506265664160401
30/10/2013,16,0.002227791701475912
2014-11-03,15,0.0020885547201336674
2013-09-12 00:00:00,13,0.0018100807574491784
2013-08-07 00:00:00,13,0.0018100807574491784
2013-08-05 00:00:00,13,0.0018100807574491784
2013-08-09 00:00:00,12,0.001670843776106934
18/10/2013,12,0.001670843776106934
2014-11-10 00:00:00,12,0.001670843776106934
2013-08-14 00:00:00,12,0.001670843776106934
2014-11-14 00:00:00,11,0.0015316067947646894
not indicated,11,0.0015316067947646894
2013-07-31 00:00:00,11,0.0015316067947646894
2013-08-06 00:00:00,11,0.0015316067947646894
2012-10-08 00:00:00,10,0.001392369813422445
21/10/2013,10,0.001392369813422445
14/10/2013,10,0.001392369813422445
2012-09-13 00:00:00,10,0.001392369813422445
17/10/2013,10,0.001392369813422445
2013-09-10 00:00:00,10,0.001392369813422445
2014-06-05,10,0.001392369813422445
2013-08-10 00:00:00,10,0.001392369813422445
2013-09-23 00:00:00,10,0.001392369813422445
2011-06-23 00:00:00,10,0.001392369813422445
2013-10-10 00:00:00,10,0.001392369813422445
2013-08-01 00:00:00,10,0.001392369813422445
2013-02-10 00:00:00,10,0.001392369813422445
16/12/2014,10,0.001392369813422445
2013-07-30 00:00:00,9,0.0012531328320802004
2013-01-28 00:00:00,9,0.0012531328320802004
2014-11-17 00:00:00,9,0.0012531328320802004
2013-06-17 00:00:00,9,0.0012531328320802004
2013-08-12 00:00:00,9,0.0012531328320802004
2012-10-05 00:00:00,9,0.0012531328320802004
2014-11-04 00:00:00,9,0.0012531328320802004

# HasDuplicate

In [241]:
tbl_panoptes_samples_final.valuecounts('HasDuplicate').displayall()

HasDuplicate,count,frequency
False,6358,0.8852687273739905
True,824,0.11473127262600946

# DiscardAsDuplicate

In [242]:
tbl_panoptes_samples_final.valuecounts('DiscardAsDuplicate').displayall()

DiscardAsDuplicate,count,frequency
False,6696,0.9323308270676691
True,486,0.06766917293233082

In [243]:
tbl_panoptes_samples_final.valuecounts('HasDuplicate', 'DiscardAsDuplicate').displayall()

HasDuplicate,DiscardAsDuplicate,count,frequency
False,False,6358,0.8852687273739905
True,True,486,0.06766917293233082
True,False,338,0.04706209969367864

In [244]:
for missingness_threshold in [1.0, 0.5, 0.2, 0.1, 0.05, 0.02, 0.01]:
    print(
        missingness_threshold,
        len(
            tbl_panoptes_samples_final
            .select(lambda rec: float(rec['pc_pass_missing']) < missingness_threshold)
            .selecteq('DiscardAsDuplicate', 'False')
            .selectne('Site', 'Lab')
            .data()
        )
    )

1.0 6621
0.5 6386
0.2 6023
0.1 5429
0.05 4522
0.02 2347
0.01 518

In [247]:
"In the Pf 6.0 release call set there are %d samples from %d countries." % (
    len(tbl_panoptes_samples_final.data()),
    len(tbl_panoptes_samples_final.selectne('CountryName', 'Lab').valuecounts('CountryName').data())
)

'In the Pf 6.0 release call set there are 7182 samples from 29 countries.'

In [248]:
"After removing lab samples there are %d samples from %d countries." % (
    len(tbl_panoptes_samples_final.selectne('CountryName', 'Lab').data()),
    len(tbl_panoptes_samples_final.selectne('CountryName', 'Lab').valuecounts('CountryName').data())
)

'After removing lab samples there are 7106 samples from 29 countries.'

In [250]:
"After removing lab samples and duplicates there are %d samples from %d countries." % (
    len(tbl_panoptes_samples_final.selectne('CountryName', 'Lab').selecteq('DiscardAsDuplicate', 'False').data()),
    len(tbl_panoptes_samples_final.selectne('CountryName', 'Lab').selecteq('DiscardAsDuplicate', 'False').valuecounts('CountryName').data())
)

'After removing lab samples and duplicates there are 6621 samples from 29 countries.'

In [252]:
"Subsetting to samples included in Pf 5.0 there are %d samples from %d countries." % (
    len(tbl_panoptes_samples_final.selectne('CountryName', 'Lab').selecteq('DiscardAsDuplicate', 'False').selecteq('InV5', 'True').data()),
    len(tbl_panoptes_samples_final.selectne('CountryName', 'Lab').selecteq('DiscardAsDuplicate', 'False').selecteq('InV5', 'True').valuecounts('CountryName').data())
)

'Subsetting to samples included in Pf 5.0 there are 5658 samples from 25 countries.'